<script setup>
import MButton from '../../components/mds/MButton.vue';
import MDialog from '../../components/mds/MDialog.vue';
import MEmptyState from '../../components/mds/MEmptyState.vue';
import MTag from '../../components/mds/MTag.vue';
import { ref } from 'vue';

defineProps({ bookings: { type: Array, default: () => [] }, totalAmount: { type: [String, Number], default: null }, error: { type: String, default: '' }, canCreate: { type: Boolean, default: false }, canEdit: { type: Function, default: () => false }, canDelete: { type: Boolean, default: false }, deletingId: { type: Number, default: null }, deleteError: { type: String, default: '' } });
const emit = defineEmits(['create', 'edit', 'delete']);
const pendingDelete = ref(null);
function formatDate(value) { const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(value || '')); return match ? `${match[3]}/${match[2]}/${match[1]}` : '—'; }
function formatAmount(value) { const numeric = Number(value); return Number.isFinite(numeric) ? `${new Intl.NumberFormat('vi-VN').format(numeric)} đ` : '—'; }
function statusColor(value) { return ({ 'Đã đặt': 'warning', 'Đã đăng': 'brand', 'Đã nghiệm thu': 'success', Hủy: 'neutral' })[value] || 'neutral'; }
</script>

<template>
  <section class="space-y-4"><div class="flex flex-wrap items-end justify-between gap-3"><div><h2 class="text-[16px] font-semibold leading-[22px]">Booking bài viết</h2><p class="mt-1 text-[13px] leading-[18px] text-[var(--mds-text-secondary)]">Số tiền chỉ hiển thị khi máy chủ đã projection theo ownership. Tổng tiền không được tự tính ở giao diện.</p></div><div class="flex items-end gap-3"><div class="text-right"><p class="text-[12px] text-[var(--mds-text-secondary)]">Tổng booking</p><p class="text-[16px] font-semibold leading-[22px]">{{ typeof totalAmount === 'number' ? formatAmount(totalAmount) : (totalAmount || '—') }}</p></div><MButton v-if="canCreate" variant="primary" @click="emit('create')">Thêm booking</MButton></div></div><p v-if="error" role="alert" class="rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] leading-[18px] text-[var(--mds-danger)]">{{ error }}</p><p v-if="deleteError" role="alert" class="rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] leading-[18px] text-[var(--mds-danger)]">{{ deleteError }}</p><div v-if="bookings.length" class="divide-y divide-[var(--mds-border-light)] rounded-lg border border-[var(--mds-border-light)]"><article v-for="booking in bookings" :key="booking.id" class="flex min-h-[64px] items-center justify-between gap-4 px-3 py-3"><div class="min-w-0"><strong class="block truncate text-[13px]">{{ booking.title }}</strong><span class="mt-1 block text-[12px] text-[var(--mds-text-secondary)]">{{ booking.contentType }} · Đặt {{ booking.bookedDate }} · Dự kiến {{ booking.publishDate }}</span></div><div class="flex shrink-0 items-center gap-3"><span v-if="booking.hasAmount" class="text-[13px] font-medium">{{ formatAmount(booking.amount) }}</span><MTag :color="statusColor(booking.status)">{{ booking.status }}</MTag><MButton v-if="canEdit(booking)" variant="link" @click="emit('edit', booking)">Sửa</MButton><MButton v-if="canDelete" variant="link" class="text-[var(--mds-danger)]" :disabled="deletingId === booking.id" @click="pendingDelete = booking">Xóa</MButton></div></article></div><MEmptyState v-else title="Chưa có booking" description="Booking bài viết của nhân sự này sẽ xuất hiện ở đây." /><MDialog :model-value="pendingDelete !== null" title="Xóa booking?" type="danger" confirm-text="Xóa booking" @update:model-value="(open) => { if (!open) pendingDelete = null; }" @confirm="emit('delete', pendingDelete.id)"><p>Booking <strong>{{ pendingDelete?.title }}</strong> sẽ bị xóa. Thao tác này không thể hoàn tác.</p></MDialog></section>
</template>
