<script setup>
import { computed } from 'vue';

const props = defineProps({ modelValue: { type: [Boolean, Array], default: false }, value: { type: [String, Number, Boolean, Object], default: undefined }, label: { type: String, default: '' }, inputAriaLabel: { type: String, default: '' }, indeterminate: Boolean, disabled: Boolean, error: { type: String, default: '' } });
const emit = defineEmits(['update:modelValue', 'change']);
const isArrayMode = computed(() => Array.isArray(props.modelValue));
const checked = computed(() => isArrayMode.value ? props.modelValue.includes(props.value) : Boolean(props.modelValue));
function toggle(event) { if (props.disabled) return; const next = isArrayMode.value ? (checked.value ? props.modelValue.filter((item) => item !== props.value) : [...props.modelValue, props.value]) : !checked.value; emit('update:modelValue', next); emit('change', next, event); }
</script>
<template><label class="inline-flex items-start gap-2" :class="disabled ? 'cursor-not-allowed' : 'cursor-pointer'"><input type="checkbox" class="sr-only" :checked="checked" :disabled="disabled" :aria-checked="indeterminate ? 'mixed' : checked" :aria-label="inputAriaLabel || undefined" @change="toggle"/><span class="mt-px flex h-4 w-4 shrink-0 items-center justify-center rounded-[3px] border-[1.5px] transition-colors focus-within:outline focus-within:outline-2 focus-within:outline-offset-2 focus-within:outline-[var(--mds-brand-600)]" :class="checked || indeterminate ? 'border-[var(--mds-brand-600)] bg-[var(--mds-brand-600)]' : [error ? 'border-[var(--mds-danger)]' : 'border-[var(--mds-border)]', disabled ? 'bg-[var(--mds-bg-disabled)]' : 'bg-[var(--mds-bg)] hover:border-[var(--mds-brand-600)]']"><span v-if="indeterminate" class="h-px w-2 bg-white"></span><span v-else-if="checked" class="text-[12px] leading-none text-white" aria-hidden="true">✓</span></span><span v-if="label || $slots.default" class="select-none text-[13px] leading-[18px]" :class="disabled ? 'text-[var(--mds-text-placeholder)]' : 'text-[var(--mds-text)]'"><slot>{{ label }}</slot></span></label><p v-if="error" class="mt-1 text-[12px] leading-4 text-[var(--mds-danger)]">{{ error }}</p></template>
