<script setup>
import { computed, nextTick, onBeforeUnmount, onMounted, reactive, ref } from 'vue';
import MEmptyState from '../../components/mds/MEmptyState.vue'; import MMobileTopBar from '../../components/mds/MMobileTopBar.vue'; import MSpinner from '../../components/mds/MSpinner.vue';
import { HostEvent, HostSurface } from '../../platform/host-adapter.mjs'; import { createInteractionsApi, InteractionsApiError } from './domain/interactions-api.mjs'; import { createVoiceApi, createVoiceIdempotencyKey } from '../voice/domain/voice-api.mjs'; import { interactionsListViewModel } from './domain/interactions-view.mjs';
import InteractionsListDesktop from './desktop/InteractionsListDesktop.vue'; import InteractionsListMobile from './mobile/InteractionsListMobile.vue'; import InteractionCreateDesktop from './desktop/InteractionCreateDesktop.vue'; import InteractionCreateMobile from './mobile/InteractionCreateMobile.vue'; import VoiceProposalDesktop from '../voice/desktop/VoiceProposalDesktop.vue'; import VoiceProposalMobile from '../voice/mobile/VoiceProposalMobile.vue';
const props = defineProps({ surface: { type: String, required: true }, adapter: { type: Object, default: null }, hostUnavailable: Boolean }); const emit = defineEmits(['back']); const api = createInteractionsApi(); const voiceApi = createVoiceApi(); const desktopVoice = ref(null); const nativeVoice = ref(null); const safeArea = ref(props.adapter?.getSafeArea?.() || {}); const unsubscribers = [];
const state = reactive({ phase: 'loading', rows: [], total: 0, page: 1, pageSize: 20, search: '', permissions: null, mode: 'read', partner: null, partnerResults: [], searchingPartners: false, saving: false, saveError: '', voiceProposal: null, voiceProcessing: false, voiceSaving: false, voiceError: '', voiceIdempotencyKey: '', error: null });
const isNative = computed(() => props.surface === HostSurface.NATIVE); const canCreate = computed(() => state.permissions?.modules?.interactions?.includes('create') === true); const safeAreaStyle = computed(() => Object.fromEntries(['top','right','bottom','left'].flatMap((side) => Number.isFinite(Number(safeArea.value?.[side])) ? [[`--mds-mobile-safe-${side}`, `${Number(safeArea.value[side])}px`]] : [])));
function setError(error) { state.error = error instanceof InteractionsApiError ? error : new InteractionsApiError({ status: 0, code: 'INTERACTIONS_NETWORK', message: 'Không thể tải tương tác. Vui lòng thử lại.' }); state.phase = 'error'; }
async function load({ page = state.page, search = state.search } = {}) { if (props.hostUnavailable) { setError(new InteractionsApiError({ status: 503, code: 'HOST_ADAPTER_UNAVAILABLE', message: 'Native host chưa sẵn sàng. Ứng dụng không chuyển sang giao diện desktop thay thế.' })); return; } state.phase = 'loading'; try { const [payload, session] = await Promise.all([api.getList({ page, pageSize: state.pageSize, search }), api.getCurrentUser()]); const model = interactionsListViewModel(payload); Object.assign(state, { rows: model.rows, total: model.total, page: model.page, pageSize: model.pageSize, search, permissions: session?.permissions || null, mode: 'read', phase: 'ready', error: null }); } catch (error) { setError(error); } }
function beginCreate() { if (canCreate.value) { state.mode = 'create'; state.partner = null; state.partnerResults = []; state.saveError = ''; } } function beginVoice() { if (canCreate.value) Object.assign(state, { mode: 'voice', voiceProposal: null, voiceError: '', voiceIdempotencyKey: '' }); }
async function searchPartners(query) { if (!query) return; state.searchingPartners = true; try { state.partnerResults = await api.searchEntities(query); } catch (error) { state.saveError = error.message; } finally { state.searchingPartners = false; } } async function save(payload) { state.saving = true; try { await api.create(payload); await load(); } catch (error) { state.saveError = error.message; } finally { state.saving = false; } }
async function proposeVoice(audio) { state.voiceProcessing = true; state.voiceError = ''; try { state.voiceProposal = await voiceApi.propose(audio); await nextTick(); (isNative.value ? nativeVoice : desktopVoice).value?.syncProposal(); } catch (error) { state.voiceError = error.message; } finally { state.voiceProcessing = false; } } async function confirmVoice(edits) { state.voiceSaving = true; state.voiceError = ''; try { state.voiceIdempotencyKey ||= createVoiceIdempotencyKey(); await voiceApi.confirm({ proposalId: state.voiceProposal.proposalId, idempotencyKey: state.voiceIdempotencyKey, edits }); await load(); } catch (error) { state.voiceError = error.message; } finally { state.voiceSaving = false; } }
async function goBack() { if (isNative.value && props.adapter) return props.adapter.goBack({ reason: 'interactions-list' }); emit('back'); } function listen() { if (!props.adapter || props.hostUnavailable) return; unsubscribers.push(props.adapter.subscribe(HostEvent.VIEWPORT, (payload) => { if (payload?.safeArea) safeArea.value = { ...safeArea.value, ...payload.safeArea }; })); } onMounted(() => { listen(); load(); }); onBeforeUnmount(() => { while (unsubscribers.length) unsubscribers.pop()(); });
</script>
<template><div v-if="state.phase === 'loading'" :class="isNative ? 'mds-mobile-app grid h-[100dvh] place-items-center bg-[var(--mds-bg)]' : 'grid min-h-[360px] place-items-center bg-[var(--mds-bg-page)]'" :style="isNative ? safeAreaStyle : undefined"><MSpinner :size="28" /></div><section v-else-if="state.phase === 'error'" :class="isNative ? 'mds-mobile-app min-h-[100dvh] bg-[var(--mds-bg)]' : 'min-h-[360px] bg-[var(--mds-bg-page)]'"><MMobileTopBar v-if="isNative" title="Lịch sử tương tác" @back="goBack" /><MEmptyState :title="state.error.status === 403 ? 'Bạn không có quyền xem tương tác' : 'Không thể mở tương tác'" :description="state.error.message" /></section><VoiceProposalMobile v-else-if="isNative && state.mode === 'voice'" ref="nativeVoice" :proposal="state.voiceProposal" :processing="state.voiceProcessing" :saving="state.voiceSaving" :error="state.voiceError" :safe-area-style="safeAreaStyle" @cancel="state.mode = 'read'" @propose="proposeVoice" @confirm="confirmVoice" /><InteractionCreateMobile v-else-if="isNative && state.mode === 'create'" :partner="state.partner" :results="state.partnerResults" :searching="state.searchingPartners" :saving="state.saving" :server-error="state.saveError" :safe-area-style="safeAreaStyle" @cancel="state.mode = 'read'" @search="searchPartners" @select="state.partner = $event" @save="save" /><InteractionsListMobile v-else-if="isNative" :rows="state.rows" :total="state.total" :page="state.page" :page-size="state.pageSize" :search="state.search" :can-create="canCreate" :safe-area-style="safeAreaStyle" @back="goBack" @create="beginCreate" @voice="beginVoice" @search="load({ page: 1, search: $event })" @page="load({ page: $event })" /><VoiceProposalDesktop v-else-if="state.mode === 'voice'" ref="desktopVoice" :proposal="state.voiceProposal" :processing="state.voiceProcessing" :saving="state.voiceSaving" :error="state.voiceError" @cancel="state.mode = 'read'" @propose="proposeVoice" @confirm="confirmVoice" /><InteractionCreateDesktop v-else-if="state.mode === 'create'" :partner="state.partner" :results="state.partnerResults" :searching="state.searchingPartners" :saving="state.saving" :server-error="state.saveError" @cancel="state.mode = 'read'" @search="searchPartners" @select="state.partner = $event" @save="save" /><InteractionsListDesktop v-else :rows="state.rows" :total="state.total" :page="state.page" :page-size="state.pageSize" :search="state.search" :can-create="canCreate" @create="beginCreate" @voice="beginVoice" @search="load({ page: 1, search: $event })" @page="load({ page: $event })" /></template>
