<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import MDialog from '../../components/mds/MDialog.vue'; import MEmptyState from '../../components/mds/MEmptyState.vue'; import MMobileTopBar from '../../components/mds/MMobileTopBar.vue'; import MSpinner from '../../components/mds/MSpinner.vue';
import { HostSurface } from '../../platform/host-adapter.mjs'; import { createRemindersApi } from './domain/reminders-api.mjs'; import { reminderViewModel } from './domain/reminders-view.mjs';
import RemindersListDesktop from './desktop/RemindersListDesktop.vue'; import ReminderFormDesktop from './desktop/ReminderFormDesktop.vue'; import RemindersListMobile from './mobile/RemindersListMobile.vue'; import ReminderFormMobile from './mobile/ReminderFormMobile.vue';
const props = defineProps({ surface: { type: String, required: true }, adapter: { type: Object, default: null }, hostUnavailable: Boolean }); const emit = defineEmits(['back']); const api = createRemindersApi(); const isNative = computed(() => props.surface === HostSurface.NATIVE); const safeArea = ref(props.adapter?.getSafeArea?.() || {}); const safeAreaStyle = computed(() => Object.fromEntries(['top', 'right', 'bottom', 'left'].flatMap((side) => Number.isFinite(Number(safeArea.value?.[side])) ? [[`--mds-mobile-safe-${side}`, `${Number(safeArea.value[side])}px`]] : [])));
const state = reactive({ phase: 'loading', rows: [], upcoming: [], days: 120, permissions: null, mode: 'read', editing: null, saving: false, saveError: '', deleting: null, deleteError: '', error: null });
const canCreate = computed(() => state.permissions?.modules?.reminders?.includes('create') === true); const canEdit = computed(() => state.permissions?.modules?.reminders?.includes('edit') === true); const canDelete = computed(() => state.permissions?.modules?.reminders?.includes('delete') === true);
async function load() { if (props.hostUnavailable) { state.phase = 'error'; state.error = { status: 503, message: 'Native host chưa sẵn sàng. Ứng dụng không chuyển sang giao diện desktop thay thế.' }; return; } state.phase = 'loading'; state.error = null; try { const [rows, upcoming, session] = await Promise.all([api.getAll(), api.getUpcoming(state.days), api.getCurrentUser()]); Object.assign(state, { rows: reminderViewModel(rows), upcoming: reminderViewModel(upcoming.rows), days: upcoming.days, permissions: session?.permissions || null, phase: 'ready', mode: 'read', saveError: '' }); } catch (error) { state.phase = 'error'; state.error = error; } }
function beginCreate() { if (canCreate.value) { state.editing = null; state.saveError = ''; state.mode = 'form'; } }
function beginEdit(record) { if (canEdit.value && record?.id) { state.editing = record; state.saveError = ''; state.mode = 'form'; } }
function cancelForm() { state.editing = null; state.saveError = ''; state.mode = 'read'; }
async function save(input) { state.saving = true; state.saveError = ''; try { await api.save(input, state.editing?.id ?? null); await load(); } catch (error) { state.saveError = error.message; } finally { state.saving = false; } }
function askDelete(record) { if (canDelete.value && record?.id) { state.deleting = record; state.deleteError = ''; } }
async function remove() { const record = state.deleting; if (!record?.id) return; state.deleting = null; try { await api.remove(record.id); await load(); } catch (error) { state.deleteError = error.message; } }
function cancelDelete() { state.deleting = null; }
function back() { if (isNative.value && props.adapter) return props.adapter.goBack({ reason: 'reminders' }); emit('back'); }
onMounted(load);
</script>
<template><div v-if="state.phase === 'loading'" :class="isNative ? 'mds-mobile-app grid h-[100dvh] place-items-center bg-[var(--mds-bg)]' : 'grid min-h-[360px] place-items-center bg-[var(--mds-bg-page)]'" :style="isNative ? safeAreaStyle : undefined"><MSpinner :size="28" /></div><section v-else-if="state.phase === 'error'" :class="isNative ? 'mds-mobile-app min-h-[100dvh] bg-[var(--mds-bg)]' : 'min-h-[360px] bg-[var(--mds-bg-page)]'" :style="isNative ? safeAreaStyle : undefined"><MMobileTopBar v-if="isNative" title="Lịch nhắc" @back="back" /><MEmptyState :title="state.error.status === 403 ? 'Bạn không có quyền xem lịch nhắc' : 'Không thể mở lịch nhắc'" :description="state.error.message" /></section><ReminderFormMobile v-else-if="isNative && state.mode === 'form'" :record="state.editing" :editing="Boolean(state.editing)" :saving="state.saving" :error="state.saveError" :safe-area-style="safeAreaStyle" @cancel="cancelForm" @save="save" /><RemindersListMobile v-else-if="isNative" :rows="state.rows" :upcoming="state.upcoming" :days="state.days" :can-create="canCreate" :can-edit="canEdit" :can-delete="canDelete" :safe-area-style="safeAreaStyle" @back="back" @create="beginCreate" @edit="beginEdit" @delete="askDelete" /><ReminderFormDesktop v-else-if="state.mode === 'form'" :record="state.editing" :editing="Boolean(state.editing)" :saving="state.saving" :error="state.saveError" @cancel="cancelForm" @save="save" /><RemindersListDesktop v-else :rows="state.rows" :upcoming="state.upcoming" :days="state.days" :can-create="canCreate" :can-edit="canEdit" :can-delete="canDelete" @create="beginCreate" @edit="beginEdit" @delete="askDelete" /><MDialog :model-value="Boolean(state.deleting)" title="Xóa ngày nhắc?" type="danger" confirm-text="Xóa" @update:model-value="!$event && cancelDelete" @cancel="cancelDelete" @confirm="remove"><p>Ngày nhắc <strong>{{ state.deleting?.title }}</strong> sẽ bị xóa. Máy chủ sẽ kiểm tra lại quyền trước khi thực hiện.</p><p v-if="state.deleteError" class="mt-2 text-[var(--mds-danger)]">{{ state.deleteError }}</p></MDialog></template>
