<script setup>
import { reactive, watch } from 'vue';
import MButton from '../../../components/mds/MButton.vue';
import MInput from '../../../components/mds/MInput.vue';
import MMobileTopBar from '../../../components/mds/MMobileTopBar.vue';
import MSelect from '../../../components/mds/MSelect.vue';
import MTextarea from '../../../components/mds/MTextarea.vue';
import { MENTION_SENTIMENT_OPTIONS, MENTION_STATUS_OPTIONS, toMentionReviewDraft, toMentionReviewPayload } from '../domain/monitoring-mention-write.mjs';
const props=defineProps({record:Object,saving:Boolean,error:String,safeAreaStyle:Object});const emit=defineEmits(['cancel','save']);const draft=reactive({...toMentionReviewDraft()});watch(()=>props.record,(record)=>Object.assign(draft,toMentionReviewDraft(record)),{immediate:true});const sentiments=MENTION_SENTIMENT_OPTIONS.map((value)=>({value,label:{'':'Chưa chấm',positive:'Tích cực',neutral:'Trung tính',negative:'Tiêu cực'}[value]}));const statuses=MENTION_STATUS_OPTIONS.map((value)=>({value,label:value}));function submit(){emit('save',toMentionReviewPayload(draft));}
</script>
<template><section class="mds-mobile-app flex h-[100dvh] min-w-0 flex-col overflow-hidden bg-[var(--mds-bg)]" :style="safeAreaStyle"><MMobileTopBar title="Cập nhật tin" @back="emit('cancel')"/><form class="min-h-0 flex flex-1 flex-col" @submit.prevent="submit"><main class="min-h-0 flex-1 overflow-y-auto"><div class="mds-mobile-gutter-x space-y-4 py-4"><p class="text-[13px] text-[var(--mds-text-secondary)]">{{record?.title||'—'}}</p><p v-if="error" class="rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{error}}</p><p class="rounded-lg bg-[var(--mds-bg-page)] px-3 py-2 text-[13px]">Máy chủ sẽ kiểm tra lại quyền trước khi lưu.</p><label><span class="mb-1 block text-[13px] font-medium">Sắc thái</span><MSelect v-model="draft.sentiment" :options="sentiments"/></label><label><span class="mb-1 block text-[13px] font-medium">Tình trạng xử lý</span><MSelect v-model="draft.status" :options="statuses"/></label><label><span class="mb-1 block text-[13px] font-medium">Nhân sự phụ trách</span><MInput v-model="draft.assignee" placeholder="Nguyễn Minh Hà"/></label><label><span class="mb-1 block text-[13px] font-medium">Tag</span><MInput v-model="draft.tags" placeholder="khách hàng, cần phản hồi"/></label><label><span class="mb-1 block text-[13px] font-medium">Việc cần làm tiếp</span><MInput v-model="draft.nextAction" placeholder="Liên hệ tòa soạn"/></label><label><span class="mb-1 block text-[13px] font-medium">Ghi chú xử lý</span><MTextarea v-model="draft.note" :rows="5" placeholder="Ghi rõ kết quả review…"/></label></div></main><footer class="flex gap-2 border-t border-[var(--mds-border-light)] bg-[var(--mds-bg)] px-4 pb-[calc(12px+var(--mds-mobile-safe-bottom))] pt-3"><MButton variant="neutral" class="flex-1 [&]:h-[var(--mds-mobile-touch-target)]" :disabled="saving" @click="emit('cancel')">Hủy</MButton><MButton variant="primary" class="flex-1 [&]:h-[var(--mds-mobile-touch-target)]" :loading="saving" @click="submit">Lưu</MButton></footer></form></section></template>
