<script setup>
import { computed, reactive, ref, watch } from 'vue';
import MButton from '../../../components/mds/MButton.vue';
import MDialog from '../../../components/mds/MDialog.vue';
import MInput from '../../../components/mds/MInput.vue';
import MMobileTopBar from '../../../components/mds/MMobileTopBar.vue';
import MSelect from '../../../components/mds/MSelect.vue';
import MTextarea from '../../../components/mds/MTextarea.vue';
import { toSupplierEditDraft, toSupplierUpdatePayload, validateSupplierEditDraft } from '../domain/supplier-write.mjs';
const props = defineProps({ record: { type: Object, required: true }, saving: { type: Boolean, default: false }, serverError: { type: String, default: '' }, safeAreaStyle: { type: Object, default: () => ({}) } });
const emit = defineEmits(['cancel', 'save']); const draft = reactive({}); const errors = reactive({}); const confirmDiscard = ref(false); const initialDraft = ref('');
const industries = ['', 'Tổ chức sự kiện', 'In ấn', 'Quà tặng', 'Truyền thông', 'Thiết kế', 'Âm thanh ánh sáng', 'Nhân sự thời vụ', 'Khác'].map((value) => ({ value, label: value || 'Chọn lĩnh vực' }));
const invoices = [{ value: '', label: 'Chọn loại hóa đơn' }, { value: 'VAT', label: 'VAT' }, { value: 'Trực tiếp 0%', label: 'Trực tiếp 0%' }];
const isDirty = computed(() => JSON.stringify(draft) !== initialDraft.value);
function resetDraft() { Object.assign(draft, toSupplierEditDraft(props.record)); initialDraft.value = JSON.stringify(draft); Object.keys(errors).forEach((key) => delete errors[key]); }
watch(() => props.record, resetDraft, { immediate: true });
function requestCancel() { if (props.saving) return; if (isDirty.value) { confirmDiscard.value = true; return; } emit('cancel'); }
function submit() { const nextErrors = validateSupplierEditDraft(draft); Object.keys(errors).forEach((key) => delete errors[key]); Object.assign(errors, nextErrors); if (Object.keys(nextErrors).length) return; emit('save', toSupplierUpdatePayload(draft)); }
</script>

<template>
  <section class="mds-mobile-app flex h-[100dvh] min-w-0 flex-col overflow-hidden bg-[var(--mds-bg)] text-[var(--mds-text)]" :style="safeAreaStyle"><MMobileTopBar title="Chỉnh sửa nhà cung cấp" @back="requestCancel"><template #actions><MButton variant="link" :disabled="saving" @click="requestCancel">Hủy</MButton></template></MMobileTopBar><form class="flex min-h-0 flex-1 flex-col" novalidate @submit.prevent="submit"><div class="min-h-0 flex-1 overflow-y-auto"><p class="mds-mobile-gutter-x border-b border-[var(--mds-border-light)] py-3 text-[13px] leading-[18px] text-[var(--mds-text-secondary)]">Chỉ thông tin hồ sơ công khai được gửi. Điều khoản thương mại và đầu mối không thay đổi.</p><div class="mds-mobile-gutter-x space-y-4 py-4"><label class="block"><span class="mb-1.5 block text-[13px] font-medium leading-[18px]">Tên nhà cung cấp <span class="text-[var(--mds-danger)]">*</span></span><MInput v-model="draft.name" placeholder="Nhập tên nhà cung cấp" :error="errors.name" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium leading-[18px]">Lĩnh vực</span><MSelect v-model="draft.industry" :options="industries" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium leading-[18px]">Loại hóa đơn</span><MSelect v-model="draft.invoice_type" :options="invoices" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium leading-[18px]">Địa chỉ</span><MInput v-model="draft.address" placeholder="Nhập địa chỉ" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium leading-[18px]">Mã số thuế</span><MInput v-model="draft.tax_code" placeholder="Nhập mã số thuế" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium leading-[18px]">Dịch vụ cung cấp</span><MInput v-model="draft.services" placeholder="Ví dụ: In ấn, tổ chức sự kiện" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium leading-[18px]">Ghi chú</span><MTextarea v-model="draft.note" placeholder="Nhập ghi chú" :disabled="saving" /></label><p v-if="serverError" role="alert" class="rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] leading-[18px] text-[var(--mds-danger)]">{{ serverError }}</p></div></div><footer class="shrink-0 border-t border-[var(--mds-border-light)] bg-[var(--mds-bg)] px-4 pb-[calc(12px+var(--mds-mobile-safe-bottom))] pt-3"><MButton variant="primary" class="w-full" :loading="saving" :disabled="saving" @click="submit">Lưu thay đổi</MButton></footer></form><MDialog v-model="confirmDiscard" title="Bỏ thay đổi?" type="danger" confirm-text="Bỏ thay đổi" @confirm="emit('cancel')"><p>Các thay đổi chưa lưu sẽ không được giữ lại.</p></MDialog></section>
</template>
