<script setup>
import { reactive, watch } from 'vue';
import MButton from '../../../components/mds/MButton.vue'; import MInput from '../../../components/mds/MInput.vue'; import MSelect from '../../../components/mds/MSelect.vue'; import MTextarea from '../../../components/mds/MTextarea.vue';
import { reminderDraft } from '../domain/reminders-view.mjs';
const props = defineProps({ record: { type: Object, default: null }, editing: Boolean, saving: Boolean, error: { type: String, default: '' } }); const emit = defineEmits(['cancel', 'save']); const draft = reactive({ ...reminderDraft(props.record) });
watch(() => props.record, (record) => Object.assign(draft, reminderDraft(record)), { deep: true });
const dateTypes = Object.freeze([{ value: 'birthday', label: 'Sinh nhật' }, { value: 'founding', label: 'Thành lập' }, { value: 'anniversary', label: 'Kỷ niệm' }, { value: 'other', label: 'Khác' }]); const recurringOptions = Object.freeze([{ value: 1, label: 'Hằng năm' }, { value: 0, label: 'Một lần' }]);
function submit() { emit('save', { ...draft }); }
</script>
<template><section class="min-h-0 bg-[var(--mds-bg-page)] p-4"><form class="mx-auto max-w-[760px] rounded-lg bg-[var(--mds-bg)] p-5 shadow-[var(--mds-shadow-card)]" @submit.prevent="submit"><header class="mb-5"><h1 class="text-[20px] font-semibold">{{ editing ? 'Sửa ngày nhắc' : 'Thêm ngày nhắc' }}</h1><p class="mt-1 text-[13px] text-[var(--mds-text-secondary)]">Thông tin này sẽ được máy chủ kiểm tra lại trước khi lưu.</p></header><p v-if="error" class="mb-4 rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{ error }}</p><div class="grid gap-4 sm:grid-cols-2"><label class="sm:col-span-2"><span class="mb-1 block text-[13px] font-medium">Tiêu đề</span><MInput v-model="draft.title" required placeholder="Ví dụ: Sinh nhật đối tác" /></label><label><span class="mb-1 block text-[13px] font-medium">Loại sự kiện</span><MSelect v-model="draft.date_type" :options="dateTypes" /></label><label><span class="mb-1 block text-[13px] font-medium">Ngày sự kiện</span><MInput v-model="draft.event_date" type="date" required /></label><label><span class="mb-1 block text-[13px] font-medium">Lặp lại</span><MSelect v-model="draft.recurring" :options="recurringOptions" /></label><label><span class="mb-1 block text-[13px] font-medium">Báo trước (ngày)</span><MInput v-model="draft.lead_days" type="number" /></label><label class="sm:col-span-2"><span class="mb-1 block text-[13px] font-medium">Đối tượng</span><MInput v-model="draft.subject_name" placeholder="Người hoặc cơ quan liên quan" /></label><label class="sm:col-span-2"><span class="mb-1 block text-[13px] font-medium">Ghi chú</span><MTextarea v-model="draft.note" :rows="4" placeholder="Thông tin cần lưu ý" /></label></div><footer class="mt-6 flex justify-end gap-2"><MButton type="button" variant="neutral" :disabled="saving" @click="emit('cancel')">Hủy</MButton><MButton type="submit" variant="primary" :loading="saving">{{ editing ? 'Lưu thay đổi' : 'Tạo ngày nhắc' }}</MButton></footer></form></section></template>
