<script setup>
import { reactive, watch } from 'vue';
import MButton from '../../../components/mds/MButton.vue';
import MInput from '../../../components/mds/MInput.vue';
import MSelect from '../../../components/mds/MSelect.vue';
import MTextarea from '../../../components/mds/MTextarea.vue';
import { MENTION_SENTIMENT_OPTIONS, MENTION_STATUS_OPTIONS, toMentionReviewDraft, toMentionReviewPayload } from '../domain/monitoring-mention-write.mjs';
const props=defineProps({record:Object,saving:Boolean,error:String});const emit=defineEmits(['cancel','save']);const draft=reactive({...toMentionReviewDraft()});watch(()=>props.record,(record)=>Object.assign(draft,toMentionReviewDraft(record)),{immediate:true});const sentiments=MENTION_SENTIMENT_OPTIONS.map((value)=>({value,label:{'':'Chưa chấm',positive:'Tích cực',neutral:'Trung tính',negative:'Tiêu cực'}[value]}));const statuses=MENTION_STATUS_OPTIONS.map((value)=>({value,label:value}));function submit(){emit('save',toMentionReviewPayload(draft));}
</script>
<template><section class="min-h-0 bg-[var(--mds-bg-page)] p-4"><form class="mx-auto flex min-h-[620px] max-w-[900px] flex-col overflow-hidden rounded-lg bg-[var(--mds-bg)] shadow-[var(--mds-shadow-card)]" @submit.prevent="submit"><header class="border-b border-[var(--mds-border-light)] px-5 py-4"><h1 class="text-[20px] font-semibold">Cập nhật xử lý tin</h1><p class="mt-1 text-[13px] text-[var(--mds-text-secondary)]">{{record?.sourceName||'—'}} · {{record?.title||'—'}}</p></header><main class="min-h-0 flex-1 space-y-4 overflow-y-auto px-5 py-4"><p v-if="error" class="rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{error}}</p><p class="rounded-lg bg-[var(--mds-bg-page)] px-3 py-2 text-[13px]">Máy chủ sẽ kiểm tra lại quyền cập nhật trước khi lưu.</p><div class="grid gap-4 md:grid-cols-2"><label><span class="mb-1 block text-[13px] font-medium">Sắc thái</span><MSelect v-model="draft.sentiment" :options="sentiments"/></label><label><span class="mb-1 block text-[13px] font-medium">Tình trạng xử lý</span><MSelect v-model="draft.status" :options="statuses"/></label><label><span class="mb-1 block text-[13px] font-medium">Nhân sự phụ trách</span><MInput v-model="draft.assignee" placeholder="Nguyễn Minh Hà"/></label><label><span class="mb-1 block text-[13px] font-medium">Tag (ngăn cách bằng dấu phẩy)</span><MInput v-model="draft.tags" placeholder="khách hàng, cần phản hồi"/></label></div><label><span class="mb-1 block text-[13px] font-medium">Việc cần làm tiếp theo</span><MInput v-model="draft.nextAction" placeholder="Liên hệ tòa soạn để làm rõ thông tin"/></label><label><span class="mb-1 block text-[13px] font-medium">Ghi chú xử lý</span><MTextarea v-model="draft.note" :rows="5" placeholder="Ghi rõ kết quả review và hướng xử lý…"/></label></main><footer class="sticky bottom-0 flex justify-end gap-2 border-t border-[var(--mds-border-light)] bg-[var(--mds-bg)] px-5 py-3"><MButton variant="neutral" :disabled="saving" @click="emit('cancel')">Hủy</MButton><MButton variant="primary" :loading="saving" @click="submit">Lưu cập nhật</MButton></footer></form></section></template>
