import { InteractionsApiError } from '../../interactions/domain/interactions-api.mjs';
function errorOf(status, payload) { return new InteractionsApiError({ status, code: payload?.code, message: payload?.message || payload?.error || 'Không thể tải báo cáo.' }); }
export function dateRange(kind = 'month', now = new Date()) { const year = now.getFullYear(); const month = now.getMonth(); const pad = (value) => String(value).padStart(2, '0'); const date = (y, m, d) => `${y}-${pad(m + 1)}-${pad(d)}`; const lastDay = (y, m) => new Date(y, m + 1, 0).getDate(); if (kind === 'year') return Object.freeze({ from: date(year, 0, 1), to: date(year, 11, 31), label: 'Năm nay' }); if (kind === 'quarter') { const start = Math.floor(month / 3) * 3; const end = start + 2; return Object.freeze({ from: date(year, start, 1), to: date(year, end, lastDay(year, end)), label: 'Quý này' }); } return Object.freeze({ from: date(year, month, 1), to: date(year, month, lastDay(year, month)), label: 'Tháng này' }); }
function rangeQuery(range) { return new URLSearchParams({ from: range.from, to: range.to }); }
async function getJson(fetchFn, url) { const response = await fetchFn(url, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload; }
export function createReportsApi({ fetchFn = globalThis.fetch, basePath = '/api' } = {}) { if (typeof fetchFn !== 'function') throw new TypeError('fetchFn phải là function.'); return Object.freeze({
  async getOverview(range) { const payload = await getJson(fetchFn, `${basePath}/reports?${rangeQuery(range)}`); if (!payload?.spend || !payload?.events || !payload?.fees) throw new InteractionsApiError({ status: 502, code: 'REPORT_OVERVIEW_INVALID_RESPONSE', message: 'Dữ liệu báo cáo trả về không hợp lệ.' }); return payload; },
  async getByStaff(range) { const payload = await getJson(fetchFn, `${basePath}/reports/by-staff?${rangeQuery(range)}`); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'REPORT_STAFF_INVALID_RESPONSE', message: 'Báo cáo nhân sự trả về không hợp lệ.' }); return payload.rows; },
  async getByUnit(range) { const payload = await getJson(fetchFn, `${basePath}/reports/by-unit?${rangeQuery(range)}`); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'REPORT_UNIT_INVALID_RESPONSE', message: 'Báo cáo đơn vị trả về không hợp lệ.' }); return payload.rows; },
  async getAwards(range) { const payload = await getJson(fetchFn, `${basePath}/reports/awards?${rangeQuery(range)}`); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'REPORT_AWARDS_INVALID_RESPONSE', message: 'Báo cáo giải thưởng trả về không hợp lệ.' }); return payload.rows; },
  async getCareAlerts() { const payload = await getJson(fetchFn, `${basePath}/reports/care-alerts`); if (!Array.isArray(payload?.rows) || !payload?.counts) throw new InteractionsApiError({ status: 502, code: 'REPORT_ALERTS_INVALID_RESPONSE', message: 'Cảnh báo chăm sóc trả về không hợp lệ.' }); return payload; }
}); }
