<script setup>
import { computed, reactive, ref } from 'vue';
import MButton from '../../../components/mds/MButton.vue';
import MDialog from '../../../components/mds/MDialog.vue';
import MInput from '../../../components/mds/MInput.vue';
import MMobileTopBar from '../../../components/mds/MMobileTopBar.vue';
import MSelect from '../../../components/mds/MSelect.vue';
import MTextarea from '../../../components/mds/MTextarea.vue';
import { toBookingEditDraft, toBookingUpdatePayload, validateBookingCreateDraft } from '../domain/booking-write.mjs';

const props = defineProps({ record: { type: Object, required: true }, saving: { type: Boolean, default: false }, serverError: { type: String, default: '' }, safeAreaStyle: { type: Object, default: () => ({}) } });
const emit = defineEmits(['cancel', 'save']);
const draft = reactive(toBookingEditDraft(props.record)); const errors = reactive({}); const confirmDiscard = ref(false); const initialDraft = JSON.stringify(draft);
const contentTypes = ['', 'Bài PR', 'Bài phỏng vấn', 'Thông cáo báo chí', 'Advertorial', 'Social post', 'Khác'].map((value) => ({ value, label: value || 'Chọn loại nội dung' }));
const statuses = ['Đã đặt', 'Đã đăng', 'Đã nghiệm thu', 'Hủy'].map((value) => ({ value, label: value })); const isDirty = computed(() => JSON.stringify(draft) !== initialDraft);
function requestCancel() { if (props.saving) return; if (isDirty.value) { confirmDiscard.value = true; return; } emit('cancel'); }
function submit() { const nextErrors = validateBookingCreateDraft(draft); Object.keys(errors).forEach((key) => delete errors[key]); Object.assign(errors, nextErrors); if (Object.keys(nextErrors).length) return; emit('save', toBookingUpdatePayload(draft)); }
</script>

<template><section class="mds-mobile-app flex h-[100dvh] min-w-0 flex-col overflow-hidden bg-[var(--mds-bg)]" :style="safeAreaStyle"><MMobileTopBar title="Chỉnh sửa booking" @back="requestCancel"><template #actions><MButton variant="link" :disabled="saving" @click="requestCancel">Hủy</MButton></template></MMobileTopBar><form class="flex min-h-0 flex-1 flex-col" novalidate @submit.prevent="submit"><div class="min-h-0 flex-1 overflow-y-auto"><p class="mds-mobile-gutter-x border-b border-[var(--mds-border-light)] py-3 text-[13px] text-[var(--mds-text-secondary)]">Máy chủ kiểm tra lại quyền chỉnh sửa và giữ nguyên chủ sở hữu, nhân sự, cơ quan.</p><div class="mds-mobile-gutter-x space-y-4 py-4"><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Tên booking <span class="text-[var(--mds-danger)]">*</span></span><MInput v-model="draft.title" placeholder="Nhập tên bài viết/booking" :error="errors.title" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Loại nội dung</span><MSelect v-model="draft.content_type" :options="contentTypes" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Trạng thái</span><MSelect v-model="draft.status" :options="statuses" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Số tiền (đ)</span><MInput v-model="draft.amount" type="number" min="0" placeholder="Nhập số tiền" :error="errors.amount" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Ngày đặt <span class="text-[var(--mds-danger)]">*</span></span><MInput v-model="draft.booked_date" type="date" :error="errors.booked_date" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Ngày đăng dự kiến</span><MInput v-model="draft.publish_date" type="date" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Link bài viết</span><MInput v-model="draft.article_link" type="url" placeholder="https://…" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Ghi chú</span><MTextarea v-model="draft.note" placeholder="Nhập ghi chú" :disabled="saving" /></label><p v-if="serverError" role="alert" class="rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{ serverError }}</p></div></div><footer class="shrink-0 border-t border-[var(--mds-border-light)] bg-[var(--mds-bg)] px-4 pb-[calc(12px+var(--mds-mobile-safe-bottom))] pt-3"><MButton variant="primary" class="w-full" :loading="saving" :disabled="saving" @click="submit">Lưu thay đổi</MButton></footer></form><MDialog v-model="confirmDiscard" title="Bỏ thay đổi booking?" type="danger" confirm-text="Bỏ thay đổi" @confirm="emit('cancel')"><p>Các thông tin vừa sửa sẽ không được giữ lại.</p></MDialog></section></template>
