<script setup>
import { ref, watch } from 'vue';
import MButton from '../../../components/mds/MButton.vue';
import MEmptyState from '../../../components/mds/MEmptyState.vue';
import MInput from '../../../components/mds/MInput.vue';
import MMobileTopBar from '../../../components/mds/MMobileTopBar.vue';
import MTag from '../../../components/mds/MTag.vue';

const props = defineProps({ rows: { type: Array, default: () => [] }, total: { type: Number, default: 0 }, page: { type: Number, default: 1 }, pageSize: { type: Number, default: 20 }, search: { type: String, default: '' }, loading: { type: Boolean, default: false }, error: { type: String, default: '' }, safeAreaStyle: { type: Object, default: () => ({}) } });
const emit = defineEmits(['search', 'page', 'open', 'back']); const query = ref(props.search);
watch(() => props.search, (value) => { query.value = value; });
function submitSearch() { emit('search', query.value.trim()); }
</script>

<template><section class="mds-mobile-app flex h-[100dvh] min-w-0 flex-col overflow-hidden bg-[var(--mds-bg)]" :style="safeAreaStyle"><MMobileTopBar title="Danh bạ nhân sự" @back="emit('back')" /><form class="mds-mobile-gutter-x flex shrink-0 gap-2 border-b border-[var(--mds-border-light)] py-3" @submit.prevent="submitSearch"><MInput v-model="query" placeholder="Tìm nhân sự…" :disabled="loading" /><MButton variant="primary" :loading="loading" @click="submitSearch">Tìm</MButton></form><p v-if="error" role="alert" class="mx-4 mt-3 rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{ error }}</p><div class="min-h-0 flex-1 overflow-y-auto"><div v-if="rows.length" class="divide-y divide-[var(--mds-border-light)]"><MButton v-for="person in rows" :key="person.id" variant="link" class="mds-mobile-gutter-x flex min-h-[var(--mds-mobile-touch-target)] w-full items-center gap-3 py-3 text-left" @click="emit('open', person.id)"><span class="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[var(--mds-brand-50)] text-[12px] font-semibold text-[var(--mds-brand-700)]">{{ person.initials }}</span><span class="min-w-0 flex-1"><strong class="block truncate text-[14px] leading-5 text-[var(--mds-text)]">{{ person.name }}</strong><span class="mt-0.5 block truncate text-[13px] leading-[18px] text-[var(--mds-text-secondary)]">{{ person.position !== '—' ? person.position : person.level }} · {{ person.orgName }}</span></span><MTag v-if="person.status !== '—'" color="neutral">{{ person.status }}</MTag></MButton></div><MEmptyState v-else-if="!loading" title="Không tìm thấy nhân sự" description="Thử đổi từ khóa tìm kiếm." /><div v-else class="p-6 text-center text-[13px] text-[var(--mds-text-secondary)]">Đang tải danh bạ…</div></div><footer class="flex shrink-0 justify-between border-t border-[var(--mds-border-light)] bg-[var(--mds-bg)] px-4 pb-[calc(12px+var(--mds-mobile-safe-bottom))] pt-3"><MButton variant="neutral" :disabled="loading || page <= 1" @click="emit('page', page - 1)">Trước</MButton><span class="self-center text-[12px] text-[var(--mds-text-secondary)]">{{ total }} nhân sự</span><MButton variant="neutral" :disabled="loading || page * pageSize >= total" @click="emit('page', page + 1)">Sau</MButton></footer></section></template>
