<script setup>
import { nextTick, reactive, ref } from 'vue';
import MButton from '../../../components/mds/MButton.vue';
import MInput from '../../../components/mds/MInput.vue';
import MSelect from '../../../components/mds/MSelect.vue';
import MTextarea from '../../../components/mds/MTextarea.vue';
import { toBookingEditDraft, toBookingUpdatePayload, validateBookingCreateDraft } from '../domain/booking-write.mjs';

const props = defineProps({ record: { type: Object, required: true }, saving: { type: Boolean, default: false }, serverError: { type: String, default: '' } });
const emit = defineEmits(['cancel', 'save']);
const draft = reactive({ ...toBookingEditDraft(props.record) }); const errors = reactive({}); const titleInput = ref(null);
const contentTypes = ['', 'Bài PR', 'Bài phỏng vấn', 'Thông cáo báo chí', 'Advertorial', 'Social post', 'Khác'].map((value) => ({ value, label: value || 'Chọn loại nội dung' }));
const statuses = ['Đã đặt', 'Đã đăng', 'Đã nghiệm thu', 'Hủy'].map((value) => ({ value, label: value }));
async function submit() { const nextErrors = validateBookingCreateDraft(draft); Object.keys(errors).forEach((key) => delete errors[key]); Object.assign(errors, nextErrors); if (Object.keys(nextErrors).length) { await nextTick(); titleInput.value?.focus(); return; } emit('save', toBookingUpdatePayload(draft)); }
</script>

<template><section class="min-h-0 bg-[var(--mds-bg-page)] p-4"><form class="mx-auto max-w-[880px] rounded-lg bg-[var(--mds-bg)] shadow-[var(--mds-shadow-card)]" novalidate @submit.prevent="submit"><header class="flex items-start justify-between gap-4 border-b border-[var(--mds-border-light)] px-5 py-4"><div><h1 class="text-[20px] font-semibold leading-7">Chỉnh sửa booking</h1><p class="mt-1 text-[13px] leading-[18px] text-[var(--mds-text-secondary)]">Chỉ cập nhật nội dung booking. Chủ sở hữu, nhân sự và cơ quan được máy chủ bảo vệ.</p></div><MButton variant="neutral" :disabled="saving" @click="emit('cancel')">Hủy</MButton></header><div class="grid gap-4 p-5 sm:grid-cols-2"><label class="block sm:col-span-2"><span class="mb-1.5 block text-[13px] font-medium">Tên booking <span class="text-[var(--mds-danger)]">*</span></span><MInput ref="titleInput" v-model="draft.title" placeholder="Nhập tên bài viết/booking" :error="errors.title" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Loại nội dung</span><MSelect v-model="draft.content_type" :options="contentTypes" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Trạng thái</span><MSelect v-model="draft.status" :options="statuses" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Số tiền (đ)</span><MInput v-model="draft.amount" type="number" min="0" placeholder="Nhập số tiền" :error="errors.amount" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Ngày đặt <span class="text-[var(--mds-danger)]">*</span></span><MInput v-model="draft.booked_date" type="date" :error="errors.booked_date" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Ngày đăng dự kiến</span><MInput v-model="draft.publish_date" type="date" :disabled="saving" /></label><label class="block"><span class="mb-1.5 block text-[13px] font-medium">Link bài viết</span><MInput v-model="draft.article_link" type="url" placeholder="https://…" :disabled="saving" /></label><label class="block sm:col-span-2"><span class="mb-1.5 block text-[13px] font-medium">Ghi chú</span><MTextarea v-model="draft.note" placeholder="Nhập ghi chú" :disabled="saving" /></label></div><p v-if="serverError" role="alert" class="mx-5 mb-4 rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{ serverError }}</p><footer class="flex justify-end gap-2 border-t border-[var(--mds-border-light)] px-5 py-3"><MButton variant="neutral" :disabled="saving" @click="emit('cancel')">Hủy</MButton><MButton variant="primary" :loading="saving" :disabled="saving" @click="submit">Lưu thay đổi</MButton></footer></form></section></template>
