<script setup>
import { computed, reactive, ref, watch } from 'vue';
import MButton from '../../../components/mds/MButton.vue';
import MDialog from '../../../components/mds/MDialog.vue';
import MInput from '../../../components/mds/MInput.vue';
import MMobileTopBar from '../../../components/mds/MMobileTopBar.vue';
import MSelect from '../../../components/mds/MSelect.vue';
import MTextarea from '../../../components/mds/MTextarea.vue';
import { toAwardParticipationDraft, toAwardParticipationPayload } from '../domain/award-participation-write.mjs';

const props = defineProps({ record: { type: Object, default: () => ({}) }, editing: Boolean, saving: Boolean, error: String, safeAreaStyle: Object }); const emit = defineEmits(['cancel', 'save']); const draft = reactive({ ...toAwardParticipationDraft(props.record) }); const localError = ref(''); const discard = ref(false);
const title = computed(() => props.editing ? 'Sửa kỳ tham gia' : 'Thêm kỳ tham gia'); const showBudget = computed(() => !props.editing || Object.hasOwn(props.record, 'budget')); const statuses = ['', 'Đang cân nhắc', 'Quyết định tham gia', 'Đã nộp', 'Đạt giải', 'Trượt', 'Không tham gia'].map((value) => ({ value, label: value || 'Chọn trạng thái' }));
watch(() => props.record, (record) => Object.assign(draft, toAwardParticipationDraft(record)), { deep: true }); function submit() { try { localError.value = ''; emit('save', toAwardParticipationPayload(draft, { existingRecord: props.editing ? props.record : null })); } catch (error) { localError.value = error.message; } }
</script>

<template><section class="mds-mobile-app flex h-[100dvh] min-w-0 flex-col overflow-hidden bg-[var(--mds-bg)]" :style="safeAreaStyle"><MMobileTopBar :title="title" @back="discard=true"><template #actions><MButton variant="link" :disabled="saving" @click="discard=true">Hủy</MButton></template></MMobileTopBar><form class="flex min-h-0 flex-1 flex-col" @submit.prevent="submit"><div class="min-h-0 flex-1 overflow-y-auto"><div class="mds-mobile-gutter-x space-y-4 py-4"><label><span class="mb-1 block text-[13px] font-medium">Năm tham gia</span><MInput v-model="draft.year" type="number" min="2000" max="2100" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Trạng thái</span><MSelect v-model="draft.status" :options="statuses" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Sản phẩm tham gia</span><MInput v-model="draft.products" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Hạng mục</span><MInput v-model="draft.categories" :disabled="saving"/></label><label v-if="showBudget"><span class="mb-1 block text-[13px] font-medium">Dự toán (đ)</span><MInput v-model="draft.budget" type="number" min="0" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Kết quả</span><MInput v-model="draft.result" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Mục tiêu</span><MTextarea v-model="draft.goal" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Mục đích</span><MTextarea v-model="draft.purpose" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Đánh giá năng lực</span><MTextarea v-model="draft.capability" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Kế hoạch triển khai</span><MTextarea v-model="draft.plan" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Ghi chú</span><MTextarea v-model="draft.note" :disabled="saving"/></label><p v-if="error || localError" role="alert" class="rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{ error || localError }}</p></div></div><footer class="shrink-0 border-t border-[var(--mds-border-light)] bg-[var(--mds-bg)] px-4 pb-[calc(12px+var(--mds-mobile-safe-bottom))] pt-3"><MButton variant="primary" class="w-full" :loading="saving" :disabled="saving" @click="submit">Lưu kỳ tham gia</MButton></footer></form><MDialog v-model="discard" title="Bỏ thay đổi?" type="danger" confirm-text="Bỏ thay đổi" @confirm="emit('cancel')"><p>Thông tin chưa lưu sẽ không được giữ lại.</p></MDialog></section></template>
