<script setup>
import { ref } from 'vue';
import MButton from '../../../components/mds/MButton.vue'; import MDialog from '../../../components/mds/MDialog.vue'; import MMobileTopBar from '../../../components/mds/MMobileTopBar.vue';
import MTag from '../../../components/mds/MTag.vue';
import EventCostsPanel from '../EventCostsPanel.vue';
import EventFilesPanel from '../EventFilesPanel.vue';
defineProps({ detail: { type: Object, required: true }, canEdit: Boolean, canDelete: Boolean, canReassignOwner:Boolean, canManageCosts: Boolean, costDeleting: Boolean, costError: String, deleteWorking: Boolean, deleteError: String, uploading: Boolean, fileError: String, safeAreaStyle: Object });
const emit = defineEmits(['back', 'edit', 'delete', 'reassign-owner', 'upload', 'add-cost', 'edit-cost', 'delete-cost']); const deleteOpen = ref(false);
</script>

<template>
  <section class="mds-mobile-app flex h-[100dvh] min-w-0 flex-col overflow-hidden bg-[var(--mds-bg)]" :style="safeAreaStyle">
    <MMobileTopBar :title="detail.title" @back="emit('back')"><template #actions><MButton v-if="canReassignOwner" variant="ghost" class="[&]:h-[var(--mds-mobile-touch-target)]" @click="emit('reassign-owner')">Gán</MButton><MButton v-if="canEdit" variant="link" @click="emit('edit')">Sửa</MButton><MTag color="neutral">{{ detail.status }}</MTag></template></MMobileTopBar>
    <main class="min-h-0 flex-1 overflow-y-auto"><section class="mds-mobile-gutter-x border-b border-[var(--mds-border-light)] py-4"><p class="text-[13px] text-[var(--mds-text-secondary)]">{{ detail.time }}</p><p class="mt-1 text-[14px]">{{ detail.location }}</p></section><section class="mds-mobile-gutter-x divide-y divide-[var(--mds-border-light)]"><div class="py-4"><h2 class="text-[16px] font-semibold">Thông tin chung</h2><dl class="mt-3 space-y-3"><div><dt class="text-[12px] text-[var(--mds-text-secondary)]">Đơn vị tổ chức</dt><dd class="mt-1 text-[14px]">{{ detail.organizer }}</dd></div><div><dt class="text-[12px] text-[var(--mds-text-secondary)]">Hình thức · định dạng</dt><dd class="mt-1 text-[14px]">{{ detail.fields.mode }} · {{ detail.fields.format }}</dd></div><div><dt class="text-[12px] text-[var(--mds-text-secondary)]">Lĩnh vực · quy mô</dt><dd class="mt-1 text-[14px]">{{ detail.fields.field }} · {{ detail.fields.scale_attendees }}</dd></div></dl></div><div class="py-4"><h2 class="text-[16px] font-semibold">Chi phí theo quyền được cấp</h2><p class="mt-1 text-[12px] text-[var(--mds-text-secondary)]">Máy chủ quyết định dữ liệu được hiển thị.</p><dl class="mt-3 divide-y divide-[var(--mds-border-light)]"><div v-for="item in detail.costTotals" :key="item.label" class="flex min-h-[48px] items-center justify-between gap-3 py-2"><dt class="text-[13px] text-[var(--mds-text-secondary)]">{{ item.label }}</dt><dd class="text-right text-[14px] font-semibold">{{ item.value }}</dd></div></dl></div><div class="py-4"><EventCostsPanel :groups="detail.costGroups" :can-edit="canManageCosts" :can-delete="canDelete" :deleting="costDeleting" :error="costError" @add="emit('add-cost', $event)" @edit="emit('edit-cost', $event)" @delete="emit('delete-cost', $event)" /></div><div class="py-4"><EventFilesPanel :files="detail.files" :can-upload="canEdit" :uploading="uploading" :error="fileError" @upload="emit('upload', $event)" /></div><div class="py-4"><h2 class="text-[16px] font-semibold">Đánh giá & ghi chú</h2><dl class="mt-3 space-y-3"><div><dt class="text-[12px] text-[var(--mds-text-secondary)]">Đánh giá</dt><dd class="mt-1 whitespace-pre-wrap text-[14px]">{{ detail.fields.evaluation }}</dd></div><div><dt class="text-[12px] text-[var(--mds-text-secondary)]">Điểm nhấn MISA</dt><dd class="mt-1 whitespace-pre-wrap text-[14px]">{{ detail.fields.misa_keynotes }}</dd></div><div><dt class="text-[12px] text-[var(--mds-text-secondary)]">Ghi chú</dt><dd class="mt-1 whitespace-pre-wrap text-[14px]">{{ detail.fields.note }}</dd></div></dl></div><div v-if="canDelete" class="py-4"><p v-if="deleteError" role="alert" class="mb-3 rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{ deleteError }}</p><MButton variant="danger" class="w-full" :disabled="deleteWorking" @click="deleteOpen = true">Xóa sự kiện</MButton></div></section></main>
    <MDialog v-model="deleteOpen" title="Xóa sự kiện?" type="danger" confirm-text="Xóa sự kiện" @confirm="emit('delete')"><p>Sự kiện và các tệp đính kèm liên quan sẽ bị xóa. Thao tác này không thể hoàn tác.</p></MDialog>
  </section>
</template>
