'use strict';
process.env.DB_CLIENT = 'sqlite';
const fs = require('fs'), os = require('os'), path = require('path');
process.env.DATA_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'pr-policy-vis-'));
const test = require('node:test'), assert = require('node:assert/strict');
const { db } = require('../db'); const { createVisibilityStore } = require('../policy-visibility-store');
const store = createVisibilityStore(db);
test.after(() => fs.rmSync(process.env.DATA_DIR, { recursive: true, force: true }));
test('D13-006: missing configuration is private and invalid field is rejected', () => { assert.equal(store.isPublic('partners', 'phone_personal'), false); assert.throws(() => store.isPublic('partners', 'bad'), /không hợp lệ/); });
test('D13-007: privileged user may only keep Confidential field private', () => { assert.throws(() => store.setPublic({ module: 'partners', field: 'phone_personal', isPublic: true, principal: { id: 2, role: 'super_admin' } }), /FORBIDDEN_TIER/); store.setPublic({ module: 'partners', field: 'phone_personal', isPublic: false, principal: { id: 2, role: 'super_admin' } }); assert.equal(store.isPublic('partners', 'phone_personal'), false); });
