'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path'); const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '..', '..'); const featureRoot = path.join(root, 'frontend', 'src', 'features', 'interactions'); const appVue = fs.readFileSync(path.join(root, 'frontend', 'src', 'App.vue'), 'utf8'); const feature = fs.readFileSync(path.join(featureRoot, 'InteractionsListFeature.vue'), 'utf8'); const desktop = fs.readFileSync(path.join(featureRoot, 'desktop', 'InteractionsListDesktop.vue'), 'utf8'); const mobile = fs.readFileSync(path.join(featureRoot, 'mobile', 'InteractionsListMobile.vue'), 'utf8'); const desktopCreate = fs.readFileSync(path.join(featureRoot, 'desktop', 'InteractionCreateDesktop.vue'), 'utf8'); const mobileCreate = fs.readFileSync(path.join(featureRoot, 'mobile', 'InteractionCreateMobile.vue'), 'utf8');
async function apiDomain() { return import(pathToFileURL(path.join(featureRoot, 'domain', 'interactions-api.mjs')).href); }
test('UI-INT-001: Interaction List chỉ render R044 projection và có hai composition MDS', async () => {
  const { interactionsListViewModel } = await import(pathToFileURL(path.join(featureRoot, 'domain', 'interactions-view.mjs')).href);
  const model = interactionsListViewModel({ rows: [{ id: 4, date: '2026-09-01', partner_name: 'Báo Ví dụ', partner_type: 'org', channel: 'Gặp trực tiếp', result: 'Tốt', staff: 'PR', summary: 'Trao đổi kế hoạch', owner_id: 2 }], total: 1, page: 1, pageSize: 20 });
  assert.equal(model.rows[0].partnerType, 'Cơ quan'); assert.equal(model.rows[0].ownerId, 2, 'owner được giữ làm context mutation, không render mặc định');
  for (const component of [desktop, mobile]) { assert.match(component, /<MInput/); assert.match(component, /<MButton/); assert.match(component, /<MEmptyState/); assert.doesNotMatch(component, /owner_id|created_by/); }
  assert.match(mobile, /<MMobileTopBar/); assert.match(mobile, /--mds-mobile-safe-bottom/); assert.match(appVue, /interactionsListRead/);
});

test('UI-INT-004: gán owner Interaction chỉ dành cho Admin, dùng shared confirmation và endpoint entity allowlist', async () => {
  assert.match(feature, /OwnerReassignDesktop/); assert.match(feature, /OwnerReassignMobile/); assert.match(feature, /modules\?\.admin\?\.includes\('edit'\)/); assert.match(feature, /api\.getAdminUsers/); assert.match(feature, /api\.reassignOwner/); assert.match(feature, /<MDialog/);
  for (const component of [desktop, mobile]) { assert.match(component, /canReassign/); assert.match(component, /emit\('reassign', row\)/); assert.match(component, /Gán/); }
  assert.match(mobile, /mds-mobile-touch-target/); assert.doesNotMatch(mobile, /MHeaderBar|MSidebar|<button\b/);
  const { createInteractionsApi } = await apiDomain(); const calls = [];
  const api = createInteractionsApi({ fetchFn: async (url, init = {}) => { calls.push({ url, init }); const payload = url.endsWith('/admin/users') ? { rows: [{ id: 3, username: 'owner', active: 1 }] } : { ok: true }; return new Response(JSON.stringify(payload), { status: 200, headers: { 'content-type': 'application/json' } }); } });
  await api.getAdminUsers(); await api.reassignOwner(12, 3);
  assert.deepEqual(calls.map(({ url, init }) => [url, init.method || 'GET', init.body || null]), [['/api/admin/users', 'GET', null], ['/api/admin/records/interaction/12/owner', 'PUT', '{"owner_id":3}']]);
  await assert.rejects(() => api.reassignOwner(0, 3), /Mã tương tác/); await assert.rejects(() => api.reassignOwner(12, 0), /Hãy chọn người phụ trách/);
});

test('UI-INT-002: Interaction Create bind đối tác từ picker, không gửi owner/created_by', async () => {
  const { toInteractionCreateDraft, toInteractionCreatePayload } = await import(pathToFileURL(path.join(featureRoot, 'domain', 'interaction-write.mjs')).href);
  const payload = toInteractionCreatePayload({ ...toInteractionCreateDraft(), summary: 'Trao đổi kế hoạch' }, { type: 'org', id: 9, name: 'Báo Ví dụ' });
  assert.equal(payload.partner_type, 'org'); assert.equal(payload.partner_id, 9); assert.equal(payload.partner_name, 'Báo Ví dụ');
  for (const forbidden of ['owner_id', 'created_by', 'caretaker_ids']) assert.equal(forbidden in payload, false);
  assert.throws(() => toInteractionCreatePayload(toInteractionCreateDraft(), null), /chọn một đối tác/);
});

test('UI-INT-003: Interaction Create có action theo quyền và hai composition MDS riêng', () => {
  assert.match(desktop, /v-if="canCreate"/); assert.match(mobile, /v-if="canCreate"/); assert.match(feature, /:can-create="canCreate"/); assert.match(feature, /@create="beginCreate"/); assert.match(feature, /api\.searchEntities/); assert.match(feature, /api\.create/);
  for (const component of [desktopCreate, mobileCreate]) { assert.match(component, /<MInput/); assert.match(component, /<MSelect/); assert.match(component, /<MTextarea/); assert.match(component, /toInteractionCreatePayload/); assert.doesNotMatch(component, /owner_id|created_by|caretaker_ids/); }
  assert.match(desktopCreate, /sticky bottom-0/); assert.match(mobileCreate, /<MMobileTopBar/); assert.match(mobileCreate, /<MDialog/); assert.match(mobileCreate, /--mds-mobile-safe-bottom/);
});

test('UI-VOICE-001: Voice API chỉ gửi audio qua propose và buộc idempotency khi confirm', async () => {
  const { createVoiceApi, createVoiceIdempotencyKey } = await import(pathToFileURL(path.join(root, 'frontend', 'src', 'features', 'voice', 'domain', 'voice-api.mjs')).href);
  const calls = []; const api = createVoiceApi({ fetchFn: async (url, init) => { calls.push({ url, init }); return new Response(JSON.stringify(url.endsWith('propose') ? { proposalId: 'p-1', expiresAt: '2026-09-01 12:00:00', extracted: {}, personCandidates: [], orgCandidates: [], matchConfidence: {}, suggestedScoreDelta: 999 } : { interactionId: 9 }), { status: 200, headers: { 'content-type': 'application/json' } }); } });
  const proposal = await api.propose(new Blob(['audio'], { type: 'audio/webm' }), { consent: true }); assert.equal(proposal.proposalId, 'p-1'); assert.equal('suggestedScoreDelta' in proposal, false, 'voice client không nhận điểm AI'); assert.equal(calls[0].init.headers, undefined); assert.ok(calls[0].init.body instanceof FormData); assert.equal(calls[0].init.body.get('aiConsent'), 'true');
  await assert.rejects(() => api.propose(new Blob(['audio'], { type: 'audio/webm' })), /được phép gửi bản ghi âm/);
  await api.confirm({ proposalId: 'p-1', idempotencyKey: 'key-1', edits: { summary: 'Đã sửa' } }); assert.match(calls[1].url, /interaction-voice-confirm$/); assert.match(calls[1].init.body, /key-1/); assert.equal(createVoiceIdempotencyKey(() => 'uuid-1'), 'uuid-1');
  await assert.rejects(() => api.confirm({ proposalId: 'p-1' }), /mã xác nhận an toàn/);
});

test('UI-VOICE-002: Voice review có hai composition MDS và luôn buộc user xác nhận', () => {
  const voiceRoot = path.join(root, 'frontend', 'src', 'features', 'voice'); const voiceDesktop = fs.readFileSync(path.join(voiceRoot, 'desktop', 'VoiceProposalDesktop.vue'), 'utf8'); const voiceMobile = fs.readFileSync(path.join(voiceRoot, 'mobile', 'VoiceProposalMobile.vue'), 'utf8');
  for (const component of [voiceDesktop, voiceMobile]) { assert.match(component, /<MUpload/); assert.match(component, /<MCheckbox/); assert.match(component, /<MRadioGroup/); assert.match(component, /Xác nhận ghi tương tác/); assert.doesNotMatch(component, /owner_id|created_by|score_delta|suggestedScoreDelta/); }
  assert.match(voiceMobile, /<MMobileTopBar/); assert.match(voiceMobile, /<MDialog/); assert.match(voiceMobile, /--mds-mobile-safe-bottom/); assert.match(feature, /VoiceProposalDesktop/); assert.match(feature, /VoiceProposalMobile/); assert.match(feature, /createVoiceIdempotencyKey/);
});

test('UI-VOICE-003: nhiều candidate phải chọn đúng một và Native dùng touch-token thật', () => {
  const voiceRoot = path.join(root, 'frontend', 'src', 'features', 'voice');
  const voiceDesktop = fs.readFileSync(path.join(voiceRoot, 'desktop', 'VoiceProposalDesktop.vue'), 'utf8');
  const voiceMobile = fs.readFileSync(path.join(voiceRoot, 'mobile', 'VoiceProposalMobile.vue'), 'utf8');
  const tokens = fs.readFileSync(path.join(root, 'frontend', 'src', 'assets', 'tokens', 'tokens.css'), 'utf8');
  for (const component of [voiceDesktop, voiceMobile]) {
    assert.match(component, /candidateCount/);
    assert.match(component, /selected !== 1/);
    assert.match(component, /selectPerson[\s\S]*selected_org_id = ''/);
    assert.match(component, /selectOrg[\s\S]*selected_person_id = ''/);
  }
  assert.match(voiceMobile, /mds-mobile-touch-target/);
  assert.match(tokens, /--mds-mobile-touch-target:\s*48px/);
  assert.match(tokens, /--mds-mobile-topbar-height:\s*56px/);
  assert.match(tokens, /\.mds-mobile-app\s*\{[\s\S]*--mds-btn-height:\s*var\(--mds-mobile-touch-target\)/);
});

test('UI-VOICE-004: entry toàn cục Native chỉ hiện sau permission và mở review Voice bằng deep-link có kiểm soát', () => {
  const trigger = fs.readFileSync(path.join(root, 'frontend', 'src', 'features', 'voice', 'mobile', 'GlobalVoiceTrigger.vue'), 'utf8');
  const legacyRouter = fs.readFileSync(path.join(root, 'public', 'app.js'), 'utf8');
  assert.match(trigger, /fetch\('\/api\/me'/);
  assert.match(trigger, /interactions\?\.includes\('create'\)/);
  assert.match(trigger, /HostEvent\.VIEWPORT/);
  assert.match(trigger, /mds-mobile-touch-target/);
  assert.match(appVue, /\^interactions\(\?:\\\?voice=1\)\?\$/);
  assert.match(appVue, /initialMode/);
  assert.match(appVue, /GlobalVoiceTrigger/);
  assert.match(appVue, /url\.hash = 'interactions\?voice=1'/);
  assert.match(feature, /initialVoicePending/);
  assert.match(feature, /VOICE_FORBIDDEN/);
  assert.match(legacyRouter, /key\.split\(\/\[\/\?\]\//);
});

test('UI-EVENT-001: Event core chỉ gửi Public allowlist, không nhận tiền/file/owner', async () => {
  const eventRoot = path.join(root, 'frontend', 'src', 'features', 'events', 'domain'); const { EVENT_PUBLIC_FIELDS, toEventDraft, toEventPayload } = await import(pathToFileURL(path.join(eventRoot, 'event-write.mjs')).href); assert.equal(toEventDraft(null).name, ''); const payload = toEventPayload({ ...toEventDraft(), name: 'Hội nghị truyền thông', owner_id: 99, total_cost: 9000000, attachments: ['x'] });
  assert.equal(payload.name, 'Hội nghị truyền thông'); for (const forbidden of ['owner_id', 'total_cost', 'attachments', 'caretaker_ids']) assert.equal(forbidden in payload, false); assert.ok(EVENT_PUBLIC_FIELDS.includes('start_time')); assert.throws(() => toEventPayload({}), /Tên sự kiện/);
});

test('UI-EVENT-001B: Event API tạo query list hợp lệ và chỉ nhận projection rows', async () => {
  const { createEventsApi } = await import(pathToFileURL(path.join(root, 'frontend', 'src', 'features', 'events', 'domain', 'events-api.mjs')).href); let url = ''; const api = createEventsApi({ fetchFn: async (value) => { url = value; return new Response(JSON.stringify({ rows: [], total: 0, page: 1, pageSize: 20 }), { status: 200, headers: { 'content-type': 'application/json' } }); } }); const payload = await api.getList({ page: 0, pageSize: 999, search: 'Hội nghị' }); assert.equal(payload.total, 0); assert.match(url, /page=1/); assert.match(url, /pageSize=100/); assert.match(url, /H%E1%BB%99i/);
});

test('UI-EVENT-002: Event List có hai composition MDS, Native không dùng desktop shell', () => {
  const eventRoot = path.join(root, 'frontend', 'src', 'features', 'events'); const desktopEvent = fs.readFileSync(path.join(eventRoot, 'desktop', 'EventsListDesktop.vue'), 'utf8'); const mobileEvent = fs.readFileSync(path.join(eventRoot, 'mobile', 'EventsListMobile.vue'), 'utf8'); const featureEvent = fs.readFileSync(path.join(eventRoot, 'EventsListFeature.vue'), 'utf8');
  for (const component of [desktopEvent, mobileEvent]) { assert.match(component, /<MInput/); assert.match(component, /<MButton/); assert.match(component, /<MEmptyState/); assert.doesNotMatch(component, /total_cost|owner_id|attachments/); }
  assert.match(mobileEvent, /<MMobileTopBar/); assert.match(mobileEvent, /--mds-mobile-safe-bottom/); assert.match(featureEvent, /Native host chưa sẵn sàng/); assert.match(appVue, /eventsListRead/); assert.match(appVue, /EventsListFeature/);
});

test('UI-EVENT-003: Event Create dùng MDS, có gate quyền và không đưa cost/file vào form', () => {
  const eventRoot = path.join(root, 'frontend', 'src', 'features', 'events'); const desktopCreate = fs.readFileSync(path.join(eventRoot, 'desktop', 'EventCreateDesktop.vue'), 'utf8'); const mobileCreate = fs.readFileSync(path.join(eventRoot, 'mobile', 'EventCreateMobile.vue'), 'utf8'); const featureEvent = fs.readFileSync(path.join(eventRoot, 'EventsListFeature.vue'), 'utf8');
  for (const component of [desktopCreate, mobileCreate]) { assert.match(component, /toEventPayload/); assert.match(component, /<MInput/); assert.match(component, /<MSelect/); assert.match(component, /<MTextarea/); assert.doesNotMatch(component, /total_cost|owner_id|attachments/); } assert.match(featureEvent, /events.*includes\('create'\)/); assert.match(desktopCreate, /sticky bottom-0/); assert.match(mobileCreate, /<MMobileTopBar/); assert.match(mobileCreate, /<MDialog/);
});

test('UI-EVENT-004: Event Detail dùng projection public, có route Desktop/Native riêng và không suy ra chi phí', async () => {
  const eventRoot = path.join(root, 'frontend', 'src', 'features', 'events'); const domainRoot = path.join(eventRoot, 'domain'); const desktopDetail = fs.readFileSync(path.join(eventRoot, 'desktop', 'EventDetailDesktop.vue'), 'utf8'); const mobileDetail = fs.readFileSync(path.join(eventRoot, 'mobile', 'EventDetailMobile.vue'), 'utf8'); const featureEvent = fs.readFileSync(path.join(eventRoot, 'EventsListFeature.vue'), 'utf8');
  const { eventDetailViewModel } = await import(pathToFileURL(path.join(domainRoot, 'event-detail.mjs')).href);
  const model = eventDetailViewModel({ record: { id: 4, name: 'Hội nghị PR', organizer: 'MISA', location: 'Hà Nội', owner_id: 99, status: 'Đang chuẩn bị' }, totals: { sponsor: '●●● (đã ẩn)', organization: 2500000, media: 0, grand: '●●● (đã ẩn)' }, attachments: [{ id: 2, kind: 'Agenda', original_name: 'agenda.pdf', mime: 'application/pdf' }] });
  assert.equal(model.title, 'Hội nghị PR'); assert.equal(model.totalCost, '●●● (đã ẩn)'); assert.equal(model.costTotals[0].value, '●●● (đã ẩn)'); assert.equal(model.costTotals[1].value, 2500000); assert.equal('ownerId' in model, false); assert.equal('attachments' in model, false); assert.deepEqual(model.files, [{ id: 2, kind: 'Agenda', originalName: 'agenda.pdf', mime: 'application/pdf' }]);
  for (const component of [desktopDetail, mobileDetail]) { assert.doesNotMatch(component, /owner_id|totalCost|event_cost/); }
  assert.match(desktopDetail, /shadow-\[var\(--mds-shadow-card\)\]/); assert.match(mobileDetail, /class="mds-mobile-app/); assert.match(mobileDetail, /<MMobileTopBar/); assert.doesNotMatch(mobileDetail, /MHeaderBar|MSidebar/);
  for (const component of [desktopDetail, mobileDetail]) { assert.match(component, /costTotals/); assert.match(component, /PolicyEngine|Máy chủ quyết định/); assert.doesNotMatch(component, /reduce\(|\.sum\(/); }
  assert.match(featureEvent, /eventDetailViewModel/); assert.match(featureEvent, /location\.hash=`events\/\$\{Number\(id\)\}`/); assert.match(appVue, /\^events\(\?:\\\/\(\\d\+\)\)\?\$/);
});

test('UI-EVENT-007: Event file chỉ dùng metadata đã projection, upload/open qua API PolicyEngine và không có xóa giả', async () => {
  const eventRoot = path.join(root, 'frontend', 'src', 'features', 'events'); const domainRoot = path.join(eventRoot, 'domain'); const panel = fs.readFileSync(path.join(eventRoot, 'EventFilesPanel.vue'), 'utf8'); const desktopDetail = fs.readFileSync(path.join(eventRoot, 'desktop', 'EventDetailDesktop.vue'), 'utf8'); const mobileDetail = fs.readFileSync(path.join(eventRoot, 'mobile', 'EventDetailMobile.vue'), 'utf8'); const featureEvent = fs.readFileSync(path.join(eventRoot, 'EventsListFeature.vue'), 'utf8'); const { createEventsApi } = await import(pathToFileURL(path.join(domainRoot, 'events-api.mjs')).href); const { eventFileUrl } = await import(pathToFileURL(path.join(domainRoot, 'event-detail.mjs')).href);
  let call; const api = createEventsApi({ fetchFn: async (url, init) => { call = { url, init }; return new Response(JSON.stringify({ ok: true }), { status: 200, headers: { 'content-type': 'application/json' } }); } }); await api.uploadFiles(12, [new Blob(['agenda'], { type: 'application/pdf' })], { kind: 'Agenda' });
  assert.match(call.url, /^\/api\/events\/12\/files\?kind=Agenda$/); assert.equal(call.init.method, 'POST'); assert.equal(call.init.credentials, 'same-origin'); assert.ok(call.init.body instanceof FormData); assert.equal(eventFileUrl(2), '/api/files/2'); assert.equal(eventFileUrl(0), null); await assert.rejects(() => api.uploadFiles(12, []), /ít nhất một tệp/);
  for (const component of [desktopDetail, mobileDetail]) assert.match(component, /EventFilesPanel/); assert.match(panel, /<MUpload/); assert.match(panel, /<MSelect/); assert.match(panel, /eventFileUrl/); assert.match(panel, /máy chủ kiểm tra lại quyền/); assert.doesNotMatch(panel, /deleteAttachment|method:\s*['\"]DELETE/); assert.match(featureEvent, /api\.uploadFiles\(props\.eventId,files,\{kind\}\)/); assert.match(featureEvent, /@upload="uploadFiles"/);
});

test('UI-EVENT-008: Event cost giữ nguyên projection PolicyEngine, có form Desktop/Native riêng và gọi đúng API protected', async () => {
  const eventRoot = path.join(root, 'frontend', 'src', 'features', 'events'); const domainRoot = path.join(eventRoot, 'domain'); const featureEvent = fs.readFileSync(path.join(eventRoot, 'EventsListFeature.vue'), 'utf8'); const panel = fs.readFileSync(path.join(eventRoot, 'EventCostsPanel.vue'), 'utf8'); const desktopForm = fs.readFileSync(path.join(eventRoot, 'desktop', 'EventCostFormDesktop.vue'), 'utf8'); const mobileForm = fs.readFileSync(path.join(eventRoot, 'mobile', 'EventCostFormMobile.vue'), 'utf8'); const { eventDetailViewModel } = await import(pathToFileURL(path.join(domainRoot, 'event-detail.mjs')).href); const { toEventCostDraft, toEventCostPayload } = await import(pathToFileURL(path.join(domainRoot, 'event-cost-write.mjs')).href); const { createEventsApi } = await import(pathToFileURL(path.join(domainRoot, 'events-api.mjs')).href);
  const model = eventDetailViewModel({ costs: { media: [{ id: 9, title: 'Bài đăng', amount: '●●● (đã ẩn)', press_org: 'Báo Ví dụ', owner_id: 99 }] }, totals: { sponsor: 0, organization: 0, media: '●●● (đã ẩn)', grand: '●●● (đã ẩn)' } }); assert.equal(model.costGroups[2].items[0].amount, '●●● (đã ẩn)'); assert.equal(model.costGroups[2].items[0].amountMasked, true); assert.equal('ownerId' in model.costGroups[2].items[0], false);
  const payload = toEventCostPayload({ ...toEventCostDraft({}, 'organization'), title: 'Thuê địa điểm', amount: '2500000', supplier_id: '7', owner_id: 99 }); assert.equal(payload.amount, 2500000); assert.equal(payload.supplier_id, 7); assert.equal('owner_id' in payload, false); assert.throws(() => toEventCostPayload({ ...toEventCostDraft({}, 'media'), title: 'Bài đăng', amount: '-1' }), /không âm/);
  const calls = []; const api = createEventsApi({ fetchFn: async (url, init = {}) => { calls.push({ url, init }); return new Response(JSON.stringify(init.method === 'POST' ? { id: 22 } : { ok: true }), { status: 200, headers: { 'content-type': 'application/json' } }); } }); await api.saveCost(12, payload); await api.saveCost(12, payload, 22); await api.deleteCost(12, 22); assert.deepEqual(calls.map((call) => [call.url, call.init.method]), [['/api/events/12/costs', 'POST'], ['/api/events/12/costs/22', 'PUT'], ['/api/events/12/costs/22', 'DELETE']]);
  assert.match(panel, /<MDialog/); assert.match(panel, /PolicyEngine/); assert.doesNotMatch(panel, /reduce\(|\.sum\(/); assert.match(featureEvent, /api\.saveCost\(props\.eventId,input,state\.costRecord\?\.id\)/); assert.match(featureEvent, /api\.deleteCost\(props\.eventId,item\.id\)/); for (const component of [desktopForm, mobileForm]) { assert.match(component, /toEventCostPayload/); assert.match(component, /<MInput/); assert.match(component, /<MTextarea/); assert.doesNotMatch(component, /owner_id|caretaker_ids/); } assert.match(desktopForm, /sticky bottom-0/); assert.match(mobileForm, /<MMobileTopBar/); assert.match(mobileForm, /--mds-mobile-safe-bottom/);
});

test('UI-AWARD-001: Award read/detail chỉ dùng projection R062/R063, không suy ra owner hay chi phí', async () => {
  const awardRoot = path.join(root, 'frontend', 'src', 'features', 'awards'); const domainRoot = path.join(awardRoot, 'domain'); const featureAward = fs.readFileSync(path.join(awardRoot, 'AwardsListFeature.vue'), 'utf8'); const listDesktop = fs.readFileSync(path.join(awardRoot, 'desktop', 'AwardsListDesktop.vue'), 'utf8'); const listMobile = fs.readFileSync(path.join(awardRoot, 'mobile', 'AwardsListMobile.vue'), 'utf8'); const detailDesktop = fs.readFileSync(path.join(awardRoot, 'desktop', 'AwardDetailDesktop.vue'), 'utf8'); const detailMobile = fs.readFileSync(path.join(awardRoot, 'mobile', 'AwardDetailMobile.vue'), 'utf8'); const { awardDetailViewModel, awardFileUrl, awardsListViewModel } = await import(pathToFileURL(path.join(domainRoot, 'award-view.mjs')).href); const { createAwardsApi } = await import(pathToFileURL(path.join(domainRoot, 'awards-api.mjs')).href);
  const list = awardsListViewModel({ rows: [{ id: 4, name: 'Giải PR', organizer: 'MISA', submission_deadline: '2026-12-20', status: 'Đang mở', scope: 'Toàn quốc', owner_id: 99, cost: 7000000 }], total: 1, page: 1, pageSize: 20 }); assert.equal(list.rows[0].name, 'Giải PR'); assert.equal('ownerId' in list.rows[0], false); assert.equal('cost' in list.rows[0], false);
  const detail = awardDetailViewModel({ record: { id: 4, name: 'Giải PR', organizer: 'MISA', cost: '●●● (đã ẩn)', owner_id: 99, status: 'Đang mở' }, attachments: [{ id: 2, original_name: 'the-le.pdf', kind: 'award_doc', mime: 'application/pdf' }], participations: [{ id: 8, year: 2026, status: 'Dự kiến', products: 'AMIS', budget: 5000000, owner_id: 3 }] }); assert.equal(detail.entryCost, '●●● (đã ẩn)'); assert.equal(detail.files[0].name, 'the-le.pdf'); assert.equal('budget' in detail.participations[0], false); assert.equal(awardFileUrl(2), '/api/files/2'); assert.equal(awardFileUrl(0), null);
  let url = ''; const api = createAwardsApi({ fetchFn: async (value) => { url = value; return new Response(JSON.stringify({ rows: [], total: 0, page: 1, pageSize: 20 }), { status: 200, headers: { 'content-type': 'application/json' } }); } }); await api.getList({ page: 0, pageSize: 999, search: 'Giải PR' }); assert.match(url, /\/api\/awards\?page=1/); assert.match(url, /pageSize=100/);
  for (const component of [listDesktop, listMobile]) { assert.match(component, /<MInput/); assert.match(component, /<MEmptyState/); assert.doesNotMatch(component, /owner_id|total_cost|entryCost/); } for (const component of [detailDesktop, detailMobile]) { assert.match(component, /AwardFiles/); assert.doesNotMatch(component, /owner_id|caretaker_ids|reduce\(|\.sum\(/); } assert.match(listMobile, /<MMobileTopBar/); assert.match(detailMobile, /class="mds-mobile-app/); assert.doesNotMatch(detailMobile, /MHeaderBar|MSidebar/); assert.match(featureAward, /Native host chưa sẵn sàng/); assert.match(appVue, /awardsListRead/); assert.match(appVue, /\^awards\(\?:\\\/\(\\d\+\)\)\?\$/);
});

test('UI-EVENT-005: Event Edit chỉ là affordance theo quyền và vẫn gửi allowlist về PUT PolicyEngine', () => {
  const eventRoot = path.join(root, 'frontend', 'src', 'features', 'events'); const featureEvent = fs.readFileSync(path.join(eventRoot, 'EventsListFeature.vue'), 'utf8'); const desktopDetail = fs.readFileSync(path.join(eventRoot, 'desktop', 'EventDetailDesktop.vue'), 'utf8'); const mobileDetail = fs.readFileSync(path.join(eventRoot, 'mobile', 'EventDetailMobile.vue'), 'utf8'); const desktopForm = fs.readFileSync(path.join(eventRoot, 'desktop', 'EventCreateDesktop.vue'), 'utf8'); const mobileForm = fs.readFileSync(path.join(eventRoot, 'mobile', 'EventCreateMobile.vue'), 'utf8');
  assert.match(featureEvent, /events\?\.includes\('edit'\)/); assert.match(featureEvent, /api\.save\(input, props\.eventId\)/); assert.match(featureEvent, /@edit="beginEdit"/);
  for (const component of [desktopDetail, mobileDetail]) assert.match(component, /v-if="canEdit"/);
  for (const component of [desktopForm, mobileForm]) { assert.match(component, /toEventDraft\(props\.record\)/); assert.match(component, /toEventPayload\(draft\)/); assert.doesNotMatch(component, /owner_id|caretaker_ids|total_cost|attachments/); }
  assert.match(mobileForm, /<MMobileTopBar/); assert.match(mobileForm, /<MDialog/); assert.match(desktopForm, /sticky bottom-0/);
});

test('UI-EVENT-006: Event Delete yêu cầu confirm ở cả hai surface và quay về API protected', async () => {
  const eventRoot = path.join(root, 'frontend', 'src', 'features', 'events'); const desktopDetail = fs.readFileSync(path.join(eventRoot, 'desktop', 'EventDetailDesktop.vue'), 'utf8'); const mobileDetail = fs.readFileSync(path.join(eventRoot, 'mobile', 'EventDetailMobile.vue'), 'utf8'); const featureEvent = fs.readFileSync(path.join(eventRoot, 'EventsListFeature.vue'), 'utf8'); const { createEventsApi } = await import(pathToFileURL(path.join(eventRoot, 'domain', 'events-api.mjs')).href);
  let call; const api = createEventsApi({ fetchFn: async (url, init) => { call = { url, init }; return new Response(JSON.stringify({ ok: true }), { status: 200, headers: { 'content-type': 'application/json' } }); } }); await api.delete(12);
  assert.equal(call.url, '/api/events/12'); assert.equal(call.init.method, 'DELETE'); await assert.rejects(() => api.delete(0), /Mã sự kiện/);
  for (const component of [desktopDetail, mobileDetail]) { assert.match(component, /<MDialog/); assert.match(component, /Xóa sự kiện\?/); assert.match(component, /v-if="canDelete"/); }
  assert.match(featureEvent, /events\?\.includes\('delete'\)/); assert.match(featureEvent, /api\.delete\(props\.eventId\)/); assert.match(featureEvent, /@delete="deleteEvent"/);
});

test('UI-AWARD-002: Award core create/edit dùng allowlist, API protected và hai composition MDS riêng', async () => {
  const awardRoot = path.join(root, 'frontend', 'src', 'features', 'awards'); const domainRoot = path.join(awardRoot, 'domain'); const featureAward = fs.readFileSync(path.join(awardRoot, 'AwardsListFeature.vue'), 'utf8'); const listDesktop = fs.readFileSync(path.join(awardRoot, 'desktop', 'AwardsListDesktop.vue'), 'utf8'); const listMobile = fs.readFileSync(path.join(awardRoot, 'mobile', 'AwardsListMobile.vue'), 'utf8'); const detailDesktop = fs.readFileSync(path.join(awardRoot, 'desktop', 'AwardDetailDesktop.vue'), 'utf8'); const detailMobile = fs.readFileSync(path.join(awardRoot, 'mobile', 'AwardDetailMobile.vue'), 'utf8'); const desktopForm = fs.readFileSync(path.join(awardRoot, 'desktop', 'AwardFormDesktop.vue'), 'utf8'); const mobileForm = fs.readFileSync(path.join(awardRoot, 'mobile', 'AwardFormMobile.vue'), 'utf8');
  const { AWARD_PUBLIC_FIELDS, toAwardDraft, toAwardPayload } = await import(pathToFileURL(path.join(domainRoot, 'award-write.mjs')).href); const { createAwardsApi } = await import(pathToFileURL(path.join(domainRoot, 'awards-api.mjs')).href);
  const payload = toAwardPayload({ ...toAwardDraft(), name: 'Giải PR 2026', cost: '2500000', owner_id: 99, caretaker_ids: [8], attachments: ['private.pdf'] }); assert.equal(payload.name, 'Giải PR 2026'); assert.equal(payload.cost, 2500000); for (const forbidden of ['owner_id', 'caretaker_ids', 'attachments', 'org_id']) assert.equal(forbidden in payload, false); assert.deepEqual(Object.keys(payload), AWARD_PUBLIC_FIELDS); const redactedUpdate = toAwardPayload({ ...toAwardDraft({ name: 'Giải PR 2026' }), name: 'Giải PR 2026' }, { existingRecord: { id: 41, name: 'Giải PR 2026', organizer: 'MISA' } }); assert.deepEqual(Object.keys(redactedUpdate), ['name', 'organizer']); assert.equal('cost' in redactedUpdate, false); assert.throws(() => toAwardPayload({ ...toAwardDraft(), name: ' ' }), /Tên giải thưởng/); assert.throws(() => toAwardPayload({ ...toAwardDraft(), name: 'Hợp lệ', cost: '-1' }), /không âm/);
  const calls = []; const api = createAwardsApi({ fetchFn: async (url, init = {}) => { calls.push({ url, init }); return new Response(JSON.stringify(init.method === 'POST' ? { id: 41 } : { ok: true }), { status: 200, headers: { 'content-type': 'application/json' } }); } }); assert.equal((await api.save(payload)).id, 41); assert.equal((await api.save(payload, 41)).id, 41); assert.deepEqual(calls.map((call) => [call.url, call.init.method]), [['/api/awards', 'POST'], ['/api/awards/41', 'PUT']]);
  assert.match(featureAward, /awards.*includes\('create'\)/); assert.match(featureAward, /awards.*includes\('edit'\)/); assert.match(featureAward, /api\.save\(input, props\.awardId\)/); assert.match(featureAward, /:can-create="canCreate"/); assert.match(featureAward, /:can-edit="canEdit"/); assert.match(featureAward, /@create="create"/); assert.match(featureAward, /@edit="edit"/); assert.match(featureAward, /@page="load\(\{ page: \$event \}\)"/);
  for (const component of [desktopForm, mobileForm]) { assert.match(component, /existingRecord:props\.editing\?props\.record:null/); assert.match(component, /v-if="showCost"/); assert.match(component, /<MInput/); assert.match(component, /<MSelect/); assert.match(component, /<MTextarea/); assert.doesNotMatch(component, /owner_id|caretaker_ids|attachments/); } assert.match(desktopForm, /sticky bottom-0/); assert.match(mobileForm, /<MMobileTopBar/); assert.match(mobileForm, /<MDialog/); assert.match(mobileForm, /--mds-mobile-safe-bottom/); for (const component of [listDesktop, listMobile]) assert.match(component, /v-if="canCreate"/); for (const component of [detailDesktop, detailMobile]) assert.match(component, /v-if="canEdit"/);
});

test('UI-FORM-001: mọi form dùng draft bất biến đều sao chép trước khi đưa vào Vue reactive', async () => {
  const { reactive, isReactive } = require('vue');
  const targets = [
    ['features/events/domain/event-write.mjs', 'toEventDraft', 'frontend/src/features/events/desktop/EventCreateDesktop.vue', 'name'],
    ['features/events/domain/event-write.mjs', 'toEventDraft', 'frontend/src/features/events/mobile/EventCreateMobile.vue', 'name'],
    ['features/events/domain/event-cost-write.mjs', 'toEventCostDraft', 'frontend/src/features/events/desktop/EventCostFormDesktop.vue', 'title'],
    ['features/events/domain/event-cost-write.mjs', 'toEventCostDraft', 'frontend/src/features/events/mobile/EventCostFormMobile.vue', 'title'],
    ['features/awards/domain/award-write.mjs', 'toAwardDraft', 'frontend/src/features/awards/desktop/AwardFormDesktop.vue', 'name'],
    ['features/awards/domain/award-write.mjs', 'toAwardDraft', 'frontend/src/features/awards/mobile/AwardFormMobile.vue', 'name'],
    ['features/interactions/domain/interaction-write.mjs', 'toInteractionCreateDraft', 'frontend/src/features/interactions/desktop/InteractionCreateDesktop.vue', 'summary'],
    ['features/interactions/domain/interaction-write.mjs', 'toInteractionCreateDraft', 'frontend/src/features/interactions/mobile/InteractionCreateMobile.vue', 'summary'],
    ['features/people/domain/people-write.mjs', 'toPeopleCreateDraft', 'frontend/src/features/people/desktop/PeopleCreateDesktop.vue', 'full_name'],
    ['features/people/domain/people-write.mjs', 'toPeopleCreateDraft', 'frontend/src/features/people/mobile/PeopleCreateMobile.vue', 'full_name'],
    ['features/people/domain/booking-write.mjs', 'toBookingCreateDraft', 'frontend/src/features/people/desktop/BookingCreateDesktop.vue', 'title'],
    ['features/people/domain/booking-write.mjs', 'toBookingCreateDraft', 'frontend/src/features/people/mobile/BookingCreateMobile.vue', 'title'],
    ['features/people/domain/booking-write.mjs', 'toBookingEditDraft', 'frontend/src/features/people/desktop/BookingEditDesktop.vue', 'title'],
    ['features/people/domain/booking-write.mjs', 'toBookingEditDraft', 'frontend/src/features/people/mobile/BookingEditMobile.vue', 'title'],
  ];
  for (const [modulePath, factoryName, componentPath, field] of targets) {
    const module = await import(pathToFileURL(path.join(root, 'frontend', 'src', modulePath)).href); const immutable = module[factoryName](); const unsafe = reactive(immutable); const safe = reactive({ ...immutable });
    assert.equal(Object.isFrozen(immutable), true, `${factoryName} must keep its immutable boundary`); assert.equal(isReactive(unsafe), false, `${factoryName} reproduces the Vue non-extensible-object trap`); assert.equal(isReactive(safe), true, `${factoryName} copy must be editable`); safe[field] = 'đã nhập'; assert.equal(safe[field], 'đã nhập'); assert.match(fs.readFileSync(path.join(root, componentPath), 'utf8'), new RegExp(`reactive\\(\\{\\s*\\.\\.\\.${factoryName}`));
  }
});

test('UI-AWARD-003: Award participation dùng payload hạn chế, không ghi đè budget bị ẩn và có hai composition MDS', async () => {
  const awardRoot = path.join(root, 'frontend', 'src', 'features', 'awards'); const domainRoot = path.join(awardRoot, 'domain'); const featureAward = fs.readFileSync(path.join(awardRoot, 'AwardsListFeature.vue'), 'utf8'); const desktopForm = fs.readFileSync(path.join(awardRoot, 'desktop', 'AwardParticipationFormDesktop.vue'), 'utf8'); const mobileForm = fs.readFileSync(path.join(awardRoot, 'mobile', 'AwardParticipationFormMobile.vue'), 'utf8'); const desktopPanel = fs.readFileSync(path.join(awardRoot, 'desktop', 'AwardParticipationsDesktop.vue'), 'utf8'); const mobilePanel = fs.readFileSync(path.join(awardRoot, 'mobile', 'AwardParticipationsMobile.vue'), 'utf8'); const { AWARD_PARTICIPATION_FIELDS, toAwardParticipationDraft, toAwardParticipationPayload } = await import(pathToFileURL(path.join(domainRoot, 'award-participation-write.mjs')).href); const { createAwardsApi } = await import(pathToFileURL(path.join(domainRoot, 'awards-api.mjs')).href);
  assert.equal(toAwardParticipationDraft(null).status, ''); const payload = toAwardParticipationPayload({ ...toAwardParticipationDraft(null), year: '2026', products: 'AMIS', budget: '3000000', owner_id: 99 }); assert.equal(payload.year, 2026); assert.equal(payload.budget, 3000000); assert.deepEqual(Object.keys(payload), AWARD_PARTICIPATION_FIELDS); assert.equal('owner_id' in payload, false); const redactedUpdate = toAwardParticipationPayload({ ...toAwardParticipationDraft(null), year: '2026' }, { existingRecord: { id: 4, year: 2026, status: 'Đã nộp' } }); assert.deepEqual(Object.keys(redactedUpdate), ['year', 'status']); assert.equal('budget' in redactedUpdate, false); assert.throws(() => toAwardParticipationPayload({ ...toAwardParticipationDraft(), year: '1999' }), /2000–2100/); assert.throws(() => toAwardParticipationPayload({ ...toAwardParticipationDraft(), budget: '-1' }), /không âm/);
  const calls = []; const api = createAwardsApi({ fetchFn: async (url, init = {}) => { calls.push({ url, init }); return new Response(JSON.stringify(init.method === 'POST' ? { id: 12 } : { ok: true }), { status: 200, headers: { 'content-type': 'application/json' } }); } }); assert.equal((await api.saveParticipation(7, payload)).id, 12); await api.saveParticipation(7, payload, 12); await api.deleteParticipation(7, 12); assert.deepEqual(calls.map((call) => [call.url, call.init.method]), [['/api/awards/7/participations', 'POST'], ['/api/awards/7/participations/12', 'PUT'], ['/api/awards/7/participations/12', 'DELETE']]);
  for (const component of [desktopForm, mobileForm]) { assert.match(component, /toAwardParticipationPayload/); assert.match(component, /existingRecord: props\.editing \? props\.record : null/); assert.match(component, /v-if="showBudget"/); assert.match(component, /<MInput/); assert.match(component, /<MSelect/); assert.match(component, /<MTextarea/); assert.doesNotMatch(component, /owner_id|caretaker_ids/); } assert.match(desktopForm, /sticky bottom-0/); assert.match(mobileForm, /<MMobileTopBar/); assert.match(mobileForm, /<MDialog/); assert.match(mobileForm, /--mds-mobile-safe-bottom/); for (const component of [desktopPanel, mobilePanel]) { assert.match(component, /<MDialog/); assert.match(component, /v-if="canCreate"/); assert.match(component, /canEdit\(item.id\)/); assert.doesNotMatch(component, /owner_id/); } assert.match(featureAward, /api\.saveParticipation/); assert.match(featureAward, /api\.deleteParticipation/); assert.match(featureAward, /Number\(item\?\.owner_id\) === Number\(state\.userId\)/);
});

test('UI-AWARD-004: Award file upload chỉ gửi FormData đến route protected và giữ hai composition MDS', async () => {
  const awardRoot = path.join(root, 'frontend', 'src', 'features', 'awards'); const featureAward = fs.readFileSync(path.join(awardRoot, 'AwardsListFeature.vue'), 'utf8'); const desktop = fs.readFileSync(path.join(awardRoot, 'desktop', 'AwardFilesDesktop.vue'), 'utf8'); const mobile = fs.readFileSync(path.join(awardRoot, 'mobile', 'AwardFilesMobile.vue'), 'utf8'); const { createAwardsApi } = await import(pathToFileURL(path.join(awardRoot, 'domain', 'awards-api.mjs')).href); let call; const api = createAwardsApi({ fetchFn: async (url, init) => { call = { url, init }; return new Response(JSON.stringify({ ok: true }), { status: 200, headers: { 'content-type': 'application/json' } }); } }); await api.uploadFiles(7, [new Blob(['pdf'], { type: 'application/pdf' })]); assert.equal(call.url, '/api/awards/7/files'); assert.equal(call.init.method, 'POST'); assert.equal(call.init.credentials, 'same-origin'); assert.ok(call.init.body instanceof FormData); await assert.rejects(() => api.uploadFiles(7, []), /ít nhất một tệp/); for (const component of [desktop, mobile]) { assert.match(component, /<MUpload/); assert.match(component, /awardFileUrl/); assert.match(component, /máy chủ kiểm tra lại quyền/i); assert.doesNotMatch(component, /owner_id|deleteAttachment|method:\s*['"]DELETE/); } assert.match(featureAward, /api\.uploadFiles\(props\.awardId, files\)/); assert.match(featureAward, /@upload="uploadFiles"/); assert.match(mobile, /Tải tài liệu giải thưởng/);
});

test('UI-AWARD-005: Smart Intake chỉ tạo bản nháp review, gửi một nguồn đến endpoint protected và không đưa chi phí bị ẩn vào form', async () => {
  const awardRoot = path.join(root, 'frontend', 'src', 'features', 'awards'); const domainRoot = path.join(awardRoot, 'domain'); const featureAward = fs.readFileSync(path.join(awardRoot, 'AwardsListFeature.vue'), 'utf8'); const desktop = fs.readFileSync(path.join(awardRoot, 'desktop', 'AwardIntakeDesktop.vue'), 'utf8'); const mobile = fs.readFileSync(path.join(awardRoot, 'mobile', 'AwardIntakeMobile.vue'), 'utf8'); const calls = []; const { createAwardsApi } = await import(pathToFileURL(path.join(domainRoot, 'awards-api.mjs')).href); const api = createAwardsApi({ fetchFn: async (url, init = {}) => { calls.push({ url, init }); return new Response(JSON.stringify({ extracted: { name: 'Giải PR', cost: 2500000 } }), { status: 200, headers: { 'content-type': 'application/json' } }); } });
  const textResult = await api.extract({ text: 'Thể lệ giải thưởng' }); assert.equal(textResult.extracted.name, 'Giải PR'); assert.equal(calls[0].url, '/api/ai/award-extract'); assert.equal(calls[0].init.method, 'POST'); assert.equal(calls[0].init.credentials, 'same-origin'); assert.equal(calls[0].init.headers['content-type'], 'application/json'); assert.deepEqual(JSON.parse(calls[0].init.body), { text: 'Thể lệ giải thưởng' });
  await api.extract({ file: new Blob(['pdf'], { type: 'application/pdf' }) }); assert.ok(calls[1].init.body instanceof FormData); assert.equal(calls[1].init.headers, undefined); await assert.rejects(() => api.extract({}), /dán nội dung/); await assert.rejects(() => api.extract({ text: 'x', url: 'https://example.com' }), /Chỉ chọn một nguồn/);
  for (const component of [desktop, mobile]) { assert.match(component, /AI chỉ tạo bản nháp/); assert.match(component, /<MTextarea/); assert.match(component, /<MInput/); assert.match(component, /<MUpload/); assert.match(component, /sourceCount > 1/); assert.doesNotMatch(component, /api\.save/); }
  assert.match(desktop, /sticky bottom-0/); assert.match(mobile, /<MMobileTopBar/); assert.match(mobile, /<MDialog/); assert.match(mobile, /--mds-mobile-safe-bottom/); assert.match(featureAward, /api\.extract\(input\)/); assert.match(featureAward, /delete draft\.cost/); assert.match(featureAward, /state\.mode = 'create'/); assert.match(featureAward, /:can-intake="canCreate"/); assert.match(featureAward, /@intake="beginIntake"/); assert.match(fs.readFileSync(path.join(awardRoot, 'desktop', 'AwardsListDesktop.vue'), 'utf8'), /Bóc tách AI/); assert.match(fs.readFileSync(path.join(awardRoot, 'mobile', 'AwardsListMobile.vue'), 'utf8'), /emit\('intake'\)/);
});

test('UI-EVENT-009: Smart Intake Event chỉ nhận văn bản hoặc Excel/CSV, giữ cảnh báo server và chuyển sang bản nháp review', async () => {
  const eventRoot = path.join(root, 'frontend', 'src', 'features', 'events'); const domainRoot = path.join(eventRoot, 'domain'); const featureEvent = fs.readFileSync(path.join(eventRoot, 'EventsListFeature.vue'), 'utf8'); const desktop = fs.readFileSync(path.join(eventRoot, 'desktop', 'EventIntakeDesktop.vue'), 'utf8'); const mobile = fs.readFileSync(path.join(eventRoot, 'mobile', 'EventIntakeMobile.vue'), 'utf8'); const calls = []; const { createEventsApi } = await import(pathToFileURL(path.join(domainRoot, 'events-api.mjs')).href); const api = createEventsApi({ fetchFn: async (url, init = {}) => { calls.push({ url, init }); return new Response(JSON.stringify({ extracted: { name: 'Hội nghị 2026', start_time: '2026-10-01' }, missing: ['location'], warnings: ['Bỏ qua sheet rỗng'] }), { status: 200, headers: { 'content-type': 'application/json' } }); } });
  const textResult = await api.extract({ text: 'Kế hoạch hội nghị' }); assert.equal(textResult.extracted.name, 'Hội nghị 2026'); assert.deepEqual(textResult.missing, ['location']); assert.deepEqual(textResult.warnings, ['Bỏ qua sheet rỗng']); assert.equal(calls[0].url, '/api/ai/event-extract'); assert.equal(calls[0].init.headers['content-type'], 'application/json'); assert.deepEqual(JSON.parse(calls[0].init.body), { text: 'Kế hoạch hội nghị' });
  await api.extract({ file: new Blob(['csv'], { type: 'text/csv' }) }); assert.ok(calls[1].init.body instanceof FormData); assert.equal(calls[1].init.headers, undefined); await assert.rejects(() => api.extract({}), /dán nội dung/); await assert.rejects(() => api.extract({ text: 'x', file: new Blob(['csv']) }), /Chỉ chọn một nguồn/);
  for (const component of [desktop, mobile]) { assert.match(component, /AI chỉ tạo bản nháp/); assert.match(component, /Excel\/CSV/); assert.match(component, /sourceCount > 1/); assert.match(component, /warnings\.length/); assert.match(component, /missing\.length/); assert.doesNotMatch(component, /api\.save/); }
  const desktopForm = fs.readFileSync(path.join(eventRoot, 'desktop', 'EventCreateDesktop.vue'), 'utf8'); const mobileForm = fs.readFileSync(path.join(eventRoot, 'mobile', 'EventCreateMobile.vue'), 'utf8'); assert.match(desktop, /sticky bottom-0/); assert.match(mobile, /<MMobileTopBar/); assert.match(mobile, /<MDialog/); assert.match(mobile, /--mds-mobile-safe-bottom/); for (const component of [desktopForm, mobileForm]) { assert.match(component, /intakeWarnings\.length/); assert.match(component, /intakeMissing\.length/); assert.match(component, /Hãy kiểm tra trước khi lưu/); } assert.match(featureEvent, /api\.extract\(input\)/); assert.match(featureEvent, /state\.intakeWarnings\s*=\s*result\.warnings/); assert.match(featureEvent, /state\.mode\s*=\s*'create'/); assert.match(featureEvent, /T00:00/); assert.match(featureEvent, /:can-intake="canCreate"/); assert.match(featureEvent, /@intake="beginIntake"/);
});

test('UI-MONITOR-001: Monitoring Dashboard chỉ render projection read-only và có composition Desktop/Native tách biệt', async () => {
  const monitorRoot = path.join(root, 'frontend', 'src', 'features', 'monitoring'); const apiRoot = path.join(monitorRoot, 'domain'); const app = fs.readFileSync(path.join(root, 'frontend', 'src', 'App.vue'), 'utf8'); const feature = fs.readFileSync(path.join(monitorRoot, 'MonitoringDashboardFeature.vue'), 'utf8'); const desktop = fs.readFileSync(path.join(monitorRoot, 'desktop', 'MonitoringDashboardDesktop.vue'), 'utf8'); const mobile = fs.readFileSync(path.join(monitorRoot, 'mobile', 'MonitoringDashboardMobile.vue'), 'utf8'); const { createMonitoringApi } = await import(pathToFileURL(path.join(apiRoot, 'monitoring-api.mjs')).href); const { monitoringDashboardViewModel } = await import(pathToFileURL(path.join(apiRoot, 'monitoring-view.mjs')).href);
  let request = ''; const api = createMonitoringApi({ fetchFn: async (url) => { request = url; return new Response(JSON.stringify({ from: '2026-08-25', to: '2026-09-01', counts: { total: '10', brand: 5, industry: 2, competitor: 1, newest24h: 3 }, sentiment: { positive: '3', neutral: '2', negative: '1' }, nsr: '0.5', crisis: false, neg24: 1, sourceCount: 4, trend: [], alerts: [] }), { status: 200, headers: { 'content-type': 'application/json' } }); } }); const payload = await api.getDashboard({ days: 7 }); assert.match(request, /\/api\/monitor\/dashboard\?from=/); const model = monitoringDashboardViewModel(payload); assert.equal(model.counts.total, 10); assert.equal(model.sentiment.positive, 3); assert.equal(model.nsr, 0.5);
  for (const component of [desktop, mobile]) { assert.match(component, /<MButton/); assert.match(component, /<MEmptyState/); assert.doesNotMatch(component, /monitor\/scan|api\.post|owner_id|created_by/); } assert.match(mobile, /<MMobileTopBar/); assert.match(mobile, /class="mds-mobile-app/); assert.match(mobile, /--mds-mobile-safe-bottom/); assert.doesNotMatch(mobile, /MHeaderBar|MSidebar/); assert.match(feature, /api\.getDashboard/); assert.match(feature, /Native host chưa sẵn sàng/); assert.match(app, /defineAsyncComponent\(\(\) => import\('\.\/features\/monitoring\/MonitoringDashboardFeature\.vue'\)\)/); assert.match(app, /monitoringDashboardRead/); assert.match(app, /uiMonitoringPilot/);
});

test('UI-MONITOR-002: Source management chỉ gửi allowlist URL qua API protected và có hai composition MDS', async () => {
  const monitorRoot = path.join(root, 'frontend', 'src', 'features', 'monitoring'); const apiRoot = path.join(monitorRoot, 'domain'); const feature = fs.readFileSync(path.join(monitorRoot, 'MonitoringDashboardFeature.vue'), 'utf8'); const desktop = fs.readFileSync(path.join(monitorRoot, 'desktop', 'MonitoringSourcesDesktop.vue'), 'utf8'); const mobile = fs.readFileSync(path.join(monitorRoot, 'mobile', 'MonitoringSourcesMobile.vue'), 'utf8'); const sourceFormMobile = fs.readFileSync(path.join(monitorRoot, 'mobile', 'MonitoringSourceFormMobile.vue'), 'utf8'); const { createMonitoringApi } = await import(pathToFileURL(path.join(apiRoot, 'monitoring-api.mjs')).href);
  let request = null; const api = createMonitoringApi({ fetchFn: async (url, options = {}) => { request = { url, options }; return new Response(JSON.stringify({ id: 17, mode: 'rss' }), { status: 200, headers: { 'content-type': 'application/json' } }); } });
  await api.saveSource({ name: ' Báo mẫu ', url: 'https://example.test/feed', type: 'news', enabled: true, mode: 'site', owner_id: 99 });
  assert.equal(request.url, '/api/monitor/sources'); assert.deepEqual(JSON.parse(request.options.body), { name: 'Báo mẫu', url: 'https://example.test/feed', type: 'news', enabled: true });
  assert.match(feature, /canManageSources.*modules\?\.admin\?\.includes\('edit'\)/); assert.match(feature, /api\.getSources/); assert.match(feature, /api\.saveSource/); assert.match(feature, /api\.deleteSource/);
  assert.match(desktop, /URL được máy chủ kiểm tra SSRF/); assert.match(mobile, /class="mds-mobile-app/); assert.match(sourceFormMobile, /--mds-mobile-touch-target/); assert.doesNotMatch(`${desktop}\n${mobile}`, /owner_id|created_by|monitor\/scan/);
});

test('UI-MONITOR-003: Mentions chỉ đọc/lọc qua API protected, không trộn scan hoặc delete và có Desktop/Native riêng', async () => {
  const monitorRoot=path.join(root,'frontend','src','features','monitoring');const domainRoot=path.join(monitorRoot,'domain');const feature=fs.readFileSync(path.join(monitorRoot,'MonitoringDashboardFeature.vue'),'utf8');const desktop=fs.readFileSync(path.join(monitorRoot,'desktop','MonitoringMentionsDesktop.vue'),'utf8');const mobile=fs.readFileSync(path.join(monitorRoot,'mobile','MonitoringMentionsMobile.vue'),'utf8');const {createMonitoringApi}=await import(pathToFileURL(path.join(domainRoot,'monitoring-api.mjs')).href);const {monitoringMentionsViewModel}=await import(pathToFileURL(path.join(domainRoot,'monitoring-view.mjs')).href);
let request='';const api=createMonitoringApi({fetchFn:async(url)=>{request=url;return new Response(JSON.stringify({rows:[{id:8,title:'MISA trên báo mẫu',link:'https://example.test/a',source_name:'Báo Mẫu',published_at:'2026-09-02',category:'brand',sentiment:'negative',status:'Mới',assignee:'Hà',ai_summary:'Cần review',next_action:'',note:'',tags:[]}],total:1,page:2,pageSize:20,queries:[]}),{status:200,headers:{'content-type':'application/json'}});}});const payload=await api.getMentions({page:2,search:'MISA',category:'brand',sentiment:'negative',status:'Mới'});assert.match(request,/\/api\/monitor\/mentions\?/);assert.match(request,/page=2/);assert.match(request,/search=MISA/);assert.match(request,/category=brand/);assert.match(request,/sentiment=negative/);assert.match(request,/status=M%E1%BB%9Bi/);const model=monitoringMentionsViewModel(payload.rows);assert.deepEqual(model[0],{id:8,title:'MISA trên báo mẫu',link:'https://example.test/a',sourceName:'Báo Mẫu',sourceType:'',publishedAt:'2026-09-02',category:'brand',sentiment:'negative',status:'Mới',assignee:'Hà',summary:'Cần review',nextAction:'',note:'',tags:[]});
  for(const component of[desktop,mobile]){assert.match(component,/<MInput/);assert.match(component,/<MSelect/);assert.match(component,/<MEmptyState/);assert.doesNotMatch(component,/bulk-delete|monitor\/scan|owner_id|created_by|method:\s*['"](?:POST|PUT|DELETE)/);}assert.match(mobile,/<MMobileTopBar/);assert.match(mobile,/class="mds-mobile-app/);assert.match(mobile,/--mds-mobile-safe-bottom/);assert.doesNotMatch(mobile,/MHeaderBar|MSidebar/);assert.match(feature,/api\.getMentions/);assert.match(feature,/MonitoringMentionsDesktop/);assert.match(feature,/MonitoringMentionsMobile/);assert.match(feature,/@mentions="openMentions"/);
});

test('UI-MONITOR-004: Review một tin chỉ gửi allowlist qua PUT protected và có form MDS hai surface', async () => {
  const monitorRoot=path.join(root,'frontend','src','features','monitoring');const domainRoot=path.join(monitorRoot,'domain');const feature=fs.readFileSync(path.join(monitorRoot,'MonitoringDashboardFeature.vue'),'utf8');const desktop=fs.readFileSync(path.join(monitorRoot,'desktop','MonitoringMentionReviewDesktop.vue'),'utf8');const mobile=fs.readFileSync(path.join(monitorRoot,'mobile','MonitoringMentionReviewMobile.vue'),'utf8');const {createMonitoringApi}=await import(pathToFileURL(path.join(domainRoot,'monitoring-api.mjs')).href);const {toMentionReviewDraft,toMentionReviewPayload,MENTION_WRITE_FIELDS}=await import(pathToFileURL(path.join(domainRoot,'monitoring-mention-write.mjs')).href);
  const draft=toMentionReviewDraft({sentiment:'negative',status:'Đang xử lý',nextAction:'Gọi tòa soạn',assignee:'Hà',tags:['khẩn','báo chí'],note:'Đã tiếp nhận'});const payload=toMentionReviewPayload({...draft,tags:' khẩn, báo chí, khẩn ',owner_id:8});assert.deepEqual(Object.keys(payload),MENTION_WRITE_FIELDS);assert.deepEqual(payload,{sentiment:'negative',status:'Đang xử lý',next_action:'Gọi tòa soạn',assignee:'Hà',tags:['khẩn','báo chí','khẩn'],note:'Đã tiếp nhận'});assert.equal('owner_id'in payload,false);
  let call=null;const api=createMonitoringApi({fetchFn:async(url,options={})=>{call={url,options};return new Response(JSON.stringify({ok:true}),{status:200,headers:{'content-type':'application/json'}});}});await api.updateMention(8,payload);assert.equal(call.url,'/api/monitor/mentions/8');assert.equal(call.options.method,'PUT');assert.deepEqual(JSON.parse(call.options.body),payload);await assert.rejects(()=>api.updateMention(0,payload),/Mã tin bài/);
  for(const component of[desktop,mobile]){assert.match(component,/<MSelect/);assert.match(component,/<MInput/);assert.match(component,/<MTextarea/);assert.match(component,/toMentionReviewPayload/);assert.doesNotMatch(component,/owner_id|created_by|bulk-delete|monitor\/scan/);}assert.match(desktop,/sticky bottom-0/);assert.match(mobile,/<MMobileTopBar/);assert.match(mobile,/class="mds-mobile-app/);assert.match(mobile,/--mds-mobile-safe-bottom/);assert.doesNotMatch(mobile,/MHeaderBar|MSidebar/);assert.match(feature,/canEditMentions.*modules\?\.monitoring\?\.includes\('edit'\)/);assert.match(feature,/api\.updateMention/);assert.match(feature,/MonitoringMentionReviewDesktop/);assert.match(feature,/MonitoringMentionReviewMobile/);
});

test('UI-MONITOR-005: Bộ từ khóa quét chỉ cấu hình query protected, không khởi chạy scan và có hai composition MDS', async () => {
  const monitorRoot=path.join(root,'frontend','src','features','monitoring');const domainRoot=path.join(monitorRoot,'domain');const feature=fs.readFileSync(path.join(monitorRoot,'MonitoringDashboardFeature.vue'),'utf8');const desktop=fs.readFileSync(path.join(monitorRoot,'desktop','MonitoringQueriesDesktop.vue'),'utf8');const mobile=fs.readFileSync(path.join(monitorRoot,'mobile','MonitoringQueriesMobile.vue'),'utf8');const desktopForm=fs.readFileSync(path.join(monitorRoot,'desktop','MonitoringQueryFormDesktop.vue'),'utf8');const mobileForm=fs.readFileSync(path.join(monitorRoot,'mobile','MonitoringQueryFormMobile.vue'),'utf8');const dashboardMobile=fs.readFileSync(path.join(monitorRoot,'mobile','MonitoringDashboardMobile.vue'),'utf8');const {createMonitoringApi}=await import(pathToFileURL(path.join(domainRoot,'monitoring-api.mjs')).href);const {MONITOR_QUERY_FIELDS,toMonitoringQueryDraft,toMonitoringQueryPayload}=await import(pathToFileURL(path.join(domainRoot,'monitoring-query-write.mjs')).href);
  const draft=toMonitoringQueryDraft({name:'Theo dõi MISA',category:'brand',queryType:'news',include:['MISA','AMIS'],exclude:['tuyển dụng'],enabled:true,grounding:true});const payload=toMonitoringQueryPayload({...draft,owner_id:9});assert.deepEqual(Object.keys(payload),MONITOR_QUERY_FIELDS);assert.deepEqual(payload,{name:'Theo dõi MISA',category:'brand',query_type:'news',include:['MISA','AMIS'],exclude:['tuyển dụng'],enabled:true,grounding:true});assert.equal('owner_id'in payload,false);
  const calls=[];const api=createMonitoringApi({fetchFn:async(url,options={})=>{calls.push({url,options});return new Response(JSON.stringify(options.method==='POST'?{id:6}:{ok:true}),{status:200,headers:{'content-type':'application/json'}});}});assert.equal((await api.saveQuery(draft)).id,6);await api.saveQuery(draft,6);await api.deleteQuery(6);assert.deepEqual(calls.map((call)=>[call.url,call.options.method]),[['/api/monitor/queries','POST'],['/api/monitor/queries/6','PUT'],['/api/monitor/queries/6','DELETE']]);assert.throws(()=>toMonitoringQueryPayload({...draft,name:'',category:'unknown'}),/Nhập tên/);for(const component of[desktop,mobile,desktopForm,mobileForm]){assert.doesNotMatch(component,/monitor\/scan|owner_id|created_by/);}for(const component of[desktopForm,mobileForm]){assert.match(component,/<MInput/);assert.match(component,/<MSelect/);assert.match(component,/<MTextarea/);}assert.match(desktopForm,/sticky bottom-0/);assert.match(mobileForm,/<MMobileTopBar/);assert.match(mobileForm,/class="mds-mobile-app/);assert.match(mobileForm,/--mds-mobile-safe-bottom/);assert.match(dashboardMobile,/emit\('queries'\)/);assert.match(feature,/canManageQueries.*modules\?\.admin\?\.includes\('edit'\)/);assert.match(feature,/api\.getQueries/);assert.match(feature,/api\.saveQuery/);assert.match(feature,/api\.deleteQuery/);
});

test('UI-REPORT-001: Reports Overview giữ tổng tiền do server tính, có kỳ chuẩn và Desktop/Native tách biệt', async () => {
  const reportsRoot = path.join(root, 'frontend', 'src', 'features', 'reports'); const domainRoot = path.join(reportsRoot, 'domain'); const app = fs.readFileSync(path.join(root, 'frontend', 'src', 'App.vue'), 'utf8'); const feature = fs.readFileSync(path.join(reportsRoot, 'ReportsOverviewFeature.vue'), 'utf8'); const desktop = fs.readFileSync(path.join(reportsRoot, 'desktop', 'ReportsOverviewDesktop.vue'), 'utf8'); const mobile = fs.readFileSync(path.join(reportsRoot, 'mobile', 'ReportsOverviewMobile.vue'), 'utf8'); const { createReportsApi, dateRange } = await import(pathToFileURL(path.join(domainRoot, 'reports-api.mjs')).href); const { reportsOverviewViewModel } = await import(pathToFileURL(path.join(domainRoot, 'reports-view.mjs')).href);
  assert.deepEqual(dateRange('month', new Date(2026, 1, 12)), { from: '2026-02-01', to: '2026-02-28', label: 'Tháng này' }); assert.deepEqual(dateRange('quarter', new Date(2026, 4, 12)), { from: '2026-04-01', to: '2026-06-30', label: 'Quý này' }); let request = ''; const api = createReportsApi({ fetchFn: async (url) => { request = url; return new Response(JSON.stringify({ grandTotal: '1200000', spend: { total: '800000', count: '2', budget: '2000000' }, events: { total: '300000' }, fees: { total: '100000' }, network: { press: '4', people: '20', newPeople: '2' }, careRisk: [] }), { status: 200, headers: { 'content-type': 'application/json' } }); } }); const model = reportsOverviewViewModel(await api.getOverview({ from: '2026-01-01', to: '2026-01-31' })); assert.match(request, /\/api\/reports\?from=2026-01-01&to=2026-01-31/); assert.equal(model.grandTotal, 1200000); assert.equal(model.spend.total, 800000);
  for (const component of [desktop, mobile]) { assert.match(component, /Intl\.NumberFormat/); assert.match(component, /<MButton/); assert.match(component, /<MEmptyState/); assert.doesNotMatch(component, /reduce\(|\.sum\(|owner_id|created_by/); } assert.match(mobile, /<MMobileTopBar/); assert.match(mobile, /class="mds-mobile-app/); assert.match(mobile, /--mds-mobile-safe-bottom/); assert.doesNotMatch(mobile, /MHeaderBar|MSidebar/); assert.match(feature, /api\.getOverview/); assert.match(feature, /Native host chưa sẵn sàng/); assert.match(app, /reportsOverviewRead/); assert.match(app, /uiReportsPilot/); assert.match(app, /defineAsyncComponent\(\(\) => import\('\.\/features\/reports\/ReportsOverviewFeature\.vue'\)\)/);
});

test('UI-REPORT-002: Các báo cáo chi tiết chỉ đọc projection API, có bảng Desktop và danh sách Native riêng', async () => {
  const reportsRoot = path.join(root, 'frontend', 'src', 'features', 'reports'); const domainRoot = path.join(reportsRoot, 'domain'); const feature = fs.readFileSync(path.join(reportsRoot, 'ReportsOverviewFeature.vue'), 'utf8'); const desktop = fs.readFileSync(path.join(reportsRoot, 'desktop', 'ReportsDetailDesktop.vue'), 'utf8'); const mobile = fs.readFileSync(path.join(reportsRoot, 'mobile', 'ReportsDetailMobile.vue'), 'utf8'); const { createReportsApi } = await import(pathToFileURL(path.join(domainRoot, 'reports-api.mjs')).href);
  const calls=[]; const api=createReportsApi({fetchFn:async(url)=>{calls.push(url);const body=url.includes('by-staff')?{rows:[{full_name:'Hà',spend:'120000'}]}:url.includes('by-unit')?{rows:[{name:'Khối PR',spend:'450000'}]}:url.includes('awards')?{rows:[{name:'Giải A',totalCost:'900000'}]}:{rows:[{name:'A',days:31}],counts:{'1m':1}};return new Response(JSON.stringify(body),{status:200,headers:{'content-type':'application/json'}});}}); const range={from:'2026-01-01',to:'2026-01-31'}; assert.equal((await api.getByStaff(range))[0].full_name,'Hà'); assert.equal((await api.getByUnit(range))[0].name,'Khối PR'); assert.equal((await api.getAwards(range))[0].name,'Giải A'); assert.equal((await api.getCareAlerts()).counts['1m'],1); assert.deepEqual(calls,['/api/reports/by-staff?from=2026-01-01&to=2026-01-31','/api/reports/by-unit?from=2026-01-01&to=2026-01-31','/api/reports/awards?from=2026-01-01&to=2026-01-31','/api/reports/care-alerts']);
  assert.match(feature,/api\.getByStaff/); assert.match(feature,/api\.getByUnit/); assert.match(feature,/api\.getAwards/); assert.match(feature,/api\.getCareAlerts/); assert.match(feature,/reportSpec/); assert.match(desktop,/<table/); assert.match(desktop,/shadow-\[var\(--mds-shadow-card\)\]/); assert.match(mobile,/<MMobileTopBar/); assert.match(mobile,/class="mds-mobile-app/); assert.match(mobile,/--mds-mobile-safe-bottom/); assert.doesNotMatch(mobile,/MHeaderBar|MSidebar/); assert.doesNotMatch(feature,/reduce\(|owner_id|created_by/);
});

test('UI-ADMIN-001: Admin Users chỉ render projection read-only, không lộ sensitive_perms và có Desktop/Native riêng', async () => {
  const adminRoot = path.join(root, 'frontend', 'src', 'features', 'admin'); const app = fs.readFileSync(path.join(root, 'frontend', 'src', 'App.vue'), 'utf8'); const desktop = fs.readFileSync(path.join(adminRoot, 'desktop', 'AdminUsersDesktop.vue'), 'utf8'); const mobile = fs.readFileSync(path.join(adminRoot, 'mobile', 'AdminUsersMobile.vue'), 'utf8'); const feature = fs.readFileSync(path.join(adminRoot, 'AdminUsersFeature.vue'), 'utf8'); const { createAdminApi } = await import(pathToFileURL(path.join(adminRoot, 'domain', 'admin-api.mjs')).href); const { adminUsersViewModel } = await import(pathToFileURL(path.join(adminRoot, 'domain', 'admin-view.mjs')).href); let request=''; const api=createAdminApi({fetchFn:async(url)=>{request=url;return new Response(JSON.stringify({roles:{viewer:'Chỉ xem'},rows:[{id:3,username:'viewer',full_name:'Người xem',role:'viewer',email:'x@misa.vn',active:1,notify_opt_in:1,sensitive_perms:['org_fee']}] }),{status:200,headers:{'content-type':'application/json'}});}});const model=adminUsersViewModel(await api.getUsers());assert.equal(request,'/api/admin/users');assert.equal(model.rows[0].roleLabel,'Chỉ xem');assert.equal('sensitivePerms' in model.rows[0],false);for(const component of [desktop,mobile]){assert.match(component,/<MEmptyState/);assert.doesNotMatch(component,/sensitive_perms|owner_id|created_by|PUT|POST|DELETE/);}assert.match(mobile,/<MMobileTopBar/);assert.match(mobile,/--mds-mobile-safe-bottom/);assert.match(feature,/api\.getUsers/);assert.match(app,/adminUsersRead/);assert.match(app,/uiAdminPilot/);assert.match(app,/defineAsyncComponent\(\(\) => import\('\.\/features\/admin\/AdminUsersFeature\.vue'\)\)/);
});

test('UI-ADMIN-002: Audit log chỉ Super Admin mới có affordance, luôn tải từ API protected và dùng Desktop/Native tách biệt', async () => {
  const adminRoot = path.join(root, 'frontend', 'src', 'features', 'admin'); const domainRoot = path.join(adminRoot, 'domain'); const feature = fs.readFileSync(path.join(adminRoot, 'AdminUsersFeature.vue'), 'utf8'); const usersDesktop = fs.readFileSync(path.join(adminRoot, 'desktop', 'AdminUsersDesktop.vue'), 'utf8'); const usersMobile = fs.readFileSync(path.join(adminRoot, 'mobile', 'AdminUsersMobile.vue'), 'utf8'); const desktop = fs.readFileSync(path.join(adminRoot, 'desktop', 'AdminAuditDesktop.vue'), 'utf8'); const mobile = fs.readFileSync(path.join(adminRoot, 'mobile', 'AdminAuditMobile.vue'), 'utf8'); const { createAdminApi } = await import(pathToFileURL(path.join(domainRoot, 'admin-api.mjs')).href); const { adminAuditViewModel } = await import(pathToFileURL(path.join(domainRoot, 'admin-view.mjs')).href);
  const calls=[]; const api=createAdminApi({fetchFn:async(url)=>{calls.push(url);return new Response(JSON.stringify(url.endsWith('/me')?{user:{id:1,role:'super_admin'}}:{rows:[{id:9,username:'root',action:'EDIT',entity:'user',entity_id:3,detail:'Cập nhật tài khoản',ts:'2026-09-01 10:00:00'}]}),{status:200,headers:{'content-type':'application/json'}});}}); const payload=await api.getAudit(); const model=adminAuditViewModel(payload); assert.equal(calls[0],'/api/admin/audit'); assert.deepEqual(model.rows[0],{id:9,actor:'root',action:'EDIT',entity:'user',entityId:3,detail:'Cập nhật tài khoản',timestamp:'2026-09-01 10:00:00'});
  for(const component of [desktop,mobile]){assert.match(component,/<MEmptyState/);assert.match(component,/row\.detail/);assert.doesNotMatch(component,/sensitive_perms|owner_id|created_by|PUT|POST|DELETE/);} assert.match(desktop,/<MButton/);assert.match(mobile,/<MMobileTopBar/);assert.match(mobile,/class="mds-mobile-app/);assert.match(mobile,/--mds-mobile-safe-bottom/);assert.doesNotMatch(mobile,/MHeaderBar|MSidebar/);assert.match(usersDesktop,/v-if="canViewAudit"/);assert.match(usersMobile,/v-if="canViewAudit"/);assert.match(feature,/currentUser\?\.role==='super_admin'/);assert.match(feature,/api\.getAudit/);assert.match(feature,/state\.error\.status===403/);
});

test('UI-ADMIN-003: User CRUD gửi allowlist, có xác nhận xoá và hai form MDS riêng; server vẫn là authority', async () => {
  const adminRoot=path.join(root,'frontend','src','features','admin');const domainRoot=path.join(adminRoot,'domain');const feature=fs.readFileSync(path.join(adminRoot,'AdminUsersFeature.vue'),'utf8');const desktop=fs.readFileSync(path.join(adminRoot,'desktop','AdminUserFormDesktop.vue'),'utf8');const mobile=fs.readFileSync(path.join(adminRoot,'mobile','AdminUserFormMobile.vue'),'utf8');const listDesktop=fs.readFileSync(path.join(adminRoot,'desktop','AdminUsersDesktop.vue'),'utf8');const listMobile=fs.readFileSync(path.join(adminRoot,'mobile','AdminUsersMobile.vue'),'utf8');const {createAdminApi}=await import(pathToFileURL(path.join(domainRoot,'admin-api.mjs')).href);const {toAdminUserDraft,toAdminUserPayload,CREATE_FIELDS,UPDATE_FIELDS}=await import(pathToFileURL(path.join(domainRoot,'admin-user-write.mjs')).href);
  const created=toAdminUserPayload({...toAdminUserDraft(),username:'pr.user',password:'strong-pass',full_name:'Nhân viên PR',role:'executor',email:'pr@misa.vn'});assert.deepEqual(Object.keys(created),CREATE_FIELDS);assert.equal('sensitive_perms'in created,false);const edited=toAdminUserPayload({...toAdminUserDraft({fullName:'Nhân viên PR',role:'executor',active:true,notify:true}),email:'',active:false,notify_opt_in:false},{editing:true});assert.deepEqual(Object.keys(edited),UPDATE_FIELDS.filter((key)=>key!=='password'));assert.equal(edited.active,0);assert.equal(edited.notify_opt_in,0);assert.throws(()=>toAdminUserPayload({...toAdminUserDraft(),username:'',password:'x',full_name:'',role:''}),/Họ tên/);
  const calls=[];const api=createAdminApi({fetchFn:async(url,init={})=>{calls.push({url,init});return new Response(JSON.stringify({ok:true,id:19}),{status:200,headers:{'content-type':'application/json'}});}});await api.saveUser(created);await api.saveUser({...edited,password:'new-pass'},19);await api.deleteUser(19);assert.deepEqual(calls.map(({url,init})=>[url,init.method||'GET']),[['/api/admin/users','POST'],['/api/admin/users/19','PUT'],['/api/admin/users/19','DELETE']]);for(const component of[desktop,mobile]){assert.match(component,/toAdminUserPayload/);assert.match(component,/<MInput/);assert.match(component,/<MSelect/);assert.doesNotMatch(component,/sensitive_perms|owner_id|created_by/);}assert.match(desktop,/sticky bottom-0/);assert.match(mobile,/<MMobileTopBar/);assert.match(mobile,/<MDialog/);assert.match(mobile,/--mds-mobile-safe-bottom/);assert.match(listDesktop,/Thêm người dùng/);assert.match(listMobile,/emit\('delete',user\)/);assert.match(feature,/currentUser\?\.role==='super_admin'/);assert.match(feature,/api\.saveUser/);assert.match(feature,/api\.deleteUser/);assert.match(feature,/<MDialog/);assert.match(feature,/Máy chủ sẽ kiểm tra lại quyền/);
});

test('UI-ADMIN-004: Field visibility chỉ cho phép siết quyền, xác nhận trước mutation và có Desktop/Native MDS riêng', async () => {
  const adminRoot=path.join(root,'frontend','src','features','admin');const domainRoot=path.join(adminRoot,'domain');const feature=fs.readFileSync(path.join(adminRoot,'AdminUsersFeature.vue'),'utf8');const apiSource=fs.readFileSync(path.join(domainRoot,'admin-api.mjs'),'utf8');const listDesktop=fs.readFileSync(path.join(adminRoot,'desktop','AdminUsersDesktop.vue'),'utf8');const listMobile=fs.readFileSync(path.join(adminRoot,'mobile','AdminUsersMobile.vue'),'utf8');const desktop=fs.readFileSync(path.join(adminRoot,'desktop','AdminFieldVisibilityDesktop.vue'),'utf8');const mobile=fs.readFileSync(path.join(adminRoot,'mobile','AdminFieldVisibilityMobile.vue'),'utf8');const {createAdminApi}=await import(pathToFileURL(path.join(domainRoot,'admin-api.mjs')).href);const {adminFieldVisibilityViewModel}=await import(pathToFileURL(path.join(domainRoot,'admin-view.mjs')).href);
  const calls=[];const api=createAdminApi({fetchFn:async(url,init={})=>{calls.push({url,init});const payload=init.method==='PUT'?{ok:true}:{module:'partners',fields:[{field:'full_name',is_public:null},{field:'bank_account_number',is_public:false}]};return new Response(JSON.stringify(payload),{status:200,headers:{'content-type':'application/json'}});}});const payload=await api.getFieldVisibility();await api.tightenFieldVisibility({field:'full_name'});assert.deepEqual(calls.map(({url,init})=>[url,init.method||'GET']),[['/api/admin/field-visibility?module=partners','GET'],['/api/admin/field-visibility','PUT']]);assert.deepEqual(JSON.parse(calls[1].init.body),{module:'partners',field:'full_name',is_public:false});await assert.rejects(()=>api.tightenFieldVisibility({field:''}),/field là bắt buộc/);const model=adminFieldVisibilityViewModel(payload);assert.deepEqual(model.rows,[{field:'full_name',isPublic:null,status:'Theo PolicyEngine'},{field:'bank_account_number',isPublic:false,status:'Đang ẩn'}]);
  for(const component of[desktop,mobile]){assert.match(component,/<MEmptyState/);assert.match(component,/<MButton/);assert.match(component,/row\.isPublic!==false/);assert.match(component,/Ẩn trường/);assert.doesNotMatch(component,/is_public\s*:\s*true|Công khai trường|owner_id|sensitive_perms/);}assert.match(desktop,/shadow-\[var\(--mds-shadow-card\)\]/);assert.match(mobile,/<MMobileTopBar/);assert.match(mobile,/class="mds-mobile-app/);assert.match(mobile,/--mds-mobile-safe-bottom/);assert.doesNotMatch(mobile,/MHeaderBar|MSidebar/);assert.match(listDesktop,/v-if="canViewVisibility"/);assert.match(listMobile,/v-if="canViewVisibility"/);assert.match(feature,/api\.getFieldVisibility/);assert.match(feature,/api\.tightenFieldVisibility/);assert.match(apiSource,/is_public:false/);assert.match(feature,/<MDialog/);assert.match(feature,/PolicyEngine vẫn kiểm tra quyền ở máy chủ/);
});

test('UI-AWARD-006: Gán lại owner chỉ mở trong Award Detail cho Admin, dùng allowlist + confirmation và hai composition MDS', async () => {
  const awardRoot=path.join(root,'frontend','src','features','awards');const domainRoot=path.join(awardRoot,'domain');const ownershipRoot=path.join(root,'frontend','src','features','ownership');const feature=fs.readFileSync(path.join(awardRoot,'AwardsListFeature.vue'),'utf8');const apiSource=fs.readFileSync(path.join(domainRoot,'awards-api.mjs'),'utf8');const detailDesktop=fs.readFileSync(path.join(awardRoot,'desktop','AwardDetailDesktop.vue'),'utf8');const detailMobile=fs.readFileSync(path.join(awardRoot,'mobile','AwardDetailMobile.vue'),'utf8');const desktop=fs.readFileSync(path.join(ownershipRoot,'desktop','OwnerReassignDesktop.vue'),'utf8');const mobile=fs.readFileSync(path.join(ownershipRoot,'mobile','OwnerReassignMobile.vue'),'utf8');const {createAwardsApi}=await import(pathToFileURL(path.join(domainRoot,'awards-api.mjs')).href);const {ownerReassignViewModel,toOwnerReassignPayload}=await import(pathToFileURL(path.join(ownershipRoot,'domain','owner-reassign.mjs')).href);
  const calls=[];const api=createAwardsApi({fetchFn:async(url,init={})=>{calls.push({url,init});const payload=url.endsWith('/admin/users')?{rows:[{id:4,username:'exec',full_name:'Chuyên viên',active:1,sensitive_perms:'finance'},{id:5,username:'old',full_name:'Đã ngưng',active:0}]}:{ok:true};return new Response(JSON.stringify(payload),{status:200,headers:{'content-type':'application/json'}});}});const users=await api.getAdminUsers();await api.reassignOwner(11,4);assert.deepEqual(calls.map(({url,init})=>[url,init.method||'GET']),[['/api/admin/users','GET'],['/api/admin/records/award/11/owner','PUT']]);assert.deepEqual(JSON.parse(calls[1].init.body),{owner_id:4});await assert.rejects(()=>api.reassignOwner(11,0),/Hãy chọn người phụ trách/);const model=ownerReassignViewModel({record:{owner_id:4},users});assert.deepEqual(model,{ownerId:4,currentOwnerLabel:'Chuyên viên · exec',owners:[{value:4,label:'Chuyên viên · exec'}]});assert.deepEqual(toOwnerReassignPayload(4),{owner_id:4});assert.throws(()=>toOwnerReassignPayload(0),/Hãy chọn người phụ trách/);
  for(const component of[desktop,mobile]){assert.match(component,/<MSelect/);assert.match(component,/<MButton/);assert.match(component,/Máy chủ/);assert.doesNotMatch(component,/sensitive_perms|created_by|fetch\(/);}assert.match(desktop,/shadow-\[var\(--mds-shadow-card\)\]/);assert.match(mobile,/<MMobileTopBar/);assert.match(mobile,/class="mds-mobile-app/);assert.match(mobile,/--mds-mobile-safe-bottom/);assert.doesNotMatch(mobile,/MHeaderBar|MSidebar/);for(const component of[detailDesktop,detailMobile]){assert.match(component,/canReassignOwner/);assert.match(component,/reassign-owner/);}assert.match(feature,/modules\?\.admin\?\.includes\('edit'\)/);assert.match(feature,/api\.getAdminUsers/);assert.match(feature,/api\.reassignOwner/);assert.match(feature,/<MDialog/);assert.match(feature,/Xác nhận gán lại người phụ trách/);assert.match(apiSource,/admin\/records\/award/);
});

test('UI-AWARD-007: Award participation chỉ Admin mới có gán owner trong card context và gọi endpoint Direct riêng', async () => {
  const awardRoot=path.join(root,'frontend','src','features','awards'); const domainRoot=path.join(awardRoot,'domain'); const feature=fs.readFileSync(path.join(awardRoot,'AwardsListFeature.vue'),'utf8'); const apiSource=fs.readFileSync(path.join(domainRoot,'awards-api.mjs'),'utf8'); const detailDesktop=fs.readFileSync(path.join(awardRoot,'desktop','AwardDetailDesktop.vue'),'utf8'); const detailMobile=fs.readFileSync(path.join(awardRoot,'mobile','AwardDetailMobile.vue'),'utf8'); const partsDesktop=fs.readFileSync(path.join(awardRoot,'desktop','AwardParticipationsDesktop.vue'),'utf8'); const partsMobile=fs.readFileSync(path.join(awardRoot,'mobile','AwardParticipationsMobile.vue'),'utf8'); const {createAwardsApi}=await import(pathToFileURL(path.join(domainRoot,'awards-api.mjs')).href);
  const calls=[]; const api=createAwardsApi({fetchFn:async(url,init={})=>{calls.push({url,init});const payload=url.endsWith('/admin/users')?{rows:[]}:{ok:true};return new Response(JSON.stringify(payload),{status:200,headers:{'content-type':'application/json'}});}}); await api.reassignParticipationOwner(11,23,4); assert.deepEqual(calls.map(({url,init})=>[url,init.method||'GET',init.body||null]),[['/api/admin/records/award_participation/23/owner','PUT','{"owner_id":4}']]); await assert.rejects(()=>api.reassignParticipationOwner(11,0,4),/Mã kỳ tham gia/); await assert.rejects(()=>api.reassignParticipationOwner(11,23,0),/Hãy chọn người phụ trách/);
  for(const component of[partsDesktop,partsMobile]){assert.match(component,/canReassign/);assert.match(component,/emit\('reassign', item\.id\)/);assert.match(component,/<MButton/);assert.doesNotMatch(component,/<button\b|owner_id|created_by/);}assert.match(partsMobile,/mds-mobile-touch-target/); for(const component of[detailDesktop,detailMobile]){assert.match(component,/canReassignParticipation/);assert.match(component,/reassign-participation/);} assert.match(feature,/beginParticipationOwnerReassign/);assert.match(feature,/ownerReassignContext/);assert.match(feature,/modules\?\.admin\?\.includes\('edit'\)/);assert.match(feature,/api\.reassignParticipationOwner/);assert.match(feature,/<MDialog/);assert.match(apiSource,/admin\/records\/award_participation/);
});

test('UI-EVENT-010: Event owner reassignment tái dùng domain/UI chung, chỉ có Admin affordance và vẫn xác nhận server-side', async () => {
  const eventRoot=path.join(root,'frontend','src','features','events');const domainRoot=path.join(eventRoot,'domain');const feature=fs.readFileSync(path.join(eventRoot,'EventsListFeature.vue'),'utf8');const apiSource=fs.readFileSync(path.join(domainRoot,'events-api.mjs'),'utf8');const desktop=fs.readFileSync(path.join(eventRoot,'desktop','EventDetailDesktop.vue'),'utf8');const mobile=fs.readFileSync(path.join(eventRoot,'mobile','EventDetailMobile.vue'),'utf8');const {createEventsApi}=await import(pathToFileURL(path.join(domainRoot,'events-api.mjs')).href);
  const calls=[];const api=createEventsApi({fetchFn:async(url,init={})=>{calls.push({url,init});const payload=url.endsWith('/admin/users')?{rows:[]}:{ok:true};return new Response(JSON.stringify(payload),{status:200,headers:{'content-type':'application/json'}});}});await api.getAdminUsers();await api.reassignOwner(23,4);assert.deepEqual(calls.map(({url,init})=>[url,init.method||'GET']),[['/api/admin/users','GET'],['/api/admin/records/event/23/owner','PUT']]);assert.deepEqual(JSON.parse(calls[1].init.body),{owner_id:4});await assert.rejects(()=>api.reassignOwner(0,4),/Mã sự kiện/);await assert.rejects(()=>api.reassignOwner(23,0),/Hãy chọn người phụ trách/);
  for(const component of[desktop,mobile]){assert.match(component,/canReassignOwner/);assert.match(component,/reassign-owner/);assert.match(component,/<MButton/);}assert.match(mobile,/<MMobileTopBar/);assert.match(mobile,/class="mds-mobile-app/);assert.match(mobile,/mds-mobile-touch-target/);assert.doesNotMatch(mobile,/MHeaderBar|MSidebar/);assert.match(feature,/OwnerReassignDesktop/);assert.match(feature,/OwnerReassignMobile/);assert.match(feature,/modules\?\.admin\?\.includes\('edit'\)/);assert.match(feature,/api\.getAdminUsers/);assert.match(feature,/api\.reassignOwner/);assert.match(feature,/Xác nhận gán lại người phụ trách/);assert.match(apiSource,/admin\/records\/event/);
});

test('UI-MONITOR-007: Monitoring operations có Desktop/Native riêng và API protected', async () => {
  const rootDir=path.join(root,'frontend','src','features','monitoring'); const feature=fs.readFileSync(path.join(rootDir,'MonitoringDashboardFeature.vue'),'utf8'); const desktop=fs.readFileSync(path.join(rootDir,'desktop','MonitoringOperationsDesktop.vue'),'utf8'); const mobile=fs.readFileSync(path.join(rootDir,'mobile','MonitoringOperationsMobile.vue'),'utf8'); const domain=fs.readFileSync(path.join(rootDir,'domain','monitoring-operations.mjs'),'utf8');
  for (const component of [desktop,mobile]) { assert.match(component, /Lịch sử quét|Lượt quét/); assert.match(component, /Đối thủ/); assert.match(component, /Chiến dịch/); assert.match(component, /<MButton/); assert.doesNotMatch(component, /<select\b|fetch\(/); }
  assert.match(mobile, /class="mds-mobile-app/); assert.match(mobile, /MMobileTopBar/); assert.doesNotMatch(mobile, /MHeaderBar|MSidebar/); assert.match(feature, /openOperations/); assert.match(feature, /api\.runScan/); assert.match(domain, /toCampaignPayload/); assert.match(domain, /toCompetitorPayload/);
});
