'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path'); const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '..', '..'); const read = (relative) => fs.readFileSync(path.join(root, relative), 'utf8');

test('UI-PARTNER-FINANCIAL-001: khoản cơ quan dùng allowlist, giữ tiền bị che và có Desktop/Native form riêng', async () => {
  const domain = path.join(root, 'frontend/src/features/partners/domain'); const { financialPayload, financialDraft, financialSchema } = await import(pathToFileURL(path.join(domain, 'partner-financial-write.mjs')).href); const { createPartnerApi } = await import(pathToFileURL(path.join(domain, 'partner-api.mjs')).href);
  assert.equal(financialSchema('association_fee').label, 'Hội phí'); assert.deepEqual(financialDraft('gift', { gift_type: 'Hoa', value: 200000 }).gift_type, 'Hoa');
  const hidden = financialPayload('sponsorship', { title: 'Giải A', type: 'award', amount: '9000000', status: 'Dự kiến', note: 'x' }, { existing: { id: 1, title: 'Giải A' } }); assert.equal('amount' in hidden, false, 'không gửi lại trường Confidential không có trong projection');
  assert.equal('value' in financialPayload('gift', { gift_type: 'Hoa', value: '' }), false, 'không ghi đè giá trị tiền bằng chuỗi rỗng');
  const visible = financialPayload('association_fee', { year: '2026', amount: '12000000', status: 'Chưa đóng' }, { existing: { id: 2, year: 2026, amount: 1 } }); assert.deepEqual(visible, { year: 2026, amount: 12000000, due_date: '', paid_date: '', status: 'Chưa đóng', staff: '', note: '' });
  assert.throws(() => financialPayload('gift', { gift_type: '', value: 'x' }), /loại quà/); assert.throws(() => financialPayload('gift', { gift_type: 'Hoa', value: 'x' }), /số hợp lệ/);
  const calls = []; const api = createPartnerApi({ fetchFn: async (url, init = {}) => { calls.push({ url, init }); return new Response(JSON.stringify(init.method === 'POST' ? { id: 9 } : { ok: true }), { status: 200, headers: { 'content-type': 'application/json' } }); } });
  await api.saveFinancial(4, 'sponsorship', visible); await api.saveFinancial(4, 'gift', { gift_type: 'Hoa' }, 8); await api.deleteFinancialForPartner(4, 'association_fee', 6);
  assert.deepEqual(calls.map(({ url, init }) => [url, init.method]), [['/api/partners/4/sponsorships', 'POST'], ['/api/gifts/8', 'PUT'], ['/api/partners/4/fees/6', 'DELETE']]); assert.equal('owner_id' in JSON.parse(calls[0].init.body), false);
  const feature = read('frontend/src/features/partners/PartnerDetailFeature.vue'); const desktop = read('frontend/src/features/partners/desktop/PartnerFinancialFormDesktop.vue'); const mobile = read('frontend/src/features/partners/mobile/PartnerFinancialFormMobile.vue'); const ownershipDesktop = read('frontend/src/features/partners/desktop/PartnerDirectOwnershipDesktop.vue'); const ownershipMobile = read('frontend/src/features/partners/mobile/PartnerDirectOwnershipMobile.vue');
  assert.match(feature, /api\.saveFinancial/); assert.match(feature, /api\.deleteFinancialForPartner/); assert.match(feature, /canEditFinancial/); assert.match(feature, /PartnerFinancialFormDesktop/); assert.match(feature, /PartnerFinancialFormMobile/); for (const component of [desktop, mobile]) { assert.match(component, /financialPayload/); assert.match(component, /<MInput/); assert.match(component, /Confidential|PolicyEngine|Quyền ghi/); assert.doesNotMatch(component, /owner_id|org_id|fetch\(/); } assert.match(mobile, /class="mds-mobile-app/); assert.match(mobile, /--mds-mobile-safe-bottom/); for (const component of [ownershipDesktop, ownershipMobile]) { assert.match(component, /emit\('create'/); assert.match(component, /emit\('edit'/); assert.match(component, /emit\('delete'/); }
});
