import { InteractionsApiError } from '../../interactions/domain/interactions-api.mjs';

function errorOf(status, payload) { return new InteractionsApiError({ status, code: payload?.code, message: payload?.message || payload?.error || 'Không thể tải sự kiện.' }); }
export function createEventsApi({ fetchFn = globalThis.fetch, basePath = '/api' } = {}) {
  if (typeof fetchFn !== 'function') throw new TypeError('fetchFn phải là function.');
  return Object.freeze({
    async getCurrentUser() { const r = await fetchFn(`${basePath}/me`, { credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); return p; },
    async getAdminUsers() { const r = await fetchFn(`${basePath}/admin/users`, { credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); if (!Array.isArray(p?.rows)) throw new InteractionsApiError({ status: 502, code: 'OWNER_USERS_INVALID_RESPONSE', message: 'Danh sách người phụ trách trả về không hợp lệ.' }); return p; },
    async getList({ page = 1, pageSize = 20, search = '' } = {}) { const q = new URLSearchParams({ page: String(Math.max(1, Number(page) || 1)), pageSize: String(Math.min(100, Math.max(1, Number(pageSize) || 20))), search: String(search || '') }); const r = await fetchFn(`${basePath}/events?${q}`, { credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); if (!Array.isArray(p?.rows)) throw new InteractionsApiError({ status: 502, code: 'EVENT_LIST_INVALID_RESPONSE', message: 'Danh sách sự kiện trả về không hợp lệ.' }); return p; },
    async get(id) { const r = await fetchFn(`${basePath}/events/${Number(id)}`, { credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); if (!p?.record) throw new InteractionsApiError({ status: 502, code: 'EVENT_INVALID_RESPONSE', message: 'Chi tiết sự kiện trả về không hợp lệ.' }); return p; },
    async save(input, id = null) { const update = Number.isInteger(Number(id)) && Number(id) > 0; const r = await fetchFn(update ? `${basePath}/events/${Number(id)}` : `${basePath}/events`, { method: update ? 'PUT' : 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); if (!update && !Number.isInteger(Number(p?.id))) throw new InteractionsApiError({ status: 502, code: 'EVENT_CREATE_INVALID_RESPONSE', message: 'Máy chủ chưa trả mã sự kiện hợp lệ.' }); return Object.freeze({ id: update ? Number(id) : Number(p.id) }); },
    async delete(id) { const eventId = Number(id); if (!Number.isInteger(eventId) || eventId < 1) throw new InteractionsApiError({ status: 400, code: 'EVENT_ID_INVALID', message: 'Mã sự kiện không hợp lệ.' }); const r = await fetchFn(`${basePath}/events/${eventId}`, { method: 'DELETE', credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); return Object.freeze({ ok: true }); },
    async reassignOwner(id, ownerId) { const eventId = Number(id); const nextOwnerId = Number(ownerId); if (!Number.isInteger(eventId) || eventId < 1) throw new InteractionsApiError({ status: 400, code: 'EVENT_ID_INVALID', message: 'Mã sự kiện không hợp lệ.' }); if (!Number.isInteger(nextOwnerId) || nextOwnerId < 1) throw new InteractionsApiError({ status: 400, code: 'OWNER_ID_INVALID', message: 'Hãy chọn người phụ trách đang hoạt động.' }); const r = await fetchFn(`${basePath}/admin/records/event/${eventId}/owner`, { method: 'PUT', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ owner_id: nextOwnerId }) }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); return p || Object.freeze({ ok: true }); },
    async listSuppliers() { const r = await fetchFn(`${basePath}/suppliers/list`, { credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); if (!Array.isArray(p?.rows)) throw new InteractionsApiError({ status: 502, code: 'SUPPLIER_LIST_INVALID_RESPONSE', message: 'Danh sách nhà cung cấp trả về không hợp lệ.' }); return p.rows.map((row) => Object.freeze({ id: Number(row.id), name: String(row.name || '') })).filter((row) => Number.isInteger(row.id) && row.id > 0); },
    async saveCost(eventId, input, costId = null) { const id = Number(eventId); if (!Number.isInteger(id) || id < 1) throw new InteractionsApiError({ status: 400, code: 'EVENT_ID_INVALID', message: 'Mã sự kiện không hợp lệ.' }); const updating = Number.isInteger(Number(costId)) && Number(costId) > 0; const r = await fetchFn(updating ? `${basePath}/events/${id}/costs/${Number(costId)}` : `${basePath}/events/${id}/costs`, { method: updating ? 'PUT' : 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); return updating ? Object.freeze({ id: Number(costId) }) : Object.freeze({ id: Number(p?.id) }); },
    async deleteCost(eventId, costId) { const id = Number(eventId); const cost = Number(costId); if (!Number.isInteger(id) || id < 1 || !Number.isInteger(cost) || cost < 1) throw new InteractionsApiError({ status: 400, code: 'EVENT_COST_ID_INVALID', message: 'Mã dòng chi phí không hợp lệ.' }); const r = await fetchFn(`${basePath}/events/${id}/costs/${cost}`, { method: 'DELETE', credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); return Object.freeze({ ok: true }); },
    async uploadFiles(id, files, { kind = 'Tài liệu' } = {}) { const eventId = Number(id); if (!Number.isInteger(eventId) || eventId < 1) throw new InteractionsApiError({ status: 400, code: 'EVENT_ID_INVALID', message: 'Mã sự kiện không hợp lệ.' }); const selected = Array.from(files || []); if (!selected.length) throw new InteractionsApiError({ status: 400, code: 'EVENT_FILES_REQUIRED', message: 'Hãy chọn ít nhất một tệp để tải lên.' }); const form = new FormData(); for (const file of selected) form.append('files', file); const r = await fetchFn(`${basePath}/events/${eventId}/files?kind=${encodeURIComponent(String(kind || 'Tài liệu'))}`, { method: 'POST', credentials: 'same-origin', body: form }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); return p; },
    async extract(input = {}) { const file = input.file || null; const text = String(input.text || '').trim(); const sourceCount = Number(Boolean(file)) + Number(Boolean(text)); if (!sourceCount) throw new InteractionsApiError({ status: 400, code: 'EVENT_EXTRACT_SOURCE_REQUIRED', message: 'Hãy dán nội dung hoặc chọn file Excel/CSV.' }); if (sourceCount > 1) throw new InteractionsApiError({ status: 400, code: 'EVENT_EXTRACT_SOURCE_AMBIGUOUS', message: 'Chỉ chọn một nguồn để AI bóc tách chính xác.' }); let r; if (file) { const form = new FormData(); form.append('file', file); r = await fetchFn(`${basePath}/ai/event-extract`, { method: 'POST', credentials: 'same-origin', body: form }); } else { r = await fetchFn(`${basePath}/ai/event-extract`, { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ text }) }); } const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); if (!p?.extracted || typeof p.extracted !== 'object') throw new InteractionsApiError({ status: 502, code: 'EVENT_EXTRACT_INVALID_RESPONSE', message: 'Kết quả AI trả về không hợp lệ.' }); return Object.freeze({ extracted: Object.freeze({ ...p.extracted }), missing: Object.freeze(Array.isArray(p.missing) ? [...p.missing] : []), warnings: Object.freeze(Array.isArray(p.warnings) ? [...p.warnings] : []) }); },
  });
}
