import { InteractionsApiError } from '../../interactions/domain/interactions-api.mjs';

function errorOf(status, payload) { return new InteractionsApiError({ status, code: payload?.code, message: payload?.message || payload?.error || 'Không thể tải sự kiện.' }); }
export function createEventsApi({ fetchFn = globalThis.fetch, basePath = '/api' } = {}) {
  if (typeof fetchFn !== 'function') throw new TypeError('fetchFn phải là function.');
  return Object.freeze({
    async getCurrentUser() { const r = await fetchFn(`${basePath}/me`, { credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); return p; },
    async getList({ page = 1, pageSize = 20, search = '' } = {}) { const q = new URLSearchParams({ page: String(Math.max(1, Number(page) || 1)), pageSize: String(Math.min(100, Math.max(1, Number(pageSize) || 20))), search: String(search || '') }); const r = await fetchFn(`${basePath}/events?${q}`, { credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); if (!Array.isArray(p?.rows)) throw new InteractionsApiError({ status: 502, code: 'EVENT_LIST_INVALID_RESPONSE', message: 'Danh sách sự kiện trả về không hợp lệ.' }); return p; },
    async get(id) { const r = await fetchFn(`${basePath}/events/${Number(id)}`, { credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); if (!p?.record) throw new InteractionsApiError({ status: 502, code: 'EVENT_INVALID_RESPONSE', message: 'Chi tiết sự kiện trả về không hợp lệ.' }); return p; },
    async save(input, id = null) { const update = Number.isInteger(Number(id)) && Number(id) > 0; const r = await fetchFn(update ? `${basePath}/events/${Number(id)}` : `${basePath}/events`, { method: update ? 'PUT' : 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); if (!update && !Number.isInteger(Number(p?.id))) throw new InteractionsApiError({ status: 502, code: 'EVENT_CREATE_INVALID_RESPONSE', message: 'Máy chủ chưa trả mã sự kiện hợp lệ.' }); return Object.freeze({ id: update ? Number(id) : Number(p.id) }); },
    async delete(id) { const eventId = Number(id); if (!Number.isInteger(eventId) || eventId < 1) throw new InteractionsApiError({ status: 400, code: 'EVENT_ID_INVALID', message: 'Mã sự kiện không hợp lệ.' }); const r = await fetchFn(`${basePath}/events/${eventId}`, { method: 'DELETE', credentials: 'same-origin' }); const p = await r.json().catch(() => null); if (!r.ok) throw errorOf(r.status, p); return Object.freeze({ ok: true }); },
  });
}
