import { InteractionsApiError } from '../../interactions/domain/interactions-api.mjs';

function errorOf(status, payload) { return new InteractionsApiError({ status, code: payload?.code, message: payload?.message || payload?.error || 'Không thể tải giải thưởng.' }); }
export function createAwardsApi({ fetchFn = globalThis.fetch, basePath = '/api' } = {}) {
  if (typeof fetchFn !== 'function') throw new TypeError('fetchFn phải là function.');
  return Object.freeze({
    async getList({ page = 1, pageSize = 20, search = '' } = {}) { const query = new URLSearchParams({ page: String(Math.max(1, Number(page) || 1)), pageSize: String(Math.min(100, Math.max(1, Number(pageSize) || 20))), search: String(search || '') }); const response = await fetchFn(`${basePath}/awards?${query}`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'AWARD_LIST_INVALID_RESPONSE', message: 'Danh sách giải thưởng trả về không hợp lệ.' }); return payload; },
    async get(id) { const awardId = Number(id); if (!Number.isInteger(awardId) || awardId < 1) throw new InteractionsApiError({ status: 400, code: 'AWARD_ID_INVALID', message: 'Mã giải thưởng không hợp lệ.' }); const response = await fetchFn(`${basePath}/awards/${awardId}`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!payload?.record) throw new InteractionsApiError({ status: 502, code: 'AWARD_INVALID_RESPONSE', message: 'Chi tiết giải thưởng trả về không hợp lệ.' }); return payload; },
    async getCurrentUser() { const response = await fetchFn(`${basePath}/me`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload; },
    async getAdminUsers() { const response = await fetchFn(`${basePath}/admin/users`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'OWNER_USERS_INVALID_RESPONSE', message: 'Danh sách người phụ trách trả về không hợp lệ.' }); return payload; },
    async reassignOwner(id, ownerId) { const awardId = Number(id); const nextOwnerId = Number(ownerId); if (!Number.isInteger(awardId) || awardId < 1) throw new InteractionsApiError({ status: 400, code: 'AWARD_ID_INVALID', message: 'Mã giải thưởng không hợp lệ.' }); if (!Number.isInteger(nextOwnerId) || nextOwnerId < 1) throw new InteractionsApiError({ status: 400, code: 'OWNER_ID_INVALID', message: 'Hãy chọn người phụ trách đang hoạt động.' }); const response = await fetchFn(`${basePath}/admin/records/award/${awardId}/owner`, { method: 'PUT', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ owner_id: nextOwnerId }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload || Object.freeze({ ok: true }); },
    async reassignParticipationOwner(awardId, participationId, ownerId) { const award = Number(awardId); const entry = Number(participationId); const target = Number(ownerId); if (!Number.isInteger(award) || award < 1 || !Number.isInteger(entry) || entry < 1) throw new InteractionsApiError({ status: 400, code: 'AWARD_PARTICIPATION_ID_INVALID', message: 'Mã kỳ tham gia không hợp lệ.' }); if (!Number.isInteger(target) || target < 1) throw new InteractionsApiError({ status: 400, code: 'OWNER_ID_INVALID', message: 'Hãy chọn người phụ trách đang hoạt động.' }); const response = await fetchFn(`${basePath}/admin/records/award_participation/${entry}/owner`, { method: 'PUT', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ owner_id: target }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload || Object.freeze({ ok: true }); },
    async save(input, id = null) { const awardId = Number(id); const updating = Number.isInteger(awardId) && awardId > 0; const response = await fetchFn(updating ? `${basePath}/awards/${awardId}` : `${basePath}/awards`, { method: updating ? 'PUT' : 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!updating && !Number.isInteger(Number(payload?.id))) throw new InteractionsApiError({ status: 502, code: 'AWARD_CREATE_INVALID_RESPONSE', message: 'Máy chủ chưa trả mã giải thưởng hợp lệ.' }); return Object.freeze({ id: updating ? awardId : Number(payload.id) }); },
    async saveParticipation(id, input, participationId = null) { const awardId = Number(id); const entryId = Number(participationId); if (!Number.isInteger(awardId) || awardId < 1) throw new InteractionsApiError({ status: 400, code: 'AWARD_ID_INVALID', message: 'Mã giải thưởng không hợp lệ.' }); const updating = Number.isInteger(entryId) && entryId > 0; const response = await fetchFn(updating ? `${basePath}/awards/${awardId}/participations/${entryId}` : `${basePath}/awards/${awardId}/participations`, { method: updating ? 'PUT' : 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(input) }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!updating && !Number.isInteger(Number(payload?.id))) throw new InteractionsApiError({ status: 502, code: 'AWARD_PARTICIPATION_CREATE_INVALID_RESPONSE', message: 'Máy chủ chưa trả mã kỳ tham gia hợp lệ.' }); return Object.freeze({ id: updating ? entryId : Number(payload.id) }); },
    async deleteParticipation(id, participationId) { const awardId = Number(id); const entryId = Number(participationId); if (!Number.isInteger(awardId) || awardId < 1 || !Number.isInteger(entryId) || entryId < 1) throw new InteractionsApiError({ status: 400, code: 'AWARD_PARTICIPATION_ID_INVALID', message: 'Mã kỳ tham gia không hợp lệ.' }); const response = await fetchFn(`${basePath}/awards/${awardId}/participations/${entryId}`, { method: 'DELETE', credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload || Object.freeze({ ok: true }); },
    async uploadFiles(id, files) { const awardId = Number(id); if (!Number.isInteger(awardId) || awardId < 1) throw new InteractionsApiError({ status: 400, code: 'AWARD_ID_INVALID', message: 'Mã giải thưởng không hợp lệ.' }); const selected = Array.from(files || []); if (!selected.length) throw new InteractionsApiError({ status: 400, code: 'AWARD_FILES_REQUIRED', message: 'Hãy chọn ít nhất một tệp để tải lên.' }); const form = new FormData(); for (const file of selected) form.append('files', file); const response = await fetchFn(`${basePath}/awards/${awardId}/files`, { method: 'POST', credentials: 'same-origin', body: form }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload || Object.freeze({ ok: true }); },
    async extract(input = {}) { const file = input.file || null; const text = String(input.text || '').trim(); const url = String(input.url || '').trim(); const sourceCount = Number(Boolean(file)) + Number(Boolean(text)) + Number(Boolean(url)); if (!sourceCount) throw new InteractionsApiError({ status: 400, code: 'AWARD_EXTRACT_SOURCE_REQUIRED', message: 'Hãy dán nội dung, nhập URL hoặc chọn một tệp.' }); if (sourceCount > 1) throw new InteractionsApiError({ status: 400, code: 'AWARD_EXTRACT_SOURCE_AMBIGUOUS', message: 'Chỉ chọn một nguồn để AI bóc tách chính xác.' }); let response; if (file) { const form = new FormData(); form.append('file', file); response = await fetchFn(`${basePath}/ai/award-extract`, { method: 'POST', credentials: 'same-origin', body: form }); } else { response = await fetchFn(`${basePath}/ai/award-extract`, { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(text ? { text } : { url }) }); } const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!payload?.extracted || typeof payload.extracted !== 'object') throw new InteractionsApiError({ status: 502, code: 'AWARD_EXTRACT_INVALID_RESPONSE', message: 'Kết quả AI trả về không hợp lệ.' }); return Object.freeze({ extracted: Object.freeze({ ...payload.extracted }) }); },
  });
}
