import { InteractionsApiError } from '../../interactions/domain/interactions-api.mjs';

function errorOf(status, payload) { return new InteractionsApiError({ status, code: payload?.code, message: payload?.message || payload?.error || 'Không thể tải giám sát truyền thông.' }); }

export function createMonitoringApi({ fetchFn = globalThis.fetch, basePath = '/api' } = {}) {
  if (typeof fetchFn !== 'function') throw new TypeError('fetchFn phải là function.');
  return Object.freeze({
    async getCurrentUser() { const response = await fetchFn(`${basePath}/me`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload; },
    async getDashboard({ days = 30 } = {}) { const normalizedDays = [7, 30, 90].includes(Number(days)) ? Number(days) : 30; const from = new Date(Date.now() - (normalizedDays - 1) * 86_400_000).toISOString().slice(0, 10); const response = await fetchFn(`${basePath}/monitor/dashboard?from=${encodeURIComponent(from)}`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!payload?.counts || !payload?.sentiment || !Array.isArray(payload?.alerts)) throw new InteractionsApiError({ status: 502, code: 'MONITOR_DASHBOARD_INVALID_RESPONSE', message: 'Dữ liệu giám sát trả về không hợp lệ.' }); return payload; },
    async getSources() { const response = await fetchFn(`${basePath}/monitor/sources`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'MONITOR_SOURCES_INVALID_RESPONSE', message: 'Danh sách nguồn tin trả về không hợp lệ.' }); return payload.rows; },
    async saveSource(input, id = null) { const updating = id != null; const sourceId = Number(id); if (updating && (!Number.isInteger(sourceId) || sourceId < 1)) throw new TypeError('Mã nguồn tin không hợp lệ.'); const name = String(input?.name || '').trim(); const url = String(input?.url || '').trim(); if (!name || !url) throw new TypeError('Nhập tên và URL nguồn tin.'); const payload = { name, url, type: ['news', 'social', 'website', 'other'].includes(input?.type) ? input.type : 'news', enabled: input?.enabled !== false }; const response = await fetchFn(updating ? `${basePath}/monitor/sources/${sourceId}` : `${basePath}/monitor/sources`, { method: updating ? 'PUT' : 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, result); if (!updating && !Number.isInteger(Number(result?.id))) throw new InteractionsApiError({ status: 502, code: 'MONITOR_SOURCE_CREATE_INVALID_RESPONSE', message: 'Máy chủ chưa trả mã nguồn tin hợp lệ.' }); return Object.freeze({ id: updating ? sourceId : Number(result.id), mode: result?.mode || null }); },
    async deleteSource(id) { const sourceId = Number(id); if (!Number.isInteger(sourceId) || sourceId < 1) throw new TypeError('Mã nguồn tin không hợp lệ.'); const response = await fetchFn(`${basePath}/monitor/sources/${sourceId}`, { method: 'DELETE', credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return Object.freeze({ ok: true }); },
    async getMentions({ page = 1, pageSize = 20, search = '', category = '', sentiment = '', status = '' } = {}) { const query = new URLSearchParams({ page: String(Math.max(1, Number.parseInt(page, 10) || 1)), pageSize: String(Math.min(100, Math.max(1, Number.parseInt(pageSize, 10) || 20))), search: String(search || '') }); for (const [key, value] of Object.entries({ category, sentiment, status })) if (value) query.set(key, String(value)); const response = await fetchFn(`${basePath}/monitor/mentions?${query}`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'MONITOR_MENTIONS_INVALID_RESPONSE', message: 'Danh sách tin bài trả về không hợp lệ.' }); return payload; },
    async updateMention(id, payload) { const mentionId = Number(id); if (!Number.isInteger(mentionId) || mentionId < 1) throw new TypeError('Mã tin bài không hợp lệ.'); const response = await fetchFn(`${basePath}/monitor/mentions/${mentionId}`, { method: 'PUT', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, result); return Object.freeze({ ok: true }); },
    async getQueries() { const response = await fetchFn(`${basePath}/monitor/queries`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'MONITOR_QUERIES_INVALID_RESPONSE', message: 'Danh sách bộ từ khóa trả về không hợp lệ.' }); return payload.rows; },
    async saveQuery(input, id = null) { const updating = id != null; const queryId = Number(id); if (updating && (!Number.isInteger(queryId) || queryId < 1)) throw new TypeError('Mã bộ từ khóa không hợp lệ.'); const name = String(input?.name || '').trim(); if (!name) throw new TypeError('Nhập tên bộ từ khóa.'); const asTerms = (value) => String(value || '').split(',').map((term) => term.trim()).filter(Boolean).slice(0, 50); const payload = { name, category: ['brand', 'industry', 'competitor'].includes(input?.category) ? input.category : 'brand', query_type: ['news', 'social', 'web'].includes(input?.queryType) ? input.queryType : 'news', include: asTerms(input?.include), exclude: asTerms(input?.exclude), enabled: input?.enabled !== false, grounding: input?.grounding === true }; const response = await fetchFn(updating ? `${basePath}/monitor/queries/${queryId}` : `${basePath}/monitor/queries`, { method: updating ? 'PUT' : 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, result); if (!updating && !Number.isInteger(Number(result?.id))) throw new InteractionsApiError({ status: 502, code: 'MONITOR_QUERY_CREATE_INVALID_RESPONSE', message: 'Máy chủ chưa trả mã bộ từ khóa hợp lệ.' }); return Object.freeze({ id: updating ? queryId : Number(result.id) }); },
    async deleteQuery(id) { const queryId = Number(id); if (!Number.isInteger(queryId) || queryId < 1) throw new TypeError('Mã bộ từ khóa không hợp lệ.'); const response = await fetchFn(`${basePath}/monitor/queries/${queryId}`, { method: 'DELETE', credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return Object.freeze({ ok: true }); },
    async runScan(queryIds) { const ids = [...new Set((Array.isArray(queryIds) ? queryIds : []).map(Number).filter((id) => Number.isInteger(id) && id > 0))]; if (!ids.length) throw new TypeError('Chọn ít nhất một bộ từ khóa trước khi quét.'); const response = await fetchFn(`${basePath}/monitor/scan`, { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ query_ids: ids }) }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Number.isInteger(Number(payload?.runId))) throw new InteractionsApiError({ status: 502, code: 'MONITOR_SCAN_INVALID_RESPONSE', message: 'Máy chủ chưa trả kết quả quét hợp lệ.' }); return Object.freeze({ runId: Number(payload.runId), fetched: Number(payload.fetched) || 0, newMentions: Number(payload.new_mentions) || 0, analyzed: Number(payload.analyzed) || 0 }); },
    async getRuns() { const response = await fetchFn(`${basePath}/monitor/runs`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'MONITOR_RUNS_INVALID_RESPONSE', message: 'Lịch sử quét trả về không hợp lệ.' }); return payload.rows; },
    async getHighlights() { const response = await fetchFn(`${basePath}/monitor/highlights`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload || {}; },
    async getCompetitorBrief() { const response = await fetchFn(`${basePath}/monitor/competitor-brief`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload || {}; },
    async getSettings() { const response = await fetchFn(`${basePath}/monitor/settings`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload || {}; },
    async saveSettings(input) { const interval = Number.parseInt(input?.interval_hours, 10); const days = Number.parseInt(input?.scan_days, 10); const payload = { autoscan: input?.autoscan === true, interval_hours: Number.isInteger(interval) ? Math.max(1, Math.min(168, interval)) : 4, scan_days: Number.isInteger(days) ? Math.max(1, Math.min(365, days)) : 30 }; const response = await fetchFn(`${basePath}/monitor/settings`, { method: 'PUT', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, result); return Object.freeze({ ok: true }); },
    async markAlertRead(id) { const alertId = Number(id); if (!Number.isInteger(alertId) || alertId < 1) throw new TypeError('Mã cảnh báo không hợp lệ.'); const response = await fetchFn(`${basePath}/monitor/alerts/${alertId}/read`, { method: 'POST', credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return Object.freeze({ ok: true }); },
    async getCompetitors() { const response = await fetchFn(`${basePath}/monitor/competitors`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'MONITOR_COMPETITORS_INVALID_RESPONSE', message: 'Danh sách đối thủ trả về không hợp lệ.' }); return payload.rows; },
    async saveCompetitor(input, id = null) { const updating = id != null; const competitorId = Number(id); if (updating && (!Number.isInteger(competitorId) || competitorId < 1)) throw new TypeError('Mã đối thủ không hợp lệ.'); const name = String(input?.name || '').trim(); if (!name) throw new TypeError('Nhập tên đối thủ.'); const split = (value) => String(value || '').split(',').map((part) => part.trim()).filter(Boolean).slice(0, 30); const payload = { name, website: String(input?.website || '').trim() || null, fanpage: String(input?.fanpage || '').trim() || null, channels: split(input?.channels), note: String(input?.note || '').trim() || null }; const response = await fetchFn(updating ? `${basePath}/monitor/competitors/${competitorId}` : `${basePath}/monitor/competitors`, { method: updating ? 'PUT' : 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, result); if (!updating && !Number.isInteger(Number(result?.id))) throw new InteractionsApiError({ status: 502, code: 'MONITOR_COMPETITOR_CREATE_INVALID_RESPONSE', message: 'Máy chủ chưa trả mã đối thủ hợp lệ.' }); return Object.freeze({ id: updating ? competitorId : Number(result.id) }); },
    async deleteCompetitor(id) { const competitorId = Number(id); if (!Number.isInteger(competitorId) || competitorId < 1) throw new TypeError('Mã đối thủ không hợp lệ.'); const response = await fetchFn(`${basePath}/monitor/competitors/${competitorId}`, { method: 'DELETE', credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return Object.freeze({ ok: true }); },
    async getCampaigns() { const response = await fetchFn(`${basePath}/monitor/campaigns`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'MONITOR_CAMPAIGNS_INVALID_RESPONSE', message: 'Danh sách chiến dịch trả về không hợp lệ.' }); return payload.rows; },
    async saveCampaign(input, id = null) { const updating = id != null; const campaignId = Number(id); if (updating && (!Number.isInteger(campaignId) || campaignId < 1)) throw new TypeError('Mã chiến dịch không hợp lệ.'); const name = String(input?.name || '').trim(); if (!name) throw new TypeError('Nhập tên chiến dịch.'); const split = (value) => String(value || '').split(',').map((part) => part.trim()).filter(Boolean).slice(0, 50); const payload = { name, start_date: String(input?.startDate || '').trim() || null, end_date: String(input?.endDate || '').trim() || null, message: String(input?.message || '').trim() || null, content: String(input?.content || '').trim() || null, audience: String(input?.audience || '').trim() || null, status: String(input?.status || '').trim() || null, note: String(input?.note || '').trim() || null, keywords: split(input?.keywords), competitors: split(input?.competitors) }; const response = await fetchFn(updating ? `${basePath}/monitor/campaigns/${campaignId}` : `${basePath}/monitor/campaigns`, { method: updating ? 'PUT' : 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, result); if (!updating && !Number.isInteger(Number(result?.id))) throw new InteractionsApiError({ status: 502, code: 'MONITOR_CAMPAIGN_CREATE_INVALID_RESPONSE', message: 'Máy chủ chưa trả mã chiến dịch hợp lệ.' }); return Object.freeze({ id: updating ? campaignId : Number(result.id) }); },
    async deleteCampaign(id) { const campaignId = Number(id); if (!Number.isInteger(campaignId) || campaignId < 1) throw new TypeError('Mã chiến dịch không hợp lệ.'); const response = await fetchFn(`${basePath}/monitor/campaigns/${campaignId}`, { method: 'DELETE', credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return Object.freeze({ ok: true }); },
    async getCampaignResults(id) { const campaignId = Number(id); if (!Number.isInteger(campaignId) || campaignId < 1) throw new TypeError('Mã chiến dịch không hợp lệ.'); const response = await fetchFn(`${basePath}/monitor/campaigns/${campaignId}/results`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload || {}; },
    async evaluateCampaign(id) { const campaignId = Number(id); if (!Number.isInteger(campaignId) || campaignId < 1) throw new TypeError('Mã chiến dịch không hợp lệ.'); const response = await fetchFn(`${basePath}/monitor/campaigns/${campaignId}/evaluate`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload || {}; },
  });
}
