import { InteractionsApiError } from '../../interactions/domain/interactions-api.mjs';

function errorOf(status, payload) { return new InteractionsApiError({ status, code: payload?.code, message: payload?.message || payload?.error || 'Không thể tải giám sát truyền thông.' }); }

export function createMonitoringApi({ fetchFn = globalThis.fetch, basePath = '/api' } = {}) {
  if (typeof fetchFn !== 'function') throw new TypeError('fetchFn phải là function.');
  return Object.freeze({
    async getCurrentUser() { const response = await fetchFn(`${basePath}/me`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return payload; },
    async getDashboard({ days = 30 } = {}) { const normalizedDays = [7, 30, 90].includes(Number(days)) ? Number(days) : 30; const from = new Date(Date.now() - (normalizedDays - 1) * 86_400_000).toISOString().slice(0, 10); const response = await fetchFn(`${basePath}/monitor/dashboard?from=${encodeURIComponent(from)}`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!payload?.counts || !payload?.sentiment || !Array.isArray(payload?.alerts)) throw new InteractionsApiError({ status: 502, code: 'MONITOR_DASHBOARD_INVALID_RESPONSE', message: 'Dữ liệu giám sát trả về không hợp lệ.' }); return payload; },
    async getSources() { const response = await fetchFn(`${basePath}/monitor/sources`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'MONITOR_SOURCES_INVALID_RESPONSE', message: 'Danh sách nguồn tin trả về không hợp lệ.' }); return payload.rows; },
    async saveSource(input, id = null) { const updating = id != null; const sourceId = Number(id); if (updating && (!Number.isInteger(sourceId) || sourceId < 1)) throw new TypeError('Mã nguồn tin không hợp lệ.'); const name = String(input?.name || '').trim(); const url = String(input?.url || '').trim(); if (!name || !url) throw new TypeError('Nhập tên và URL nguồn tin.'); const payload = { name, url, type: ['news', 'social', 'website', 'other'].includes(input?.type) ? input.type : 'news', enabled: input?.enabled !== false }; const response = await fetchFn(updating ? `${basePath}/monitor/sources/${sourceId}` : `${basePath}/monitor/sources`, { method: updating ? 'PUT' : 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, result); if (!updating && !Number.isInteger(Number(result?.id))) throw new InteractionsApiError({ status: 502, code: 'MONITOR_SOURCE_CREATE_INVALID_RESPONSE', message: 'Máy chủ chưa trả mã nguồn tin hợp lệ.' }); return Object.freeze({ id: updating ? sourceId : Number(result.id), mode: result?.mode || null }); },
    async deleteSource(id) { const sourceId = Number(id); if (!Number.isInteger(sourceId) || sourceId < 1) throw new TypeError('Mã nguồn tin không hợp lệ.'); const response = await fetchFn(`${basePath}/monitor/sources/${sourceId}`, { method: 'DELETE', credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); return Object.freeze({ ok: true }); },
    async getMentions({ page = 1, pageSize = 20, search = '', category = '', sentiment = '', status = '' } = {}) { const query = new URLSearchParams({ page: String(Math.max(1, Number.parseInt(page, 10) || 1)), pageSize: String(Math.min(100, Math.max(1, Number.parseInt(pageSize, 10) || 20))), search: String(search || '') }); for (const [key, value] of Object.entries({ category, sentiment, status })) if (value) query.set(key, String(value)); const response = await fetchFn(`${basePath}/monitor/mentions?${query}`, { credentials: 'same-origin' }); const payload = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, payload); if (!Array.isArray(payload?.rows)) throw new InteractionsApiError({ status: 502, code: 'MONITOR_MENTIONS_INVALID_RESPONSE', message: 'Danh sách tin bài trả về không hợp lệ.' }); return payload; },
    async updateMention(id, payload) { const mentionId = Number(id); if (!Number.isInteger(mentionId) || mentionId < 1) throw new TypeError('Mã tin bài không hợp lệ.'); const response = await fetchFn(`${basePath}/monitor/mentions/${mentionId}`, { method: 'PUT', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => null); if (!response.ok) throw errorOf(response.status, result); return Object.freeze({ ok: true }); },
  });
}
