<script setup>
import { computed, reactive, ref } from 'vue';
import MButton from '../../../components/mds/MButton.vue'; import MInput from '../../../components/mds/MInput.vue'; import MRadioGroup from '../../../components/mds/MRadioGroup.vue'; import MSelect from '../../../components/mds/MSelect.vue'; import MTextarea from '../../../components/mds/MTextarea.vue'; import MUpload from '../../../components/mds/MUpload.vue';
const props = defineProps({ proposal: { type: Object, default: null }, processing: Boolean, saving: Boolean, error: { type: String, default: '' } }); const emit = defineEmits(['cancel', 'propose', 'confirm']);
const edits = reactive({ date: '', channel: '', result: '', summary: '', selected_person_id: '', selected_org_id: '', score_delta: 0 }); const localError = ref(''); const hasProposal = computed(() => !!props.proposal);
const channelOptions = ['Gặp mặt', 'Điện thoại', 'Email', 'Sự kiện', 'Khác'].map((value) => ({ value, label: value })); const resultOptions = ['Tích cực', 'Trung lập', 'Cần theo dõi'].map((value) => ({ value, label: value }));
function select(files) { const file = files[0]; if (file) emit('propose', file); } function syncProposal() { const v = props.proposal; if (!v) return; Object.assign(edits, { date: v.extracted.date || '', channel: v.extracted.channel || 'Gặp mặt', result: v.extracted.result || 'Tích cực', summary: v.extracted.summary || '', selected_person_id: v.personCandidates.length === 1 ? String(v.personCandidates[0].id) : '', selected_org_id: v.orgCandidates.length === 1 ? String(v.orgCandidates[0].id) : '', score_delta: v.suggestedScoreDelta || 0 }); } function confirm() { if (!props.proposal) return; localError.value = ''; emit('confirm', { ...edits, selected_person_id: edits.selected_person_id || undefined, selected_org_id: edits.selected_org_id || undefined }); }
defineExpose({ syncProposal });
</script>
<template><section class="min-h-0 bg-[var(--mds-bg-page)] p-4"><div class="mx-auto max-w-[880px] rounded-lg bg-[var(--mds-bg)] shadow-[var(--mds-shadow-card)]"><header class="flex items-start justify-between gap-4 border-b border-[var(--mds-border-light)] px-5 py-4"><div><h1 class="text-[20px] font-semibold">Ghi tương tác bằng giọng nói</h1><p class="mt-1 text-[13px] text-[var(--mds-text-secondary)]">AI chỉ chuẩn bị đề xuất. Bạn phải rà soát và xác nhận trước khi lưu.</p></div><MButton variant="neutral" :disabled="processing || saving" @click="emit('cancel')">Hủy</MButton></header><div class="space-y-4 p-5"><MUpload v-if="!hasProposal" accept="audio/*" :multiple="false" :max-size-m-b="25" label="Tệp ghi âm" :disabled="processing" @select-files="select" /><p v-if="!hasProposal" class="text-[12px] text-[var(--mds-text-secondary)]">Thu âm trực tiếp trong AMIS Mobile chưa sẵn sàng; hãy chọn tệp audio hợp lệ.</p><template v-else><p class="rounded-lg bg-[var(--mds-brand-50)] px-3 py-2 text-[13px] text-[var(--mds-brand-700)]">Đề xuất hết hạn: {{ proposal.expiresAt }}. Không có dữ liệu nào được lưu cho đến khi bạn xác nhận.</p><label><span class="mb-1 block text-[13px] font-medium">Ngày</span><MInput v-model="edits.date" type="date" /></label><div class="grid gap-4 sm:grid-cols-2"><label><span class="mb-1 block text-[13px] font-medium">Kênh</span><MSelect v-model="edits.channel" :options="channelOptions" /></label><label><span class="mb-1 block text-[13px] font-medium">Kết quả</span><MSelect v-model="edits.result" :options="resultOptions" /></label></div><label><span class="mb-1 block text-[13px] font-medium">Nội dung</span><MTextarea v-model="edits.summary" /></label><section v-if="proposal.personCandidates.length"><span class="mb-2 block text-[13px] font-medium">Người liên hệ</span><MRadioGroup v-model="edits.selected_person_id" direction="vertical" :options="proposal.personCandidates.map((item) => ({ value: String(item.id), label: `${item.name}${item.org_name ? ' · ' + item.org_name : ''}` }))" /></section><section v-if="proposal.orgCandidates.length"><span class="mb-2 block text-[13px] font-medium">Cơ quan</span><MRadioGroup v-model="edits.selected_org_id" direction="vertical" :options="proposal.orgCandidates.map((item) => ({ value: String(item.id), label: `${item.name}${item.org_type ? ' · ' + item.org_type : ''}` }))" /></section></template><p v-if="error || localError" role="alert" class="rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{ error || localError }}</p></div><footer class="sticky bottom-0 flex justify-end gap-2 border-t border-[var(--mds-border-light)] bg-[var(--mds-bg)] px-5 py-3"><MButton variant="neutral" :disabled="processing || saving" @click="emit('cancel')">Hủy</MButton><MButton v-if="hasProposal" variant="primary" :loading="saving" @click="confirm">Xác nhận ghi tương tác</MButton></footer></div></section></template>
