<script setup>
import { computed, ref } from 'vue';
import MButton from '../../../components/mds/MButton.vue';
import MDialog from '../../../components/mds/MDialog.vue';
import MEmptyState from '../../../components/mds/MEmptyState.vue';
import MIcon from '../../../components/MIcon.vue';
import MMobileBottomNav from '../../../components/mds/MMobileBottomNav.vue';
import MMobileTopBar from '../../../components/mds/MMobileTopBar.vue';
const props = defineProps({ dashboard: { type: Object, default: null }, safeAreaStyle: { type: Object, default: () => ({}) }, nativeNavigation: { type: Array, default: () => [] } });
const emit = defineEmits(['navigate']); const moreOpen = ref(false); const primaryKeys = new Set(['dashboard', 'people', 'interactions', 'events']);
const primaryNavigation = computed(() => [...props.nativeNavigation.filter((item) => primaryKeys.has(item.key)), { key: 'more', label: 'Khác', icon: 'dots-circle-horizontal', active: false }]);
const moreNavigation = computed(() => props.nativeNavigation.filter((item) => !primaryKeys.has(item.key)));
function navigate(key) { if (key === 'more') { moreOpen.value = true; return; } emit('navigate', key); }
function navigateMore(key) { moreOpen.value = false; emit('navigate', key); }
</script>

<template>
  <section class="mds-mobile-app flex h-[100dvh] min-w-0 flex-col overflow-hidden bg-[var(--mds-bg)]" :style="safeAreaStyle"><MMobileTopBar title="Tổng quan" :show-back="false"/><main class="min-h-0 flex-1 overflow-y-auto pb-[calc(var(--mds-mobile-bottom-nav-height)+var(--mds-mobile-safe-bottom))]"><div class="mds-mobile-gutter-x space-y-4 py-4"><p class="text-[13px] text-[var(--mds-text-secondary)]">Theo dõi quan hệ, lịch nhắc và hoạt động tháng {{ dashboard?.month }}/{{ dashboard?.year }}.</p><MEmptyState v-if="!dashboard" title="Chưa có dữ liệu" description="Kiểm tra lại quyền truy cập."/><template v-else><section v-for="group in dashboard.groups" :key="group.key" class="rounded-lg bg-[var(--mds-bg-page)] p-4"><div class="mb-3 flex items-center justify-between gap-2"><h2 class="flex items-center gap-2 text-[15px] font-semibold"><MIcon :name="group.icon" :size="20"/>{{ group.title }}</h2><MButton variant="icon" class="[&]:h-[var(--mds-mobile-touch-target)] [&]:w-[var(--mds-mobile-touch-target)]" :aria-label="`Mở ${group.title}`" @click="emit('navigate', group.navigate)"><template #icon><MIcon name="chevron-right" :size="20"/></template></MButton></div><div class="grid grid-cols-3 gap-2"><MButton v-for="stat in group.stats" :key="stat.label" variant="neutral" class="[&]:h-auto [&]:min-h-[76px] [&]:w-full [&]:justify-start [&]:px-2 [&]:py-2 [&]:text-left" @click="emit('navigate', stat.navigate)"><span class="block"><strong class="block text-[18px]">{{ stat.value }}</strong><span class="mt-1 block text-[11px] leading-4 text-[var(--mds-text-secondary)]">{{ stat.label }}</span></span></MButton></div></section><section class="rounded-lg bg-[var(--mds-bg-page)] p-4"><div class="flex items-center justify-between gap-2"><h2 class="text-[15px] font-semibold">Sắp tới</h2><MButton variant="link" @click="emit('navigate', 'reminders')">Xem lịch</MButton></div><MEmptyState v-if="!dashboard.upcoming.length" title="Chưa có lịch gần" description="Không có mốc trong 60 ngày tới."/><div v-else class="mt-2 divide-y divide-[var(--mds-border-light)]"><MButton v-for="item in dashboard.upcoming" :key="`${item.title}-${item.date}`" variant="ghost" class="[&]:h-auto [&]:min-h-[var(--mds-mobile-touch-target)] [&]:w-full [&]:justify-start [&]:px-0 [&]:py-3 [&]:text-left" @click="emit('navigate', item.navigate)"><span class="block"><strong class="block text-[13px]">{{ item.title }}</strong><span class="mt-1 block text-[12px] text-[var(--mds-text-secondary)]">{{ item.date || 'Chưa có ngày' }}<span v-if="item.daysUntil !== null"> · còn {{ item.daysUntil }} ngày</span></span></span></MButton></div></section></template></div></main><MMobileBottomNav :items="primaryNavigation" @navigate="navigate"/></section>
  <MDialog v-model="moreOpen" title="Khám phá PR Workstation" confirm-text="Đóng"><p class="mb-3 text-[13px] text-[var(--mds-text-secondary)]">Chọn phân hệ cần làm việc. Máy chủ luôn kiểm tra lại dữ liệu và quyền.</p><div class="grid gap-2"><MButton v-for="item in moreNavigation" :key="item.key" variant="neutral" class="[&]:w-full [&]:justify-start" :disabled="item.disabled" @click="navigateMore(item.key)"><template #icon><MIcon :name="item.icon" :size="20"/></template>{{ item.label }}</MButton></div></MDialog>
</template>
