<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import MDialog from '../../components/mds/MDialog.vue'; import MEmptyState from '../../components/mds/MEmptyState.vue'; import MMobileTopBar from '../../components/mds/MMobileTopBar.vue'; import MSpinner from '../../components/mds/MSpinner.vue';
import { HostSurface } from '../../platform/host-adapter.mjs'; import { createMonitoringApi } from './domain/monitoring-api.mjs'; import { monitoringDashboardViewModel, monitoringMentionsViewModel, monitoringQueriesViewModel, monitoringSourcesViewModel } from './domain/monitoring-view.mjs'; import MonitoringDashboardDesktop from './desktop/MonitoringDashboardDesktop.vue'; import MonitoringDashboardMobile from './mobile/MonitoringDashboardMobile.vue'; import MonitoringMentionReviewDesktop from './desktop/MonitoringMentionReviewDesktop.vue'; import MonitoringMentionReviewMobile from './mobile/MonitoringMentionReviewMobile.vue'; import MonitoringMentionsDesktop from './desktop/MonitoringMentionsDesktop.vue'; import MonitoringMentionsMobile from './mobile/MonitoringMentionsMobile.vue'; import MonitoringQueriesDesktop from './desktop/MonitoringQueriesDesktop.vue'; import MonitoringQueriesMobile from './mobile/MonitoringQueriesMobile.vue'; import MonitoringQueryFormDesktop from './desktop/MonitoringQueryFormDesktop.vue'; import MonitoringQueryFormMobile from './mobile/MonitoringQueryFormMobile.vue'; import MonitoringSourcesDesktop from './desktop/MonitoringSourcesDesktop.vue'; import MonitoringSourcesMobile from './mobile/MonitoringSourcesMobile.vue'; import MonitoringSourceFormDesktop from './desktop/MonitoringSourceFormDesktop.vue'; import MonitoringSourceFormMobile from './mobile/MonitoringSourceFormMobile.vue';
const props=defineProps({surface:String,adapter:Object,hostUnavailable:Boolean}); const emit=defineEmits(['back']); const api=createMonitoringApi(); const isNative=computed(()=>props.surface===HostSurface.NATIVE); const safeArea=ref(props.adapter?.getSafeArea?.()||{}); const safeAreaStyle=computed(()=>Object.fromEntries(['top','right','bottom','left'].flatMap((side)=>Number.isFinite(Number(safeArea.value?.[side]))?[[`--mds-mobile-safe-${side}`,`${Number(safeArea.value[side])}px`]]:[]))); const state=reactive({phase:'loading',days:30,dashboard:null,permissions:null,mode:'dashboard',sources:[],editing:null,queries:[],queryEditing:null,saving:false,saveError:'',deleting:null,mentions:[],mentionsTotal:0,mentionsPage:1,mentionsPageSize:20,mentionsSearch:'',mentionsCategory:'',mentionsSentiment:'',mentionsStatus:'',mentionsLoading:false,mentionEditing:null,error:null}); const canManageSources=computed(()=>state.permissions?.modules?.admin?.includes('edit')===true); const canManageQueries=computed(()=>state.permissions?.modules?.admin?.includes('edit')===true); const canEditMentions=computed(()=>state.permissions?.modules?.monitoring?.includes('edit')===true);
async function load(days=state.days){ if(props.hostUnavailable){state.phase='error';state.error={status:503,message:'Native host chưa sẵn sàng. Ứng dụng không chuyển sang giao diện desktop thay thế.'};return;} state.days=days;state.phase='loading';state.error=null;try{const [payload,session]=await Promise.all([api.getDashboard({days}),api.getCurrentUser()]);state.dashboard=monitoringDashboardViewModel(payload);state.permissions=session?.permissions||null;state.phase='ready';}catch(error){state.phase='error';state.error=error;}}
async function openSources(){state.mode='sources';state.saveError='';try{state.sources=monitoringSourcesViewModel(await api.getSources());}catch(error){state.saveError=error.message;}}
function beginCreateSource(){if(canManageSources.value){state.editing=null;state.saveError='';state.mode='source-form';}}
function beginEditSource(record){if(canManageSources.value&&record?.id){state.editing=record;state.saveError='';state.mode='source-form';}}
async function saveSource(input){if(!canManageSources.value)return;state.saving=true;state.saveError='';try{await api.saveSource(input,state.editing?.id??null);await openSources();}catch(error){state.saveError=error.message;}finally{state.saving=false;}}
function askDeleteSource(record){if(canManageSources.value&&record?.id)state.deleting=record;}
async function deleteSource(){const record=state.deleting;if(!record?.id)return;state.deleting=null;try{await api.deleteSource(record.id);await openSources();}catch(error){state.saveError=error.message;}}
async function openQueries(){state.mode='queries';state.saveError='';try{state.queries=monitoringQueriesViewModel(await api.getQueries());}catch(error){state.saveError=error.message;}}
function beginCreateQuery(){if(canManageQueries.value){state.queryEditing=null;state.saveError='';state.mode='query-form';}}
function beginEditQuery(record){if(canManageQueries.value&&record?.id){state.queryEditing=record;state.saveError='';state.mode='query-form';}}
async function saveQuery(input){if(!canManageQueries.value)return;state.saving=true;state.saveError='';try{await api.saveQuery(input,state.queryEditing?.id??null);await openQueries();}catch(error){state.saveError=error.message;}finally{state.saving=false;}}
function askDeleteQuery(record){if(canManageQueries.value&&record?.id)state.deleting={...record,kind:'query'};}
async function deleteManagedRecord(){const record=state.deleting;if(!record?.id)return;state.deleting=null;try{if(record.kind==='query'){await api.deleteQuery(record.id);await openQueries();}else{await api.deleteSource(record.id);await openSources();}}catch(error){state.saveError=error.message;}}
async function loadMentions({page=state.mentionsPage,search=state.mentionsSearch,filters={}}={}){state.mentionsLoading=true;state.saveError='';const changes=Object.fromEntries(Object.entries(filters).map(([key,value])=>[`mentions${key[0].toUpperCase()}${key.slice(1)}`,String(value||'')]));Object.assign(state,{mentionsPage:Math.max(1,Number(page)||1),mentionsSearch:String(search||''),...changes});try{const payload=await api.getMentions({page:state.mentionsPage,pageSize:state.mentionsPageSize,search:state.mentionsSearch,category:state.mentionsCategory,sentiment:state.mentionsSentiment,status:state.mentionsStatus});state.mentions=monitoringMentionsViewModel(payload.rows);state.mentionsTotal=Number(payload.total)||0;state.mentionsPage=Number(payload.page)||state.mentionsPage;}catch(error){state.saveError=error.message;state.mentions=[];state.mentionsTotal=0;}finally{state.mentionsLoading=false;}}
async function openMentions(){state.mode='mentions';await loadMentions({page:1});}
async function updateMentionFilters(filters){await loadMentions({page:1,filters});}
function beginMentionReview(record){if(canEditMentions.value&&record?.id){state.mentionEditing=record;state.saveError='';state.mode='mention-review';}}
async function saveMentionReview(payload){const record=state.mentionEditing;if(!canEditMentions.value||!record?.id)return;state.saving=true;state.saveError='';try{await api.updateMention(record.id,payload);state.mode='mentions';await loadMentions();}catch(error){state.saveError=error.message;}finally{state.saving=false;}}
function back(){if(isNative.value&&props.adapter)return props.adapter.goBack({reason:'monitor-dashboard'});emit('back');} onMounted(load);
</script>
<template>
  <div v-if="state.phase==='loading'" :class="isNative?'mds-mobile-app grid h-[100dvh] place-items-center bg-[var(--mds-bg)]':'grid min-h-[360px] place-items-center bg-[var(--mds-bg-page)]'"><MSpinner :size="28"/></div>
  <section v-else-if="state.phase==='error'" :class="isNative?'mds-mobile-app min-h-[100dvh] bg-[var(--mds-bg)]':'min-h-[360px] bg-[var(--mds-bg-page)]'"><MMobileTopBar v-if="isNative" title="Giám sát truyền thông" @back="back"/><MEmptyState :title="state.error.status===403?'Bạn không có quyền xem giám sát truyền thông':'Không thể mở giám sát truyền thông'" :description="state.error.message"/></section>
  <MonitoringSourceFormMobile v-else-if="isNative&&state.mode==='source-form'" :record="state.editing" :editing="Boolean(state.editing)" :saving="state.saving" :error="state.saveError" :safe-area-style="safeAreaStyle" @cancel="state.mode='sources'" @save="saveSource"/>
  <MonitoringSourcesMobile v-else-if="isNative&&state.mode==='sources'" :rows="state.sources" :can-manage="canManageSources" :safe-area-style="safeAreaStyle" @back="state.mode='dashboard'" @create="beginCreateSource" @edit="beginEditSource" @delete="askDeleteSource"/>
  <MonitoringQueryFormMobile v-else-if="isNative&&state.mode==='query-form'" :record="state.queryEditing" :editing="Boolean(state.queryEditing)" :saving="state.saving" :error="state.saveError" :safe-area-style="safeAreaStyle" @cancel="state.mode='queries'" @save="saveQuery"/>
  <MonitoringQueriesMobile v-else-if="isNative&&state.mode==='queries'" :rows="state.queries" :can-manage="canManageQueries" :safe-area-style="safeAreaStyle" @back="state.mode='dashboard'" @create="beginCreateQuery" @edit="beginEditQuery" @delete="askDeleteQuery"/>
  <MonitoringMentionReviewMobile v-else-if="isNative&&state.mode==='mention-review'" :record="state.mentionEditing" :saving="state.saving" :error="state.saveError" :safe-area-style="safeAreaStyle" @cancel="state.mode='mentions'" @save="saveMentionReview"/>
  <MonitoringMentionsMobile v-else-if="isNative&&state.mode==='mentions'" :rows="state.mentions" :total="state.mentionsTotal" :page="state.mentionsPage" :page-size="state.mentionsPageSize" :search="state.mentionsSearch" :category="state.mentionsCategory" :sentiment="state.mentionsSentiment" :status="state.mentionsStatus" :loading="state.mentionsLoading" :can-edit="canEditMentions" :safe-area-style="safeAreaStyle" @back="state.mode='dashboard'" @search="loadMentions({page:1,search:$event})" @filters="updateMentionFilters" @review="beginMentionReview" @page="loadMentions({page:$event})"/>
  <MonitoringDashboardMobile v-else-if="isNative" :dashboard="state.dashboard" :days="state.days" :loading="state.phase==='loading'" :safe-area-style="safeAreaStyle" @back="back" @range="load" @mentions="openMentions" @sources="openSources" @queries="openQueries"/>
  <MonitoringSourceFormDesktop v-else-if="state.mode==='source-form'" :record="state.editing" :editing="Boolean(state.editing)" :saving="state.saving" :error="state.saveError" @cancel="state.mode='sources'" @save="saveSource"/>
  <MonitoringSourcesDesktop v-else-if="state.mode==='sources'" :rows="state.sources" :can-manage="canManageSources" @back="state.mode='dashboard'" @create="beginCreateSource" @edit="beginEditSource" @delete="askDeleteSource"/>
  <MonitoringQueryFormDesktop v-else-if="state.mode==='query-form'" :record="state.queryEditing" :editing="Boolean(state.queryEditing)" :saving="state.saving" :error="state.saveError" @cancel="state.mode='queries'" @save="saveQuery"/>
  <MonitoringQueriesDesktop v-else-if="state.mode==='queries'" :rows="state.queries" :can-manage="canManageQueries" @back="state.mode='dashboard'" @create="beginCreateQuery" @edit="beginEditQuery" @delete="askDeleteQuery"/>
  <MonitoringMentionReviewDesktop v-else-if="state.mode==='mention-review'" :record="state.mentionEditing" :saving="state.saving" :error="state.saveError" @cancel="state.mode='mentions'" @save="saveMentionReview"/>
  <MonitoringMentionsDesktop v-else-if="state.mode==='mentions'" :rows="state.mentions" :total="state.mentionsTotal" :page="state.mentionsPage" :page-size="state.mentionsPageSize" :search="state.mentionsSearch" :category="state.mentionsCategory" :sentiment="state.mentionsSentiment" :status="state.mentionsStatus" :loading="state.mentionsLoading" :can-edit="canEditMentions" @back="state.mode='dashboard'" @search="loadMentions({page:1,search:$event})" @filters="updateMentionFilters" @review="beginMentionReview" @page="loadMentions({page:$event})"/>
  <MonitoringDashboardDesktop v-else :dashboard="state.dashboard" :days="state.days" :loading="state.phase==='loading'" @range="load" @mentions="openMentions" @sources="openSources" @queries="openQueries"/>
  <MDialog :model-value="Boolean(state.deleting)" :title="state.deleting?.kind==='query'?'Xóa bộ từ khóa?':'Xóa nguồn tin?'" type="danger" confirm-text="Xóa" @update:model-value="!$event&&(state.deleting=null)" @confirm="deleteManagedRecord"><p><strong>{{state.deleting?.name}}</strong> sẽ bị xóa. Máy chủ kiểm tra lại quyền quản trị trước khi thực hiện.</p></MDialog>
</template>
