<script setup>
import { computed, onMounted, reactive, ref } from 'vue';
import MEmptyState from '../../components/mds/MEmptyState.vue'; import MMobileTopBar from '../../components/mds/MMobileTopBar.vue'; import MSpinner from '../../components/mds/MSpinner.vue';
import { HostSurface } from '../../platform/host-adapter.mjs'; import { createMonitoringApi } from './domain/monitoring-api.mjs'; import { monitoringDashboardViewModel } from './domain/monitoring-view.mjs'; import MonitoringDashboardDesktop from './desktop/MonitoringDashboardDesktop.vue'; import MonitoringDashboardMobile from './mobile/MonitoringDashboardMobile.vue';
const props=defineProps({surface:String,adapter:Object,hostUnavailable:Boolean}); const emit=defineEmits(['back']); const api=createMonitoringApi(); const isNative=computed(()=>props.surface===HostSurface.NATIVE); const safeArea=ref(props.adapter?.getSafeArea?.()||{}); const safeAreaStyle=computed(()=>Object.fromEntries(['top','right','bottom','left'].flatMap((side)=>Number.isFinite(Number(safeArea.value?.[side]))?[[`--mds-mobile-safe-${side}`,`${Number(safeArea.value[side])}px`]]:[]))); const state=reactive({phase:'loading',days:30,dashboard:null,error:null});
async function load(days=state.days){ if(props.hostUnavailable){state.phase='error';state.error={status:503,message:'Native host chưa sẵn sàng. Ứng dụng không chuyển sang giao diện desktop thay thế.'};return;} state.days=days;state.phase='loading';state.error=null;try{const payload=await api.getDashboard({days});state.dashboard=monitoringDashboardViewModel(payload);state.phase='ready';}catch(error){state.phase='error';state.error=error;}}
function back(){if(isNative.value&&props.adapter)return props.adapter.goBack({reason:'monitor-dashboard'});emit('back');} onMounted(load);
</script>
<template><div v-if="state.phase==='loading'" :class="isNative?'mds-mobile-app grid h-[100dvh] place-items-center bg-[var(--mds-bg)]':'grid min-h-[360px] place-items-center bg-[var(--mds-bg-page)]'"><MSpinner :size="28"/></div><section v-else-if="state.phase==='error'" :class="isNative?'mds-mobile-app min-h-[100dvh] bg-[var(--mds-bg)]':'min-h-[360px] bg-[var(--mds-bg-page)]'"><MMobileTopBar v-if="isNative" title="Giám sát truyền thông" @back="back"/><MEmptyState :title="state.error.status===403?'Bạn không có quyền xem giám sát truyền thông':'Không thể mở giám sát truyền thông'" :description="state.error.message"/></section><MonitoringDashboardMobile v-else-if="isNative" :dashboard="state.dashboard" :days="state.days" :loading="state.phase==='loading'" :safe-area-style="safeAreaStyle" @back="back" @range="load"/><MonitoringDashboardDesktop v-else :dashboard="state.dashboard" :days="state.days" :loading="state.phase==='loading'" @range="load"/></template>
