<script setup>
import { computed, onMounted, reactive, ref, watch } from 'vue';
import MEmptyState from '../../components/mds/MEmptyState.vue'; import MMobileTopBar from '../../components/mds/MMobileTopBar.vue'; import MSpinner from '../../components/mds/MSpinner.vue';
import { HostSurface } from '../../platform/host-adapter.mjs'; import { createAwardsApi } from './domain/awards-api.mjs'; import { awardDetailViewModel, awardsListViewModel } from './domain/award-view.mjs';
import AwardDetailDesktop from './desktop/AwardDetailDesktop.vue'; import AwardsListDesktop from './desktop/AwardsListDesktop.vue'; import AwardDetailMobile from './mobile/AwardDetailMobile.vue'; import AwardsListMobile from './mobile/AwardsListMobile.vue';
const props = defineProps({ awardId: { type: Number, default: null }, surface: String, adapter: Object, hostUnavailable: Boolean }); const emit = defineEmits(['back']); const api = createAwardsApi(); const safeArea = ref(props.adapter?.getSafeArea?.() || {}); const isNative = computed(() => props.surface === HostSurface.NATIVE); const state = reactive({ phase: 'loading', rows: [], total: 0, page: 1, pageSize: 20, search: '', detail: null, mode: 'read', error: null }); const safeAreaStyle = computed(() => Object.fromEntries(['top', 'right', 'bottom', 'left'].flatMap((side) => Number.isFinite(Number(safeArea.value?.[side])) ? [[`--mds-mobile-safe-${side}`, `${Number(safeArea.value[side])}px`]] : [])));
async function load({ page = state.page, search = state.search } = {}) { if (props.hostUnavailable) { state.phase = 'error'; state.error = { status: 503, message: 'Native host chưa sẵn sàng. Ứng dụng không chuyển sang giao diện desktop thay thế.' }; return; } state.phase = 'loading'; state.error = null; try { if (props.awardId) { const payload = await api.get(props.awardId); Object.assign(state, { detail: awardDetailViewModel(payload), mode: 'detail', phase: 'ready' }); return; } const model = awardsListViewModel(await api.getList({ page, pageSize: state.pageSize, search })); Object.assign(state, { ...model, detail: null, mode: 'read', phase: 'ready' }); } catch (error) { state.phase = 'error'; state.error = error; } }
function openAward(id) { location.hash = `awards/${Number(id)}`; } function showList() { location.hash = 'awards'; } async function back() { if (isNative.value && props.adapter) return props.adapter.goBack({ reason: 'awards-list' }); emit('back'); } watch(() => props.awardId, () => load()); onMounted(load);
</script>
<template><div v-if="state.phase==='loading'" :class="isNative?'mds-mobile-app grid h-[100dvh] place-items-center bg-[var(--mds-bg)]':'grid min-h-[360px] place-items-center bg-[var(--mds-bg-page)]'"><MSpinner :size="28"/></div><section v-else-if="state.phase==='error'" :class="isNative?'mds-mobile-app min-h-[100dvh] bg-[var(--mds-bg)]':'min-h-[360px] bg-[var(--mds-bg-page)]'"><MMobileTopBar v-if="isNative" title="Giải thưởng" @back="back"/><MEmptyState :title="state.error.status===404?'Không tìm thấy giải thưởng':state.error.status===403?'Bạn không có quyền xem giải thưởng':'Không thể mở giải thưởng'" :description="state.error.message"/></section><AwardDetailMobile v-else-if="isNative&&state.mode==='detail'" :detail="state.detail" :safe-area-style="safeAreaStyle" @back="showList"/><AwardsListMobile v-else-if="isNative" :rows="state.rows" :total="state.total" :page="state.page" :page-size="state.pageSize" :search="state.search" :safe-area-style="safeAreaStyle" @back="back" @open="openAward" @search="load({page:1,search:$event})" @page="load({page:$event})"/><AwardDetailDesktop v-else-if="state.mode==='detail'" :detail="state.detail" @back="showList"/><AwardsListDesktop v-else :rows="state.rows" :total="state.total" :page="state.page" :page-size="state.pageSize" :search="state.search" @open="openAward" @search="load({page:1,search:$event})" @page="load({page:$event})"/></template>
