<script setup>
import { computed, reactive, ref, watch } from 'vue';
import MButton from '../../../components/mds/MButton.vue';
import MInput from '../../../components/mds/MInput.vue';
import MSelect from '../../../components/mds/MSelect.vue';
import MTextarea from '../../../components/mds/MTextarea.vue';
import { toAwardParticipationDraft, toAwardParticipationPayload } from '../domain/award-participation-write.mjs';

const props = defineProps({ record: { type: Object, default: () => ({}) }, editing: Boolean, saving: Boolean, error: String });
const emit = defineEmits(['cancel', 'save']);
const draft = reactive({ ...toAwardParticipationDraft(props.record) }); const localError = ref('');
const title = computed(() => props.editing ? 'Sửa kỳ tham gia' : 'Thêm kỳ tham gia'); const showBudget = computed(() => !props.editing || Object.hasOwn(props.record, 'budget'));
const statuses = ['', 'Đang cân nhắc', 'Quyết định tham gia', 'Đã nộp', 'Đạt giải', 'Trượt', 'Không tham gia'].map((value) => ({ value, label: value || 'Chọn trạng thái' }));
watch(() => props.record, (record) => Object.assign(draft, toAwardParticipationDraft(record)), { deep: true });
function submit() { try { localError.value = ''; emit('save', toAwardParticipationPayload(draft, { existingRecord: props.editing ? props.record : null })); } catch (error) { localError.value = error.message; } }
</script>

<template><section class="min-h-0 bg-[var(--mds-bg-page)] p-4"><form class="mx-auto max-w-[880px] rounded-lg bg-[var(--mds-bg)] shadow-[var(--mds-shadow-card)]" @submit.prevent="submit"><header class="flex items-start justify-between gap-4 border-b border-[var(--mds-border-light)] px-5 py-4"><div><h1 class="text-[20px] font-semibold">{{ title }}</h1><p class="mt-1 text-[13px] text-[var(--mds-text-secondary)]">Máy chủ kiểm tra lại owner và quyền thao tác khi lưu.</p></div><MButton variant="neutral" :disabled="saving" @click="emit('cancel')">Hủy</MButton></header><div class="grid gap-4 p-5 sm:grid-cols-2"><label><span class="mb-1 block text-[13px] font-medium">Năm tham gia</span><MInput v-model="draft.year" type="number" min="2000" max="2100" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Trạng thái</span><MSelect v-model="draft.status" :options="statuses" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Sản phẩm tham gia</span><MInput v-model="draft.products" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Hạng mục</span><MInput v-model="draft.categories" :disabled="saving"/></label><label v-if="showBudget"><span class="mb-1 block text-[13px] font-medium">Dự toán (đ)</span><MInput v-model="draft.budget" type="number" min="0" :disabled="saving"/></label><label><span class="mb-1 block text-[13px] font-medium">Kết quả</span><MInput v-model="draft.result" :disabled="saving"/></label><label class="sm:col-span-2"><span class="mb-1 block text-[13px] font-medium">Mục tiêu</span><MTextarea v-model="draft.goal" :disabled="saving"/></label><label class="sm:col-span-2"><span class="mb-1 block text-[13px] font-medium">Mục đích</span><MTextarea v-model="draft.purpose" :disabled="saving"/></label><label class="sm:col-span-2"><span class="mb-1 block text-[13px] font-medium">Đánh giá năng lực</span><MTextarea v-model="draft.capability" :disabled="saving"/></label><label class="sm:col-span-2"><span class="mb-1 block text-[13px] font-medium">Kế hoạch triển khai</span><MTextarea v-model="draft.plan" :disabled="saving"/></label><label class="sm:col-span-2"><span class="mb-1 block text-[13px] font-medium">Ghi chú</span><MTextarea v-model="draft.note" :disabled="saving"/></label></div><p v-if="error || localError" role="alert" class="mx-5 mb-4 rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{ error || localError }}</p><footer class="sticky bottom-0 flex justify-end gap-2 border-t border-[var(--mds-border-light)] bg-[var(--mds-bg)] px-5 py-3"><MButton variant="neutral" :disabled="saving" @click="emit('cancel')">Hủy</MButton><MButton variant="primary" :loading="saving" :disabled="saving" @click="submit">Lưu kỳ tham gia</MButton></footer></form></section></template>
