<script setup>
import { ref } from 'vue';
import MButton from '../../../components/mds/MButton.vue';
import MDialog from '../../../components/mds/MDialog.vue';
import MEmptyState from '../../../components/mds/MEmptyState.vue';

const props = defineProps({ items: { type: Array, default: () => [] }, canCreate: Boolean, canEdit: { type: Function, default: () => false }, canReassign: { type: Function, default: () => false }, canDelete: Boolean, error: String }); const emit = defineEmits(['add', 'edit', 'reassign', 'delete']); const deletingId = ref(null);
function requestDelete(id) { deletingId.value = id; } function confirmDelete() { if (deletingId.value) emit('delete', deletingId.value); deletingId.value = null; }
</script>

<template><section class="rounded-lg bg-[var(--mds-bg)] p-5 shadow-[var(--mds-shadow-card)]"><div class="flex items-start justify-between gap-3"><div><h2 class="text-[16px] font-semibold">Kỳ tham gia</h2><p class="mt-1 text-[13px] text-[var(--mds-text-secondary)]">Quyền tạo, sửa và xóa được máy chủ kiểm tra lại theo từng kỳ.</p></div><MButton v-if="canCreate" variant="neutral" @click="emit('add')">Thêm kỳ</MButton></div><div v-if="items.length" class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><article v-for="item in items" :key="item.id" class="rounded-lg bg-[var(--mds-bg-page)] p-3"><div class="flex items-start justify-between gap-2"><strong class="text-[13px]">{{ item.year }} · {{ item.status }}</strong><div class="flex gap-1"><MButton v-if="canEdit(item.id)" variant="link" @click="emit('edit', item.id)">Sửa</MButton><MButton v-if="canReassign(item.id)" variant="link" @click="emit('reassign', item.id)">Gán</MButton><MButton v-if="canDelete" variant="link" class="text-[var(--mds-danger)]" @click="requestDelete(item.id)">Xóa</MButton></div></div><p class="mt-1 text-[12px] text-[var(--mds-text-secondary)]">{{ item.products }} · {{ item.categories }}</p><p class="mt-2 text-[13px]">{{ item.result }}</p></article></div><MEmptyState v-else class="mt-4" title="Chưa có kỳ tham gia" description="Kỳ tham gia được phép xem sẽ xuất hiện tại đây."/><p v-if="error" role="alert" class="mt-4 rounded-lg bg-[var(--mds-danger-bg)] px-3 py-2 text-[13px] text-[var(--mds-danger)]">{{ error }}</p><MDialog :model-value="Boolean(deletingId)" title="Xóa kỳ tham gia?" type="danger" confirm-text="Xóa kỳ" @update:model-value="(open) => { if (!open) deletingId = null; }" @confirm="confirmDelete"><p>Không thể hoàn tác thao tác này.</p></MDialog></section></template>
